const art = {
  "academic painting": [{
    "Name": "academic painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Beige",
    "Color 2": "Beige",
    "Size": "1x1",
    "Real Artwork Title": "Vitruvian Man",
    "Artist": "Leonardo da Vinci, circa 1487, Pen and ink on paper",
    "Description": "This drawing is based on the 'ideal' human-body ratio, as stated in 'De architectura.' 'De architectura' was a treatise by Vitruvius, an architect from the early 1st century BCE.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtVitruvianMan",
    "Internal ID": "12619",
    "Unique Entry ID": "xfTf9sfyLkxHQEz4u"
  }, {
    "Name": "academic painting",
    "Genuine": "No",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Beige",
    "Color 2": "Beige",
    "Size": "1x1",
    "Real Artwork Title": "Vitruvian Man",
    "Artist": "Leonardo da Vinci, circa 1487, Pen and ink on paper",
    "Description": "This drawing is based on the 'ideal' human-body ratio, as stated in 'De architectura.' 'De architectura' was a treatise by Vitruvius, an architect from the early 1st century BCE.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtVitruvianManFake",
    "Internal ID": "12620",
    "Unique Entry ID": "5KNFAo3LkdTTJPQkd"
  }],
  "amazing painting": [{
    "Name": "amazing painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Black",
    "Color 2": "Black",
    "Size": "2x2",
    "Real Artwork Title": "The Night Watch",
    "Artist": "Rembrandt van Rijn, 1642, Oil on canvas",
    "Description": "This masterpiece, painted by 17th century Dutch artist Rembrandt, depicts a military gathering. At the time, portraits usually showed their subjects standing still. So this was a leap forward in technique. For many years, art scholars thought the painting was set at night, but a restoration revealed a dark varnish. We can now see the dynamic poses and lighting as they were meant to be seenâ€”in the daytime!",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtNightWatch",
    "Internal ID": "56",
    "Unique Entry ID": "Sg6MCSG3m9tvjGWoj"
  }, {
    "Name": "amazing painting",
    "Genuine": "No",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Black",
    "Color 2": "Black",
    "Size": "2x2",
    "Real Artwork Title": "The Night Watch",
    "Artist": "Rembrandt van Rijn, 1642, Oil on canvas",
    "Description": "This masterpiece, painted by 17th century Dutch artist Rembrandt, depicts a military gathering. At the time, portraits usually showed their subjects standing still. So this was a leap forward in technique. For many years, art scholars thought the painting was set at night, but a restoration revealed a dark varnish. We can now see the dynamic poses and lighting as they were meant to be seenâ€”in the daytime!",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtNightWatchFake",
    "Internal ID": "55",
    "Unique Entry ID": "vc2Ebu4Pkn443zYiN"
  }],
  "ancient statue": [{
    "Name": "ancient statue",
    "High-Res Texture": "NA",
    "Genuine": "Yes",
    "Category": "Miscellaneous",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Gray",
    "Color 2": "Gray",
    "Size": "1x1",
    "Real Artwork Title": "JÅmon Period 'DogÅ«' Figurine ShakÅki-dogÅ«",
    "Artist": "Artist Unknown, 1000-400 BCE, Fired pottery",
    "Description": "A mysterious, riveting doll made from kneaded, unglazed dirt during the JÅmon period. Its large round eyes resemble goggles that intercept light, so its name should come as no surprise. 'ShakÅki' means 'light-intercepting goggles,' and a dogÅ« is a small animal figurine.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "heritage",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureDoguu",
    "Internal ID": "1337",
    "Unique Entry ID": "zpAsguge9Yb29ksjS"
  }, {
    "Name": "ancient statue",
    "High-Res Texture": "NA",
    "Genuine": "No",
    "Category": "Miscellaneous",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Gray",
    "Color 2": "Gray",
    "Size": "1x1",
    "Real Artwork Title": "JÅmon Period 'DogÅ«' Figurine ShakÅki-dogÅ«",
    "Artist": "Artist Unknown, 1000-400 BCE, Fired pottery",
    "Description": "A mysterious, riveting doll made from kneaded, unglazed dirt during the JÅmon period. Its large round eyes resemble goggles that intercept light, so its name should come as no surprise. 'ShakÅki' means 'light-intercepting goggles,' and a dogÅ« is a small animal figurine.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "Yes",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureDoguuFake",
    "Internal ID": "1338",
    "Unique Entry ID": "fXbsrcXirg6miBoqT"
  }],
  "basic painting": [{
    "Name": "basic painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Black",
    "Color 2": "Blue",
    "Size": "1x2",
    "Real Artwork Title": "The Blue Boy",
    "Artist": "Thomas Gainsborough, 1770, Oil on canvas",
    "Description": "Gainsborough was known for his innovative use of colors in his traditional portraits, like this one. Although he preferred painting landscapes, his portraits would be the defining work of his career.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtBlueBoy",
    "Internal ID": "14",
    "Unique Entry ID": "Xhn8ZjtbdZeET3NXR"
  }, {
    "Name": "basic painting",
    "Genuine": "No",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Black",
    "Color 2": "Blue",
    "Size": "1x2",
    "Real Artwork Title": "The Blue Boy",
    "Artist": "Thomas Gainsborough, 1770, Oil on canvas",
    "Description": "Gainsborough was known for his innovative use of colors in his traditional portraits, like this one. Although he preferred painting landscapes, his portraits would be the defining work of his career.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtBlueBoyFake",
    "Internal ID": "13",
    "Unique Entry ID": "o4px7Mx9g2Zk6NHvC"
  }],
  "beautiful statue": [{
    "Name": "beautiful statue",
    "High-Res Texture": "NA",
    "Genuine": "Yes",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "White",
    "Color 2": "White",
    "Size": "1x1",
    "Real Artwork Title": "Venus de Milo",
    "Artist": "Artist Unknown, circa 130 BCE, Marble",
    "Description": "A statue of the Roman goddess of love and beauty, Venus was found on the island of Milos. This beautiful sculpture makes many wonder what her original pose might have been.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "heritage",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureMilo",
    "Internal ID": "1341",
    "Unique Entry ID": "iscap6FsmDZdNP5dw"
  }, {
    "Name": "beautiful statue",
    "High-Res Texture": "NA",
    "Genuine": "No",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "White",
    "Color 2": "White",
    "Size": "1x1",
    "Real Artwork Title": "Venus de Milo",
    "Artist": "Artist Unknown, circa 130 BCE, Marble",
    "Description": "A statue of the Roman goddess of love and beauty, Venus was found on the island of Milos. This beautiful sculpture makes many wonder what her original pose might have been.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureMiloFake",
    "Internal ID": "1342",
    "Unique Entry ID": "w9vrMbhJNj6JHkznu"
  }],
  "calm painting": [{
    "Name": "calm painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Green",
    "Color 2": "Gray",
    "Size": "2x1.5",
    "Real Artwork Title": "A Sunday Afternoon on the Island of La Grande Jatte",
    "Artist": "Georges Seurat, circa 1885, Oil on canvas",
    "Description": "Seurat, known as the founder of neo-impressionism, invented the use of brightly colored dots. His method, which does not involve mixing pigments, took time. This piece, for instance, took two years. It shows a crowd enjoying a day off at the river Seine in France.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtSundayOn",
    "Internal ID": "78",
    "Unique Entry ID": "7QgYY7KuhauCnS37H"
  }],
  "common painting": [{
    "Name": "common painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Beige",
    "Color 2": "White",
    "Size": "1x1",
    "Real Artwork Title": "The Gleaners",
    "Artist": "Jean-FranÃ§ois Millet, 1857, Oil on canvas",
    "Description": "The signature piece from Millet, who was known for depicting the lives of commoners in the 19th century.Notice the abundant crops visible in the background relative to the meager wheat remaining for workers.This art served as social commentary in a time of great inequality.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtGleaners",
    "Internal ID": "44",
    "Unique Entry ID": "GE6sppzKjqkG7sRoz"
  }],
  "detailed painting": [{
    "Name": "detailed painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Yellow",
    "Color 2": "Green",
    "Size": "1x2",
    "Real Artwork Title": "Ajisai SÅkeizu",
    "Artist": "ItÅ JakuchÅ«, 18th century, Dyed silk",
    "Description": "A detailed, colorful, and dynamic piece by ItÅ JakuchÅ«, a successful Kyoto artist in the mid-Edo period. High-quality paints on silk help it maintain its brilliant color even now, 200 years after its creation.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtAjisaisoukeizu",
    "Internal ID": "12622",
    "Unique Entry ID": "T2QA6mqARHfToTJpQ"
  }, {
    "Name": "detailed painting",
    "Genuine": "No",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Yellow",
    "Color 2": "Green",
    "Size": "1x2",
    "Real Artwork Title": "Ajisai SÅkeizu",
    "Artist": "ItÅ JakuchÅ«, 18th century, Dyed silk",
    "Description": "A detailed, colorful, and dynamic piece by ItÅ JakuchÅ«, a successful Kyoto artist in the mid-Edo period. High-quality paints on silk help it maintain its brilliant color even now, 200 years after its creation.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtAjisaisoukeizuFake",
    "Internal ID": "12623",
    "Unique Entry ID": "m9TkAsJFFkpQ9Hr4s"
  }],
  "dynamic painting": [{
    "Name": "dynamic painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Beige",
    "Color 2": "Beige",
    "Size": "1x1",
    "Real Artwork Title": "Thirty-Six Views of Mount Fuji The Great Wave off Kanagawa",
    "Artist": "Katsushika Hokusai, circa 1831, Woodblock print",
    "Description": "The signature piece of ukiyo-e artist Katsushika Hokusai, painted as part of a series when he was in his 60s. Although it is dubbed 'Thirty-Six Views,' he eventually added 10 more to make 46 in total.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtKanagawaOki",
    "Internal ID": "38",
    "Unique Entry ID": "BMBiEvuooPCwpzHj7"
  }],
  "familiar statue": [{
    "Name": "familiar statue",
    "High-Res Texture": "NA",
    "Genuine": "Yes",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Green",
    "Color 2": "Green",
    "Size": "1x1",
    "Real Artwork Title": "The Thinker",
    "Artist": "Auguste Rodin, 1902, Bronze",
    "Description": "This bronze sculpture was crafted by the French sculptor Rodin, known as the father of modern sculpture. The incredibly famous original is located in France. The sculpture was casted over 20 times. As such, authentic pieces can be found all around the world.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "heritage",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureThinker",
    "Internal ID": "12541",
    "Unique Entry ID": "e45RimLWaxcoBYLNq"
  }],
  "famous painting": [{
    "Name": "famous painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Black",
    "Color 2": "Beige",
    "Size": "1x1",
    "Real Artwork Title": "Mona Lisa",
    "Artist": "Leonardo da Vinci, circa 1503, Oil on poplar",
    "Description": "The world's most famous smile. It's said that da Vinci kept this painting for himself until the very end...Given its power to beguile visitors all these years later, it's easy to see why.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtMonaLisa",
    "Internal ID": "18",
    "Unique Entry ID": "23b6Mtp42pbXaLiGj"
  }, {
    "Name": "famous painting",
    "Genuine": "No",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Black",
    "Color 2": "Beige",
    "Size": "1x1",
    "Real Artwork Title": "Mona Lisa",
    "Artist": "Leonardo da Vinci, circa 1503, Oil on poplar",
    "Description": "The world's most famous smile. It's said that da Vinci kept this painting for himself until the very end...Given its power to beguile visitors all these years later, it's easy to see why.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtMonaLisaFake",
    "Internal ID": "17",
    "Unique Entry ID": "ppnz4rtJf2L6FK6YN"
  }],
  "flowery painting": [{
    "Name": "flowery painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Yellow",
    "Color 2": "Brown",
    "Size": "1x1",
    "Real Artwork Title": "Sunflowers",
    "Artist": "Vincent van Gogh, circa 1888, Oil on canvas",
    "Description": "Van Gogh painted this piece when he moved to the south of France in search of more vibrant colors. Yellow was Van Gogh's favorite color, and he made seven paintings that featured sunflowers during this time.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtSunflower",
    "Internal ID": "50",
    "Unique Entry ID": "aDZWPQ79YhLCMRqAE"
  }],
  "gallant statue": [{
    "Name": "gallant statue",
    "High-Res Texture": "NA",
    "Genuine": "Yes",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "White",
    "Color 2": "White",
    "Size": "2x2",
    "Real Artwork Title": "David",
    "Artist": "Michelangelo, circa 1504, Marble",
    "Description": "Young David glares at his enemies, sling slung over his shoulder. It took Michelangelo more than three years to sculpt this piece. Close inspection shows heart- shaped eyes, but that's probably meant to depict light hitting them. Hearts didn't have the lovey-dovey symbolism back then that they do today.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "heritage",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureDavid",
    "Internal ID": "1333",
    "Unique Entry ID": "hNbaWeaJCdihGnHM9"
  }, {
    "Name": "gallant statue",
    "High-Res Texture": "NA",
    "Genuine": "No",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "White",
    "Color 2": "White",
    "Size": "2x2",
    "Real Artwork Title": "David",
    "Artist": "Michelangelo, circa 1504, Marble",
    "Description": "Young David glares at his enemies, sling slung over his shoulder. It took Michelangelo more than three years to sculpt this piece. Close inspection shows heart- shaped eyes, but that's probably meant to depict light hitting them. Hearts didn't have the lovey-dovey symbolism back then that they do today.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureDavidFake",
    "Internal ID": "1334",
    "Unique Entry ID": "aoJwhWz4TTkNHrgg4"
  }],
  "glowing painting": [{
    "Name": "glowing painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Blue",
    "Color 2": "Gray",
    "Size": "1x1",
    "Real Artwork Title": "The Fighting Temeraire",
    "Artist": "Joseph Mallord William Turner, 1839, Oil on canvas",
    "Description": "A famous piece by Turner, a 'painter of light. 'It shows an English Navy ship commanded by Admiral Nelson as it's being tugged toward its dismantling.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtFightingTemeraire",
    "Internal ID": "12624",
    "Unique Entry ID": "89wbjB4u9oKjrKiZB"
  }],
  "graceful painting": [{
    "Name": "graceful painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Yellow",
    "Color 2": "Red",
    "Size": "1x2",
    "Real Artwork Title": "Beauty Looking Back",
    "Artist": "Hishikawa Moronobu, 17th century, Color on silk",
    "Description": "A hand-painted piece by Hishikawa Moronobu, an artist known for popularizing the ukiyo-e style. This stirring painting depicts a fashionable woman glancing back over her shoulder.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtMikaeri",
    "Internal ID": "6",
    "Unique Entry ID": "8M8N84TgtyATYSaPK"
  }, {
    "Name": "graceful painting",
    "Genuine": "No",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Yellow",
    "Color 2": "Red",
    "Size": "1x2",
    "Real Artwork Title": "Beauty Looking Back",
    "Artist": "Hishikawa Moronobu, 17th century, Color on silk",
    "Description": "A hand-painted piece by Hishikawa Moronobu, an artist known for popularizing the ukiyo-e style. This stirring painting depicts a fashionable woman glancing back over her shoulder.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtMikaeriFake",
    "Internal ID": "5",
    "Unique Entry ID": "PJCq2YjGNkP3rLYAs"
  }],
  "great statue": [{
    "Name": "great statue",
    "High-Res Texture": "NA",
    "Genuine": "Yes",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Black",
    "Color 2": "Yellow",
    "Size": "2x2",
    "Real Artwork Title": "King Kamehameha I",
    "Artist": "Thomas Ridgeway Gould, circa 1883, Bronze",
    "Description": "A bronze sculpture of King Kamehameha I, who founded the Kingdom of Hawaii in 1810. Traditionally, the sculpture is draped with many leis every year on June 11th.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "heritage",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureKamehameha",
    "Internal ID": "1339",
    "Unique Entry ID": "AAE89LXrdnv7yxs7p"
  }],
  "informative statue": [{
    "Name": "informative statue",
    "High-Res Texture": "NA",
    "Genuine": "Yes",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Black",
    "Color 2": "Black",
    "Size": "1x1",
    "Real Artwork Title": "Rosetta Stone",
    "Artist": "Artist Unknown, 196 BCE, Granodiorite",
    "Description": "A stone slab found in Rosetta, Egypt in 1799. Helped efforts to decipher ancient Egyptian hieroglyphs. Almost identical text is written in hieroglyphs at the top, then Demotic script, and lastly Greek script.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "heritage",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureRosettaStone",
    "Internal ID": "12535",
    "Unique Entry ID": "QW7tW8LLK5ReWvNeT"
  }, {
    "Name": "informative statue",
    "High-Res Texture": "NA",
    "Genuine": "No",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Blue",
    "Color 2": "Blue",
    "Size": "1x1",
    "Real Artwork Title": "Rosetta Stone",
    "Artist": "Artist Unknown, 196 BCE, Granodiorite",
    "Description": "A stone slab found in Rosetta, Egypt in 1799. Helped efforts to decipher ancient Egyptian hieroglyphs. Almost identical text is written in hieroglyphs at the top, then Demotic script, and lastly Greek script.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureRosettaStoneFake",
    "Internal ID": "12536",
    "Unique Entry ID": "qsBfFStS8mFJWotF3"
  }],
  "jolly painting": [{
    "Name": "jolly painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Black",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Real Artwork Title": "Summer",
    "Artist": "Giuseppe Arcimboldo, circa 1563, Oil on canvas",
    "Description": "A curious portrait by Giuseppe Arcimboldo, an Italian painter from the late 16th century. It doesn't take a particularly sharp eye to see that the entire portrait is composed of fresh produce.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtSummer",
    "Internal ID": "42",
    "Unique Entry ID": "JmuDLy5Gzy5L98TYi"
  }, {
    "Name": "jolly painting",
    "Genuine": "No",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Black",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Real Artwork Title": "Summer",
    "Artist": "Giuseppe Arcimboldo, circa 1563, Oil on canvas",
    "Description": "A curious portrait by Giuseppe Arcimboldo, an Italian painter from the late 16th century. It doesn't take a particularly sharp eye to see that the entire portrait is composed of fresh produce.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtSummerFake",
    "Internal ID": "41",
    "Unique Entry ID": "ndpzuYrx9RtgkuF4q"
  }],
  "moody painting": [{
    "Name": "moody painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Black",
    "Color 2": "Gray",
    "Size": "1x1",
    "Real Artwork Title": "The Sower",
    "Artist": "Jean-FranÃ§ois Millet, circa 1850, Oil on canvas",
    "Description": "Millet painted this piece of a farmer sowing wheat seeds in a field after moving to the countryside from Paris. If the piece reminds you of Van Gogh, that's likely because Van Gogh himself was inspired by it!",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtSlower",
    "Internal ID": "52",
    "Unique Entry ID": "BvTziFiDfmghDfn2f"
  }],
  "motherly statue": [{
    "Name": "motherly statue",
    "High-Res Texture": "NA",
    "Genuine": "Yes",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Black",
    "Color 2": "Gray",
    "Size": "2x1",
    "Real Artwork Title": "Capitoline Wolf",
    "Artist": "Artist Unknown, 5th century BCE, Bronze",
    "Description": "This wolf from Roman mythology raises a pair of twins, along with some controversy. The original bronze sculpture of the wolf is a masterpiece that dates back to 5th century BCE. The twins were added during the 15th century...or so it was thought.Recent research has given rise to speculation that the original piece may be from the 11th or 12th century. (We will, however, stick with the 5th century BCE estimate for now.)",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "heritage",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureCapitolini",
    "Internal ID": "1331",
    "Unique Entry ID": "CzWpdw9fWH7CSqvD4"
  }, {
    "Name": "motherly statue",
    "High-Res Texture": "NA",
    "Genuine": "No",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Black",
    "Color 2": "Gray",
    "Size": "2x1",
    "Real Artwork Title": "Capitoline Wolf",
    "Artist": "Artist Unknown, 5th century BCE, Bronze",
    "Description": "This wolf from Roman mythology raises a pair of twins, along with some controversy. The original bronze sculpture of the wolf is a masterpiece that dates back to 5th century BCE. The twins were added during the 15th century...or so it was thought.Recent research has given rise to speculation that the original piece may be from the 11th or 12th century. (We will, however, stick with the 5th century BCE estimate for now.)",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureCapitoliniFake",
    "Internal ID": "1332",
    "Unique Entry ID": "FQnkD6Ecica9g8hn6"
  }],
  "moving painting": [{
    "Name": "moving painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Aqua",
    "Color 2": "White",
    "Size": "2x1.5",
    "Real Artwork Title": "The Birth of Venus",
    "Artist": "Sandro Botticelli, circa 1485, Tempura on canvas",
    "Description": "A painting of the Roman goddess Venus riding a scallop shell after being born in the ocean. The name Botticelli is said to actually be a nickname given to the artist's brother, who was built like a barrel. Why this nickname was transferred between siblings is a mystery lost to the ages.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtBirthVenus",
    "Internal ID": "32",
    "Unique Entry ID": "CbpBJoxScgd7YkJ2a"
  }, {
    "Name": "moving painting",
    "Genuine": "No",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Aqua",
    "Color 2": "White",
    "Size": "2x1.5",
    "Real Artwork Title": "The Birth of Venus",
    "Artist": "Sandro Botticelli, circa 1485, Tempura on canvas",
    "Description": "A painting of the Roman goddess Venus riding a scallop shell after being born in the ocean. The name Botticelli is said to actually be a nickname given to the artist's brother, who was built like a barrel. Why this nickname was transferred between siblings is a mystery lost to the ages.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtBirthVenusFake",
    "Internal ID": "31",
    "Unique Entry ID": "8ji8jMXCQbeXcBZ4G"
  }],
  "mysterious painting": [{
    "Name": "mysterious painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Black",
    "Color 2": "Gray",
    "Size": "2x1",
    "Real Artwork Title": "Isle of The Dead",
    "Artist": "Arnold BÃ¶cklin, 1883, Oil on wood",
    "Description": "A small boat carrying a corpse glides quietly over a still sea to an island of graves surrounded by cliffs. The air of this piece by symbolist painter BÃ¶cklin is chilling, but also somehow calm. BÃ¶cklin worked here to capture not what he could see, but some of humanity's inner contemplations.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtIsleOfDead",
    "Internal ID": "12625",
    "Unique Entry ID": "jyEqfpiQxoJr7dFim"
  }],
  "mystic statue": [{
    "Name": "mystic statue",
    "High-Res Texture": "NA",
    "Genuine": "Yes",
    "Category": "Miscellaneous",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Beige",
    "Color 2": "Black",
    "Size": "1x1",
    "Real Artwork Title": "Bust of Nefertiti",
    "Artist": "Thutmose, circa 1345 BCE, Limestone",
    "Description": "A bust of Nefertiti, whose name means 'the beautiful one has come.' A 'royal wife,' she was known as one of the three most beautiful women in ancient Egypt. It is not known whether the left eye is missing because it fell out, or because it was never completed.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "heritage",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureNefertiti",
    "Internal ID": "1343",
    "Unique Entry ID": "m8rdQtfhuSxvLjbA7"
  }, {
    "Name": "mystic statue",
    "High-Res Texture": "NA",
    "Genuine": "No",
    "Category": "Miscellaneous",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Beige",
    "Color 2": "Black",
    "Size": "1x1",
    "Real Artwork Title": "Bust of Nefertiti",
    "Artist": "Thutmose, circa 1345 BCE, Limestone",
    "Description": "A bust of Nefertiti, whose name means 'the beautiful one has come.' A 'royal wife,' she was known as one of the three most beautiful women in ancient Egypt. It is not known whether the left eye is missing because it fell out, or because it was never completed.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureNefertitiFake",
    "Internal ID": "1344",
    "Unique Entry ID": "DPZFgiykKg576TMns"
  }],
  "nice painting": [{
    "Name": "nice painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Gray",
    "Color 2": "Red",
    "Size": "1x2",
    "Real Artwork Title": "The Fifer",
    "Artist": "Ã‰douard Manet, 1866, Oil on canvas",
    "Description": "One of Manet's earlier works, this painting depicts a young flautist dressed in military uniform. Manet's works are notable for their lack of linear perspective and strong color contrast. These attributes led some to call him 'The Father of Impressionism' and make comparisons to VÃ©lazquez. Fun fact-flautists can determine what note the boy is playing just by studying the painting closely.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtFifePlayer",
    "Internal ID": "48",
    "Unique Entry ID": "bE9epxYeiupMZXZBY"
  }],
  "perfect painting": [{
    "Name": "perfect painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Black",
    "Color 2": "Gray",
    "Size": "1x1",
    "Real Artwork Title": "Apples and Oranges",
    "Artist": "Paul CÃ©zanne, circa 1899, Oil on canvas",
    "Description": "This still life is known to have inspired the work of many other artists, including Pablo Picasso. Rather than trying to recreate an image, CÃ©zanne captured the beauty of shapes from many angles. With this work, CÃ©zanne draws on both the atmosphere of his subjects and the spirit of its beholders.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtAppleOrange",
    "Internal ID": "20",
    "Unique Entry ID": "GrTJQRodgefZ3ndPz"
  }],
  "proper painting": [{
    "Name": "proper painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Black",
    "Color 2": "Gray",
    "Size": "2x1",
    "Real Artwork Title": "A Bar at The Folies-BergÃ¨re",
    "Artist": "Ã‰douard Manet, circa 1882, Oil on canvas",
    "Description": "Close inspection of the mirror behind this painting's subject reveals many mysteries and paradoxes... In fact, the painting is based on multiple perspectives, which explains the unusual placement of some items. Sadly, this is Manet's last major work. He passed away a year after it was complete, at age 51.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtBarFB",
    "Internal ID": "46",
    "Unique Entry ID": "5MYg559uG6YjFrJLu"
  }],
  "quaint painting": [{
    "Name": "quaint painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "White",
    "Color 2": "Gray",
    "Size": "1x1",
    "Real Artwork Title": "The Milkmaid",
    "Artist": "Johannes Vermeer, circa 1658, Oil on canvas",
    "Description": "This piece earned Vermeer the nickname 'Master of Light' thanks to its exquisite contrast and depth. Vermeer painted this masterpiece at only 25 years of age. Many note that it is surprisingly small in real life.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtMilkmaid",
    "Internal ID": "10",
    "Unique Entry ID": "4eD8bxvcsNdFuJZy3"
  }, {
    "Name": "quaint painting",
    "Genuine": "No",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "White",
    "Color 2": "Gray",
    "Size": "1x1",
    "Real Artwork Title": "The Milkmaid",
    "Artist": "Johannes Vermeer, circa 1658, Oil on canvas",
    "Description": "This piece earned Vermeer the nickname 'Master of Light' thanks to its exquisite contrast and depth. Vermeer painted this masterpiece at only 25 years of age. Many note that it is surprisingly small in real life.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtMilkmaidFake",
    "Internal ID": "9",
    "Unique Entry ID": "A8oEDJdRDYCWWvgqP"
  }],
  "robust statue": [{
    "Name": "robust statue",
    "High-Res Texture": "NA",
    "Genuine": "Yes",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "White",
    "Color 2": "White",
    "Size": "2x1",
    "Real Artwork Title": "Discobolus",
    "Artist": "Artist Unknown, 2nd century CE, Marble",
    "Description": "This ancient Roman statue is based on the ancient Greek statue crafted by Myron. It's a piece that shows the grandeur of the human body, beautiful from any angle.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "heritage",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureDiskobolos",
    "Internal ID": "1335",
    "Unique Entry ID": "BMJTrZQQLrzhgFQ6T"
  }, {
    "Name": "robust statue",
    "High-Res Texture": "NA",
    "Genuine": "No",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "White",
    "Color 2": "White",
    "Size": "2x1",
    "Real Artwork Title": "Discobolus",
    "Artist": "Artist Unknown, 2nd century CE, Marble",
    "Description": "This ancient Roman statue is based on the ancient Greek statue crafted by Myron. It's a piece that shows the grandeur of the human body, beautiful from any angle.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureDiskobolosFake",
    "Internal ID": "1336",
    "Unique Entry ID": "JxRWC7dP3bSnrYafb"
  }],
  "rock-head statue": [{
    "Name": "rock-head statue",
    "High-Res Texture": "NA",
    "Genuine": "Yes",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Gray",
    "Color 2": "Gray",
    "Size": "2x2",
    "Real Artwork Title": "Olmec Colossal Head",
    "Artist": "Artist Unknown, circa 1000 BCE, Basalt, andesite",
    "Description": "Giant stone head thought to be from the ancient Mesoamerican Olmec civilization. The larger ones can reach three meters in height. Scholars think they only crafted heads, no bodies.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "heritage",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureOlmecaHead",
    "Internal ID": "12533",
    "Unique Entry ID": "yuq7wqkBtYpTh9cQs"
  }, {
    "Name": "rock-head statue",
    "High-Res Texture": "NA",
    "Genuine": "No",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Gray",
    "Color 2": "Gray",
    "Size": "2x2",
    "Real Artwork Title": "Olmec Colossal Head",
    "Artist": "Artist Unknown, circa 1000 BCE, Basalt, andesite",
    "Description": "Giant stone head thought to be from the ancient Mesoamerican Olmec civilization. The larger ones can reach three meters in height. Scholars think they only crafted heads, no bodies.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureOlmecaHeadFake",
    "Internal ID": "12534",
    "Unique Entry ID": "vgYniErBETSwYurmo"
  }],
  "scary painting": [{
    "Name": "scary painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Gray",
    "Color 2": "Gray",
    "Size": "1x1",
    "Real Artwork Title": "ÅŒtani Oniji the 3rd as Yakko Edobei",
    "Artist": "TÅshÅ«sai Sharaku, 1794, Woodblock print",
    "Description": "A print from the mid-Edo period by TÅshÅ«sai Sharaku depicting a famous actor of the time. Sharaku made roughly 140 ukiyo-e prints in his career, even though it only spanned around 10 months!",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtOotaniOniji",
    "Internal ID": "66",
    "Unique Entry ID": "mPutXzCMyFowYqPHu"
  }, {
    "Name": "scary painting",
    "Genuine": "No",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Gray",
    "Color 2": "Gray",
    "Size": "1x1",
    "Real Artwork Title": "ÅŒtani Oniji the 3rd as Yakko Edobei",
    "Artist": "TÅshÅ«sai Sharaku, 1794, Woodblock print",
    "Description": "A print from the mid-Edo period by TÅshÅ«sai Sharaku depicting a famous actor of the time. Sharaku made roughly 140 ukiyo-e prints in his career, even though it only spanned around 10 months!",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtOotaniOnijiFake",
    "Internal ID": "65",
    "Unique Entry ID": "xfEX3LgBZxdy8cWnv"
  }],
  "scenic painting": [{
    "Name": "scenic painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "White",
    "Color 2": "Aqua",
    "Size": "2x1.5",
    "Real Artwork Title": "The Hunters in The Snow",
    "Artist": "Pieter Brueghel the Elder, 1565, Oil on wood panel",
    "Description": "A landscape artist from the late Renaissance period, Brueghel was known as the 'Peasant Artist.' He earned the title for depicting scenes from common peasant life, such as the moment captured here. Note the contrast between the weary hunters and the people frolicking below on icy ponds.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtHunterSnow",
    "Internal ID": "2",
    "Unique Entry ID": "9zdd3tRyrgvHg7MHR"
  }, {
    "Name": "scenic painting",
    "Genuine": "No",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "White",
    "Color 2": "Aqua",
    "Size": "2x1.5",
    "Real Artwork Title": "The Hunters in The Snow",
    "Artist": "Pieter Brueghel the Elder, 1565, Oil on wood panel",
    "Description": "A landscape artist from the late Renaissance period, Brueghel was known as the 'Peasant Artist.' He earned the title for depicting scenes from common peasant life, such as the moment captured here. Note the contrast between the weary hunters and the people frolicking below on icy ponds.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtHunterSnowFake",
    "Internal ID": "12629",
    "Unique Entry ID": "xXvgi6GY62Kiy7ZPc"
  }],
  "serene painting": [{
    "Name": "serene painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Black",
    "Color 2": "Beige",
    "Size": "1x1",
    "Real Artwork Title": "Lady with an Ermine",
    "Artist": "Leonardo da Vinci, circa 1490, Oil on wood panel",
    "Description": "One of only four portraits of women painted by da Vinci, one of which is the 'Mona Lisa. 'Some believe that the 'ermine' is not actually an ermine, but rather a white ferret!",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtPortraitCecilia",
    "Internal ID": "24",
    "Unique Entry ID": "xWDYCn59iCuXXFYCa"
  }, {
    "Name": "serene painting",
    "Genuine": "No",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Black",
    "Color 2": "Beige",
    "Size": "1x1",
    "Real Artwork Title": "Lady with an Ermine",
    "Artist": "Leonardo da Vinci, circa 1490, Oil on wood panel",
    "Description": "One of only four portraits of women painted by da Vinci, one of which is the 'Mona Lisa. 'Some believe that the 'ermine' is not actually an ermine, but rather a white ferret!",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtPortraitCeciliaFake",
    "Internal ID": "23",
    "Unique Entry ID": "DAFG5byhuAns7SeNJ"
  }],
  "sinking painting": [{
    "Name": "sinking painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Green",
    "Color 2": "White",
    "Size": "1x1",
    "Real Artwork Title": "Ophelia",
    "Artist": "John Everett Millais, 1852, Oil on canvas",
    "Description": "Ophelia is a tragic figure in the Shakespearean play 'Hamlet.' There is an otherworldly expression on her face as she lies unconscious in a river. She is surrounded by the beauty of nature as she floats between life and death.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtOphelia",
    "Internal ID": "12621",
    "Unique Entry ID": "7ku7mD4CEkRPAfvgf"
  }],
  "solemn painting": [{
    "Name": "solemn painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Black",
    "Color 2": "Beige",
    "Size": "2x2",
    "Real Artwork Title": "Las Meninas",
    "Artist": "Diego VelÃ¡zquez, circa 1656, Oil on canvas",
    "Description": "This famous piece by VelÃ¡zquez, who served the Spanish court, shows us something about perspective. It depicts a young princess with her 'ladies-in-waiting.' The artist himself is seen to the left. The king and queen are reflected in the mirror to the artist's right, so the perspective is that of the king. The king...watching the artist...paint the king and the queen...",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtLasMeninas",
    "Internal ID": "72",
    "Unique Entry ID": "Rdxe9rejLcZB9FPPj"
  }, {
    "Name": "solemn painting",
    "Genuine": "No",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Black",
    "Color 2": "Beige",
    "Size": "2x2",
    "Real Artwork Title": "Las Meninas",
    "Artist": "Diego VelÃ¡zquez, circa 1656, Oil on canvas",
    "Description": "This famous piece by VelÃ¡zquez, who served the Spanish court, shows us something about perspective. It depicts a young princess with her 'ladies-in-waiting.' The artist himself is seen to the left. The king and queen are reflected in the mirror to the artist's right, so the perspective is that of the king. The king...watching the artist...paint the king and the queen...",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtLasMeninasFake",
    "Internal ID": "71",
    "Unique Entry ID": "nk6zayAkJFzinuKDK"
  }],
  "tremendous statue": [{
    "Name": "tremendous statue",
    "High-Res Texture": "NA",
    "Genuine": "Yes",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Green",
    "Color 2": "Green",
    "Size": "2x1",
    "Real Artwork Title": "Houmuwu Ding",
    "Artist": "Artist Unknown, 1200 BCE, Bronze",
    "Description": "This bronze ding from ancient China is the largest and heaviest ever found. The script on the inside suggests it was created to honor the king's mother.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "heritage",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureHoumuwuDing",
    "Internal ID": "12537",
    "Unique Entry ID": "jNGr7gorm7HSW3saj"
  }, {
    "Name": "tremendous statue",
    "High-Res Texture": "NA",
    "Genuine": "No",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Green",
    "Color 2": "Green",
    "Size": "2x1",
    "Real Artwork Title": "Houmuwu Ding",
    "Artist": "Artist Unknown, 1200 BCE, Bronze",
    "Description": "This bronze ding from ancient China is the largest and heaviest ever found. The script on the inside suggests it was created to honor the king's mother.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureHoumuwuDingFake",
    "Internal ID": "12538",
    "Unique Entry ID": "JixcFeWLnkcAy7rnu"
  }],
  "twinkling painting": [{
    "Name": "twinkling painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Blue",
    "Color 2": "Black",
    "Size": "1x1",
    "Real Artwork Title": "The Starry Night",
    "Artist": "Vincent van Gogh, 1889, Oil on canvas",
    "Description": "Van Gogh's signature piece, painted while he was hospitalized at an asylum. This view from his room includes memories and imaginations. In letters to friends, the artist called it a failure.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtStarryNight",
    "Internal ID": "12618",
    "Unique Entry ID": "vd2Naaf6TREFTQsdy"
  }],
  "valiant statue": [{
    "Name": "valiant statue",
    "High-Res Texture": "NA",
    "Genuine": "Yes",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "White",
    "Color 2": "White",
    "Size": "2x2",
    "Real Artwork Title": "Nike of Samothrace",
    "Artist": "Artist Unknown, circa 190 BCE, Marble",
    "Description": "A statue of the goddess of victory, Nike, found on Samothrace. It shows Nike alighting on the prow of a ship. Originally found in separate pieces, it has largely been restored, but the arms and head are still missing.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "heritage",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureSamothrace",
    "Internal ID": "1345",
    "Unique Entry ID": "stPbtNz5bpPCb3eRy"
  }, {
    "Name": "valiant statue",
    "High-Res Texture": "NA",
    "Genuine": "No",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "White",
    "Color 2": "White",
    "Size": "2x2",
    "Real Artwork Title": "Nike of Samothrace",
    "Artist": "Artist Unknown, circa 190 BCE, Marble",
    "Description": "A statue of the goddess of victory, Nike, found on Samothrace. It shows Nike alighting on the prow of a ship. Originally found in separate pieces, it has largely been restored, but the arms and head are still missing.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureSamothraceFake",
    "Internal ID": "1346",
    "Unique Entry ID": "FWFGsBRxrdnE4RSXa"
  }],
  "warm painting": [{
    "Name": "warm painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Black",
    "Color 2": "Gray",
    "Size": "2x1",
    "Real Artwork Title": "The Clothed Maja",
    "Artist": "Francisco de Goya, circa 1805, Oil on canvas",
    "Description": "It is said that this painting is a more discreet version of an earlier work known as 'The Nude Maja.' It is also known that Francisco de Goya was quite popular in his own time. Could these facts be related? A third, unrelated fact-the word 'maja' refers to a 'stylish young lady of Madrid.'",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtClothedMaja",
    "Internal ID": "34",
    "Unique Entry ID": "SD7NXc97t2b4f74xi"
  }],
  "warrior statue": [{
    "Name": "warrior statue",
    "High-Res Texture": "NA",
    "Genuine": "Yes",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Gray",
    "Color 2": "Gray",
    "Size": "1x1",
    "Real Artwork Title": "Terracotta Army",
    "Artist": "Artist Unknown, 210 BCE, Earthenware",
    "Description": "These terracotta warriors were buried with the first Qin emperor to protect him in the afterlife. Nearly 2,000 years later, in 1974, about 8,000 of them were found. Each statue is said to have been handmade with different poses, expressions, and clothing.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "heritage",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureHeibayo",
    "Internal ID": "12539",
    "Unique Entry ID": "5ZWqwpgKjNRGgT44E"
  }, {
    "Name": "warrior statue",
    "High-Res Texture": "NA",
    "Genuine": "No",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Gray",
    "Color 2": "Gray",
    "Size": "1x1",
    "Real Artwork Title": "Terracotta Army",
    "Artist": "Artist Unknown, 210 BCE, Earthenware",
    "Description": "These terracotta warriors were buried with the first Qin emperor to protect him in the afterlife. Nearly 2,000 years later, in 1974, about 8,000 of them were found. Each statue is said to have been handmade with different poses, expressions, and clothing.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Sculpture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrSculptureHeibayoFake",
    "Internal ID": "12540",
    "Unique Entry ID": "phB8tH4gdSYwq48Gs"
  }],
  "wild painting left half": [{
    "Name": "wild painting left half",
    "Genuine": "Yes",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Orange",
    "Color 2": "Brown",
    "Size": "2x1",
    "Real Artwork Title": "Folding Screen of FÅ«jin and Raijin",
    "Artist": "Tawaraya SÅtatsu, 17th century, Gold leaf and ink on paper",
    "Description": "This folding screen shows dynamic brushwork of FÅ«jin and Raijin on a gold-leaf background. It is thought to be the masterpiece of Tawaraya SÅtatsu, an early-Edo- period artist. The simplification of the subjects is a style that was carried on by Ogata KÅrin. It's a style still in use today in the Rinpa school of Japanese painting.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtRaijin",
    "Internal ID": "12570",
    "Unique Entry ID": "hMQkJiQG5cNGQxKCE"
  }, {
    "Name": "wild painting left half",
    "Genuine": "No",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Orange",
    "Color 2": "Brown",
    "Size": "2x1",
    "Real Artwork Title": "Folding Screen of FÅ«jin and Raijin",
    "Artist": "Tawaraya SÅtatsu, 17th century, Gold leaf and ink on paper",
    "Description": "This folding screen shows dynamic brushwork of FÅ«jin and Raijin on a gold-leaf background. It is thought to be the masterpiece of Tawaraya SÅtatsu, an early-Edo- period artist. The simplification of the subjects is a style that was carried on by Ogata KÅrin. It's a style still in use today in the Rinpa school of Japanese painting.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtRaijinFake",
    "Internal ID": "12571",
    "Unique Entry ID": "E9szuomHevSfq8yY3"
  }],
  "wild painting right half": [{
    "Name": "wild painting right half",
    "Genuine": "Yes",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Beige",
    "Color 2": "Brown",
    "Size": "2x1",
    "Real Artwork Title": "Folding Screen of FÅ«jin and Raijin",
    "Artist": "Tawaraya SÅtatsu, 17th century, Gold leaf and ink on paper",
    "Description": "This folding screen shows dynamic brushwork of FÅ«jin and Raijin on a gold-leaf background. It is thought to be the masterpiece of Tawaraya SÅtatsu, an early-Edo- period artist. The simplification of the subjects is a style that was carried on by Ogata KÅrin. It's a style still in use today in the Rinpa school of Japanese painting.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtFuujin",
    "Internal ID": "76",
    "Unique Entry ID": "rcXt6qMXZh9jj4ojN"
  }, {
    "Name": "wild painting right half",
    "Genuine": "No",
    "Category": "Housewares",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Beige",
    "Color 2": "Brown",
    "Size": "2x1",
    "Real Artwork Title": "Folding Screen of FÅ«jin and Raijin",
    "Artist": "Tawaraya SÅtatsu, 17th century, Gold leaf and ink on paper",
    "Description": "This folding screen shows dynamic brushwork of FÅ«jin and Raijin on a gold-leaf background. It is thought to be the masterpiece of Tawaraya SÅtatsu, an early-Edo- period artist. The simplification of the subjects is a style that was carried on by Ogata KÅrin. It's a style still in use today in the Rinpa school of Japanese painting.",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtFuujinFake",
    "Internal ID": "75",
    "Unique Entry ID": "aKefsi2sySXJkzPLo"
  }],
  "wistful painting": [{
    "Name": "wistful painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Black",
    "Color 2": "Beige",
    "Size": "1x1",
    "Real Artwork Title": "Girl with a Pearl Earring",
    "Artist": "Johannes Vermeer, circa 1665, Oil on canvas",
    "Description": "Also known as 'Girl with a Turban,' this piece uses ultramarine paint, which was expensive at the time. It seems the expense was worth it, as the vivid blue colors draw the eye and help make the piece a classic. The only question is... Is that a real pearl earring? Or something else...",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtPearlEarring",
    "Internal ID": "28",
    "Unique Entry ID": "Mupx2ny4sM3Kbfs3v"
  }, {
    "Name": "wistful painting",
    "Genuine": "No",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "0",
    "Color 1": "Black",
    "Color 2": "Beige",
    "Size": "1x1",
    "Real Artwork Title": "Girl with a Pearl Earring",
    "Artist": "Johannes Vermeer, circa 1665, Oil on canvas",
    "Description": "Also known as 'Girl with a Turban,' this piece uses ultramarine paint, which was expensive at the time. It seems the expense was worth it, as the vivid blue colors draw the eye and help make the piece a classic. The only question is... Is that a real pearl earring? Or something else...",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "17",
    "HHA Concept 1": "horror",
    "HHA Concept 2": "None",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtPearlEarringFake",
    "Internal ID": "27",
    "Unique Entry ID": "c7zw6f8Dbe5h9oJni"
  }],
  "worthy painting": [{
    "Name": "worthy painting",
    "Genuine": "Yes",
    "Category": "Wall-mounted",
    "Buy": "4980",
    "Sell": "1245",
    "Color 1": "Black",
    "Color 2": "Beige",
    "Size": "2x1.5",
    "Real Artwork Title": "Liberty Leading the People",
    "Artist": "EugÃ¨ne Delacroix, 1830, Oil on canvas",
    "Description": "Painted by leading 19th century Romantic artist Delacroix in the same year as a French revolution. The woman in the center is often mistaken for Joan of Arc, but she is actually the fictional 'Marianne.'",
    "Source": "Jolly Redd's Treasure Trawler",
    "HHA Base Points": "451",
    "HHA Concept 1": "expensive",
    "HHA Concept 2": "facility",
    "HHA Series": "None",
    "HHA Set": "None",
    "Interact": "No",
    "Tag": "Picture",
    "Speaker Type": "Does not play music",
    "Lighting Type": "No lighting",
    "Catalog": "Not for sale",
    "Version Added": "1.2.0",
    "Unlocked?": "Yes",
    "Filename": "FtrArtLibertyLeading",
    "Internal ID": "68",
    "Unique Entry ID": "8R3LhTWJzqHmPPPvK"
  }]
}

export default art;