const bags = {
  "957": [{
    "Name": "town backpack",
    "Variation": "Red",
    "DIY": "No",
    "Buy": "1040",
    "Sell": "260",
    "HHA Base Points": "23",
    "Color 1": "Red",
    "Color 2": "Red",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "everyday; outdoorsy",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackTown3",
    "ClothGroup ID": "957",
    "Internal ID": "11945",
    "Unique Entry ID": "wkeZwbrp9BoHTEPRZ"
  }, {
    "Name": "town backpack",
    "Variation": "Orange",
    "DIY": "No",
    "Buy": "1040",
    "Sell": "260",
    "HHA Base Points": "23",
    "Color 1": "Orange",
    "Color 2": "Orange",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "everyday; outdoorsy",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackTown1",
    "ClothGroup ID": "957",
    "Internal ID": "6839",
    "Unique Entry ID": "aZasytqebQRikaZZZ"
  }, {
    "Name": "town backpack",
    "Variation": "Green",
    "DIY": "No",
    "Buy": "1040",
    "Sell": "260",
    "HHA Base Points": "23",
    "Color 1": "Green",
    "Color 2": "Green",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "everyday; outdoorsy",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackTown0",
    "ClothGroup ID": "957",
    "Internal ID": "6838",
    "Unique Entry ID": "sm5eKnwyeNyKGXQLC"
  }, {
    "Name": "town backpack",
    "Variation": "Blue",
    "DIY": "No",
    "Buy": "1040",
    "Sell": "260",
    "HHA Base Points": "23",
    "Color 1": "Blue",
    "Color 2": "Blue",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "everyday; outdoorsy",
    "Sort Order": "4",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackTown2",
    "ClothGroup ID": "957",
    "Internal ID": "11944",
    "Unique Entry ID": "WGhvofsBw6pFs5c93"
  }],
  "958": [{
    "Name": "travel pouch",
    "Variation": "Pink",
    "DIY": "No",
    "Buy": "840",
    "Sell": "210",
    "HHA Base Points": "23",
    "Color 1": "Pink",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "everyday; outdoorsy",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderTravel0",
    "ClothGroup ID": "958",
    "Internal ID": "2550",
    "Unique Entry ID": "ygrWBZtknqDLLH8Rn"
  }, {
    "Name": "travel pouch",
    "Variation": "Green",
    "DIY": "No",
    "Buy": "840",
    "Sell": "210",
    "HHA Base Points": "23",
    "Color 1": "Green",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "everyday; outdoorsy",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderTravel1",
    "ClothGroup ID": "958",
    "Internal ID": "12000",
    "Unique Entry ID": "oX3GfBwtMfcQ4STtd"
  }, {
    "Name": "travel pouch",
    "Variation": "Light blue",
    "DIY": "No",
    "Buy": "840",
    "Sell": "210",
    "HHA Base Points": "23",
    "Color 1": "Aqua",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "everyday; outdoorsy",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderTravel2",
    "ClothGroup ID": "958",
    "Internal ID": "12001",
    "Unique Entry ID": "SSHDSgfSasCP6AgmW"
  }, {
    "Name": "travel pouch",
    "Variation": "Purple",
    "DIY": "No",
    "Buy": "840",
    "Sell": "210",
    "HHA Base Points": "23",
    "Color 1": "Purple",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "everyday; outdoorsy",
    "Sort Order": "4",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderTravel3",
    "ClothGroup ID": "958",
    "Internal ID": "12002",
    "Unique Entry ID": "HTjXg6MXwPZCwEtmJ"
  }],
  "962": [{
    "Name": "messenger bag",
    "Variation": "Black",
    "DIY": "No",
    "Buy": "840",
    "Sell": "210",
    "HHA Base Points": "23",
    "Color 1": "Black",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Active",
    "Label Themes": "everyday; outdoorsy; sporty",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderMessenger2",
    "ClothGroup ID": "962",
    "Internal ID": "11979",
    "Unique Entry ID": "ZuwiM4DzJF5Rsg46x"
  }, {
    "Name": "messenger bag",
    "Variation": "Orange",
    "DIY": "No",
    "Buy": "840",
    "Sell": "210",
    "HHA Base Points": "23",
    "Color 1": "Orange",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Active",
    "Label Themes": "everyday; outdoorsy; sporty",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderMessenger1",
    "ClothGroup ID": "962",
    "Internal ID": "11978",
    "Unique Entry ID": "sgxnCe87EdtdoKved"
  }, {
    "Name": "messenger bag",
    "Variation": "Green",
    "DIY": "No",
    "Buy": "840",
    "Sell": "210",
    "HHA Base Points": "23",
    "Color 1": "Green",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Active",
    "Label Themes": "everyday; outdoorsy; sporty",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderMessenger0",
    "ClothGroup ID": "962",
    "Internal ID": "7470",
    "Unique Entry ID": "7mPZ9PnTd46r65DXx"
  }],
  "963": [{
    "Name": "dry bag",
    "Variation": "Yellow",
    "DIY": "No",
    "Buy": "1040",
    "Sell": "260",
    "HHA Base Points": "23",
    "Color 1": "Yellow",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackDry0",
    "ClothGroup ID": "963",
    "Internal ID": "7471",
    "Unique Entry ID": "iwTpuxykXjSBi8b9a"
  }, {
    "Name": "dry bag",
    "Variation": "Blue",
    "DIY": "No",
    "Buy": "1040",
    "Sell": "260",
    "HHA Base Points": "23",
    "Color 1": "Blue",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackDry1",
    "ClothGroup ID": "963",
    "Internal ID": "11964",
    "Unique Entry ID": "cMoNDoZx2sdfD6Haz"
  }],
  "964": [{
    "Name": "pleather shoulder bag",
    "Variation": "Navy blue",
    "DIY": "No",
    "Buy": "2400",
    "Sell": "600",
    "HHA Base Points": "23",
    "Color 1": "Blue",
    "Color 2": "Blue",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Elegant",
    "Style 2": "Simple",
    "Label Themes": "everyday; formal",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderLeather1",
    "ClothGroup ID": "964",
    "Internal ID": "12009",
    "Unique Entry ID": "ZKgcPhGYErHShMrGR"
  }, {
    "Name": "pleather shoulder bag",
    "Variation": "Brown",
    "DIY": "No",
    "Buy": "2400",
    "Sell": "600",
    "HHA Base Points": "23",
    "Color 1": "Brown",
    "Color 2": "Brown",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Elegant",
    "Style 2": "Simple",
    "Label Themes": "everyday; formal",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderLeather0",
    "ClothGroup ID": "964",
    "Internal ID": "7476",
    "Unique Entry ID": "9AqRYq83NRMxrEWiD"
  }],
  "965": [{
    "Name": "fish pochette",
    "Variation": "NA",
    "DIY": "No",
    "Buy": "NFS",
    "Sell": "210",
    "HHA Base Points": "501",
    "Color 1": "Aqua",
    "Color 2": "Blue",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "C.J.",
    "Season/Event": "Fishing Tourney",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Cute",
    "Label Themes": "formal; party",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderFish0",
    "ClothGroup ID": "965",
    "Internal ID": "7477",
    "Unique Entry ID": "CrFcdF3rXiaiiajEB"
  }],
  "966": [{
    "Name": "tackle bag",
    "Variation": "NA",
    "DIY": "No",
    "Buy": "NFS",
    "Sell": "175",
    "HHA Base Points": "501",
    "Color 1": "Blue",
    "Color 2": "Orange",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "C.J.",
    "Season/Event": "Fishing Tourney",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; sporty; work",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderFishing0",
    "ClothGroup ID": "966",
    "Internal ID": "7478",
    "Unique Entry ID": "prkWCjgn7gTK4X8QH"
  }],
  "967": [{
    "Name": "bug cage",
    "Variation": "NA",
    "DIY": "No",
    "Buy": "NFS",
    "Sell": "122",
    "HHA Base Points": "501",
    "Color 1": "Green",
    "Color 2": "White",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Flick",
    "Season/Event": "Bug-Off",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; vacation",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderCage0",
    "ClothGroup ID": "967",
    "Internal ID": "7479",
    "Unique Entry ID": "nrkEKkL46YsQYcYjp"
  }],
  "968": [{
    "Name": "faux-fur bag",
    "Variation": "Pink",
    "DIY": "No",
    "Buy": "1400",
    "Sell": "350",
    "HHA Base Points": "23",
    "Color 1": "Pink",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Gorgeous",
    "Label Themes": "formal; party",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderFakefur0",
    "ClothGroup ID": "968",
    "Internal ID": "7480",
    "Unique Entry ID": "FyneYzGmHW7SyoHn7"
  }, {
    "Name": "faux-fur bag",
    "Variation": "Purple",
    "DIY": "No",
    "Buy": "1400",
    "Sell": "350",
    "HHA Base Points": "23",
    "Color 1": "Purple",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Gorgeous",
    "Label Themes": "formal; party",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderFakefur1",
    "ClothGroup ID": "968",
    "Internal ID": "12003",
    "Unique Entry ID": "gH3fn5rkmCrekWoJB"
  }],
  "969": [{
    "Name": "pleather fringe bag",
    "Variation": "White",
    "DIY": "No",
    "Buy": "2400",
    "Sell": "600",
    "HHA Base Points": "23",
    "Color 1": "White",
    "Color 2": "White",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Elegant",
    "Style 2": "Elegant",
    "Label Themes": "everyday; formal; party",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderFringe1",
    "ClothGroup ID": "969",
    "Internal ID": "12010",
    "Unique Entry ID": "fiM98m9CGgi6iATkQ"
  }, {
    "Name": "pleather fringe bag",
    "Variation": "Camel",
    "DIY": "No",
    "Buy": "2400",
    "Sell": "600",
    "HHA Base Points": "23",
    "Color 1": "Brown",
    "Color 2": "Brown",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Elegant",
    "Style 2": "Elegant",
    "Label Themes": "everyday; formal; party",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderFringe0",
    "ClothGroup ID": "969",
    "Internal ID": "7481",
    "Unique Entry ID": "7RYHreaA7o9huubNu"
  }],
  "970": [{
    "Name": "hand-knit pouch",
    "Variation": "Green",
    "DIY": "No",
    "Buy": "1250",
    "Sell": "312",
    "HHA Base Points": "23",
    "Color 1": "Green",
    "Color 2": "Green",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Elegant",
    "Style 2": "Simple",
    "Label Themes": "vacation",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderRace0",
    "ClothGroup ID": "970",
    "Internal ID": "7482",
    "Unique Entry ID": "taTKqY3xif2LhShrf"
  }, {
    "Name": "hand-knit pouch",
    "Variation": "Purple",
    "DIY": "No",
    "Buy": "1250",
    "Sell": "312",
    "HHA Base Points": "23",
    "Color 1": "Purple",
    "Color 2": "Purple",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Elegant",
    "Style 2": "Simple",
    "Label Themes": "vacation",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderRace1",
    "ClothGroup ID": "970",
    "Internal ID": "12004",
    "Unique Entry ID": "GLLrMeJCPd8Xn7fdr"
  }],
  "971": [{
    "Name": "crossbody bag",
    "Variation": "White",
    "DIY": "No",
    "Buy": "700",
    "Sell": "175",
    "HHA Base Points": "23",
    "Color 1": "White",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "everyday; outdoorsy; sporty",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackBody3",
    "ClothGroup ID": "971",
    "Internal ID": "11982",
    "Unique Entry ID": "FsyHb5QAf8DDvPC7y"
  }, {
    "Name": "crossbody bag",
    "Variation": "Pink",
    "DIY": "No",
    "Buy": "700",
    "Sell": "175",
    "HHA Base Points": "23",
    "Color 1": "Pink",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "everyday; outdoorsy; sporty",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackBody0",
    "ClothGroup ID": "971",
    "Internal ID": "7483",
    "Unique Entry ID": "zXtyCFHwWjnChTami"
  }, {
    "Name": "crossbody bag",
    "Variation": "Yellow",
    "DIY": "No",
    "Buy": "700",
    "Sell": "175",
    "HHA Base Points": "23",
    "Color 1": "Yellow",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "everyday; outdoorsy; sporty",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackBody2",
    "ClothGroup ID": "971",
    "Internal ID": "11981",
    "Unique Entry ID": "zX6ZX4puTojGuJgGj"
  }, {
    "Name": "crossbody bag",
    "Variation": "Green",
    "DIY": "No",
    "Buy": "700",
    "Sell": "175",
    "HHA Base Points": "23",
    "Color 1": "Green",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "everyday; outdoorsy; sporty",
    "Sort Order": "4",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackBody1",
    "ClothGroup ID": "971",
    "Internal ID": "11980",
    "Unique Entry ID": "tbfNwy8RmGztJdAnn"
  }],
  "972": [{
    "Name": "pleather crossbody bag",
    "Variation": "Black",
    "DIY": "No",
    "Buy": "1120",
    "Sell": "280",
    "HHA Base Points": "23",
    "Color 1": "Black",
    "Color 2": "White",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cool",
    "Style 2": "Simple",
    "Label Themes": "everyday; work",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackBodybag1",
    "ClothGroup ID": "972",
    "Internal ID": "12005",
    "Unique Entry ID": "QDPYGrpFNNir49uBe"
  }, {
    "Name": "pleather crossbody bag",
    "Variation": "Navy blue",
    "DIY": "No",
    "Buy": "1120",
    "Sell": "280",
    "HHA Base Points": "23",
    "Color 1": "Blue",
    "Color 2": "Brown",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cool",
    "Style 2": "Simple",
    "Label Themes": "everyday; work",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackBodybag0",
    "ClothGroup ID": "972",
    "Internal ID": "7484",
    "Unique Entry ID": "YQD8XMuvDbymAeKxt"
  }],
  "973": [{
    "Name": "crossbody boston bag",
    "Variation": "Red",
    "DIY": "No",
    "Buy": "1680",
    "Sell": "420",
    "HHA Base Points": "23",
    "Color 1": "Red",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Active",
    "Label Themes": "everyday; outdoorsy; sporty",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderDrum0",
    "ClothGroup ID": "973",
    "Internal ID": "7485",
    "Unique Entry ID": "8MwDxuHHvYM3XJpmy"
  }, {
    "Name": "crossbody boston bag",
    "Variation": "Blue",
    "DIY": "No",
    "Buy": "1680",
    "Sell": "420",
    "HHA Base Points": "23",
    "Color 1": "Blue",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Active",
    "Label Themes": "everyday; outdoorsy; sporty",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderDrum1",
    "ClothGroup ID": "973",
    "Internal ID": "12011",
    "Unique Entry ID": "w98ZrTQWiRMHyveaa"
  }],
  "974": [{
    "Name": "gumdrop shoulder bag",
    "Variation": "Pop",
    "DIY": "No",
    "Buy": "2000",
    "Sell": "500",
    "HHA Base Points": "23",
    "Color 1": "Pink",
    "Color 2": "Green",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Cute",
    "Label Themes": "everyday; comfy",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderPattern0",
    "ClothGroup ID": "974",
    "Internal ID": "7486",
    "Unique Entry ID": "mQZCwxcr6z3hq5Dgm"
  }, {
    "Name": "gumdrop shoulder bag",
    "Variation": "Cool",
    "DIY": "No",
    "Buy": "2000",
    "Sell": "500",
    "HHA Base Points": "23",
    "Color 1": "Purple",
    "Color 2": "Aqua",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Cute",
    "Label Themes": "everyday; comfy",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderPattern1",
    "ClothGroup ID": "974",
    "Internal ID": "12012",
    "Unique Entry ID": "JxHQbqWH73Q3GYKT8"
  }],
  "975": [{
    "Name": "cloth shoulder bag",
    "Variation": "Ivory",
    "DIY": "No",
    "Buy": "1400",
    "Sell": "350",
    "HHA Base Points": "23",
    "Color 1": "White",
    "Color 2": "White",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Simple",
    "Label Themes": "everyday",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderCanvas2",
    "ClothGroup ID": "975",
    "Internal ID": "12014",
    "Unique Entry ID": "NfkYKg5NoaWKBEpzN"
  }, {
    "Name": "cloth shoulder bag",
    "Variation": "Orange",
    "DIY": "No",
    "Buy": "1400",
    "Sell": "350",
    "HHA Base Points": "23",
    "Color 1": "Orange",
    "Color 2": "Orange",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Simple",
    "Label Themes": "everyday",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderCanvas1",
    "ClothGroup ID": "975",
    "Internal ID": "12013",
    "Unique Entry ID": "dcpCgBwji4QCYAy8k"
  }, {
    "Name": "cloth shoulder bag",
    "Variation": "Blue",
    "DIY": "No",
    "Buy": "1400",
    "Sell": "350",
    "HHA Base Points": "23",
    "Color 1": "Aqua",
    "Color 2": "Aqua",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Simple",
    "Label Themes": "everyday",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderCanvas0",
    "ClothGroup ID": "975",
    "Internal ID": "7487",
    "Unique Entry ID": "DzoRrArWrKtzn6Xzc"
  }],
  "976": [{
    "Name": "straw pochette",
    "Variation": "NA",
    "DIY": "No",
    "Buy": "980",
    "Sell": "245",
    "HHA Base Points": "23",
    "Color 1": "Brown",
    "Color 2": "Brown",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Elegant",
    "Label Themes": "comfy; vacation",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderRattan0",
    "ClothGroup ID": "976",
    "Internal ID": "7488",
    "Unique Entry ID": "CGs3z4dKEkH82FDyq"
  }],
  "977": [{
    "Name": "star pochette",
    "Variation": "NA",
    "DIY": "Yes",
    "Buy": "NFS",
    "Sell": "3000",
    "HHA Base Points": "103",
    "Color 1": "Yellow",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Crafting",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Gorgeous",
    "Label Themes": "fairy tale; party; vacation",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderStar0",
    "ClothGroup ID": "977",
    "Internal ID": "7489",
    "Unique Entry ID": "3WQ8vSWtHMjZ6YPtR"
  }],
  "978": [{
    "Name": "cherry-blossom pochette",
    "Variation": "NA",
    "DIY": "Yes",
    "Buy": "NFS",
    "Sell": "2400",
    "HHA Base Points": "201",
    "Color 1": "Pink",
    "Color 2": "Pink",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Crafting",
    "Season/Event": "cherry-blossom petals",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Cute",
    "Label Themes": "fairy tale",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderCherryblossoms0",
    "ClothGroup ID": "978",
    "Internal ID": "7490",
    "Unique Entry ID": "wwkZdhj9HzxZiqHys"
  }],
  "979": [{
    "Name": "maple-leaf pochette",
    "Variation": "NA",
    "DIY": "Yes",
    "Buy": "NFS",
    "Sell": "2400",
    "HHA Base Points": "201",
    "Color 1": "Orange",
    "Color 2": "Orange",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Crafting",
    "Season/Event": "maple leaves",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Cute",
    "Label Themes": "fairy tale",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderMaple0",
    "ClothGroup ID": "979",
    "Internal ID": "7491",
    "Unique Entry ID": "HJDH4dCPMQY9qQanL"
  }],
  "980": [{
    "Name": "acorn pochette",
    "Variation": "NA",
    "DIY": "Yes",
    "Buy": "NFS",
    "Sell": "2400",
    "HHA Base Points": "201",
    "Color 1": "Brown",
    "Color 2": "Green",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Crafting",
    "Season/Event": "acorns and pine cones",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Cute",
    "Label Themes": "fairy tale",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderAcorn0",
    "ClothGroup ID": "980",
    "Internal ID": "7492",
    "Unique Entry ID": "XiC7bNzTBAdb8zWwr"
  }],
  "981": [{
    "Name": "snowflake pochette",
    "Variation": "NA",
    "DIY": "Yes",
    "Buy": "NFS",
    "Sell": "2400",
    "HHA Base Points": "201",
    "Color 1": "Aqua",
    "Color 2": "White",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Crafting",
    "Season/Event": "snowflakes",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Elegant",
    "Style 2": "Cool",
    "Label Themes": "fairy tale; party; vacation",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderSnow0",
    "ClothGroup ID": "981",
    "Internal ID": "7493",
    "Unique Entry ID": "gW7R4HX8hjZEHAFtB"
  }],
  "982": [{
    "Name": "shellfish pochette",
    "Variation": "NA",
    "DIY": "Yes",
    "Buy": "NFS",
    "Sell": "10800",
    "HHA Base Points": "201",
    "Color 1": "White",
    "Color 2": "White",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Crafting",
    "Season/Event": "summer shells",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Elegant",
    "Label Themes": "fairy tale; vacation",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderShell0",
    "ClothGroup ID": "982",
    "Internal ID": "7494",
    "Unique Entry ID": "XEsQxMf7k9qvjYxPF"
  }],
  "983": [{
    "Name": "tool bag",
    "Variation": "NA",
    "DIY": "No",
    "Buy": "910",
    "Sell": "227",
    "HHA Base Points": "23",
    "Color 1": "Black",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; work",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderTool0",
    "ClothGroup ID": "983",
    "Internal ID": "7497",
    "Unique Entry ID": "KiXvv8fvv7CN5sFDx"
  }],
  "984": [{
    "Name": "retro sports bag",
    "Variation": "Red",
    "DIY": "No",
    "Buy": "1400",
    "Sell": "350",
    "HHA Base Points": "23",
    "Color 1": "White",
    "Color 2": "Red",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderSports1",
    "ClothGroup ID": "984",
    "Internal ID": "12007",
    "Unique Entry ID": "Lqtjq3rWFoy4Dv39C"
  }, {
    "Name": "retro sports bag",
    "Variation": "Blue",
    "DIY": "No",
    "Buy": "1400",
    "Sell": "350",
    "HHA Base Points": "23",
    "Color 1": "White",
    "Color 2": "Blue",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderSports0",
    "ClothGroup ID": "984",
    "Internal ID": "7302",
    "Unique Entry ID": "vY7qcZFdWb3HgSv7L"
  }, {
    "Name": "retro sports bag",
    "Variation": "Black",
    "DIY": "No",
    "Buy": "1400",
    "Sell": "350",
    "HHA Base Points": "23",
    "Color 1": "Black",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderSports2",
    "ClothGroup ID": "984",
    "Internal ID": "12008",
    "Unique Entry ID": "nGhHjk4GEKSQwvARA"
  }],
  "985": [{
    "Name": "sacoche bag",
    "Variation": "Black",
    "DIY": "No",
    "Buy": "980",
    "Sell": "245",
    "HHA Base Points": "23",
    "Color 1": "Black",
    "Color 2": "White",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderSacosh2",
    "ClothGroup ID": "985",
    "Internal ID": "11975",
    "Unique Entry ID": "NRYqQLN2Beq4jpDBJ"
  }, {
    "Name": "sacoche bag",
    "Variation": "Red",
    "DIY": "No",
    "Buy": "980",
    "Sell": "245",
    "HHA Base Points": "23",
    "Color 1": "Red",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderSacosh1",
    "ClothGroup ID": "985",
    "Internal ID": "11974",
    "Unique Entry ID": "LYnLwBnwTYcMp4fr9"
  }, {
    "Name": "sacoche bag",
    "Variation": "Blue",
    "DIY": "No",
    "Buy": "980",
    "Sell": "245",
    "HHA Base Points": "23",
    "Color 1": "Blue",
    "Color 2": "Green",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderSacosh0",
    "ClothGroup ID": "985",
    "Internal ID": "7304",
    "Unique Entry ID": "n82fhWWNSv8kyFJc2"
  }],
  "986": [{
    "Name": "evening bag",
    "Variation": "Black",
    "DIY": "No",
    "Buy": "1250",
    "Sell": "312",
    "HHA Base Points": "23",
    "Color 1": "Black",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Elegant",
    "Label Themes": "formal; party",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderParty2",
    "ClothGroup ID": "986",
    "Internal ID": "11977",
    "Unique Entry ID": "x9Z63uLS8cHdsoczj"
  }, {
    "Name": "evening bag",
    "Variation": "Pink",
    "DIY": "No",
    "Buy": "1250",
    "Sell": "312",
    "HHA Base Points": "23",
    "Color 1": "Pink",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Elegant",
    "Label Themes": "formal; party",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderParty0",
    "ClothGroup ID": "986",
    "Internal ID": "7305",
    "Unique Entry ID": "tZhGqzKpEeEweTZi7"
  }, {
    "Name": "evening bag",
    "Variation": "Blue",
    "DIY": "No",
    "Buy": "1250",
    "Sell": "312",
    "HHA Base Points": "23",
    "Color 1": "Blue",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Elegant",
    "Label Themes": "formal; party",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagShoulderParty1",
    "ClothGroup ID": "986",
    "Internal ID": "11976",
    "Unique Entry ID": "SoJkNi7GNiW28tYuG"
  }],
  "987": [{
    "Name": "log pack",
    "Variation": "NA",
    "DIY": "Yes",
    "Buy": "NFS",
    "Sell": "960",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Beige",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Crafting",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Simple",
    "Label Themes": "fairy tale; outdoorsy",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackWood0",
    "ClothGroup ID": "987",
    "Internal ID": "7498",
    "Unique Entry ID": "rDDM48hSfsSbcp92u"
  }],
  "988": [{
    "Name": "traveler's backpack",
    "Variation": "Orange",
    "DIY": "No",
    "Buy": "2940",
    "Sell": "735",
    "HHA Base Points": "23",
    "Color 1": "Orange",
    "Color 2": "Beige",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Active",
    "Label Themes": "fairy tale; outdoorsy; work",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackJourney0",
    "ClothGroup ID": "988",
    "Internal ID": "7499",
    "Unique Entry ID": "ag2m7kcBg83aCARGE"
  }, {
    "Name": "traveler's backpack",
    "Variation": "Blue",
    "DIY": "No",
    "Buy": "2940",
    "Sell": "735",
    "HHA Base Points": "23",
    "Color 1": "Blue",
    "Color 2": "Beige",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Active",
    "Label Themes": "fairy tale; outdoorsy; work",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackJourney1",
    "ClothGroup ID": "988",
    "Internal ID": "11965",
    "Unique Entry ID": "iprTWWTSARJtHTKqF"
  }, {
    "Name": "traveler's backpack",
    "Variation": "Brown",
    "DIY": "No",
    "Buy": "2940",
    "Sell": "735",
    "HHA Base Points": "23",
    "Color 1": "Brown",
    "Color 2": "Beige",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Active",
    "Label Themes": "fairy tale; outdoorsy; work",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackJourney2",
    "ClothGroup ID": "988",
    "Internal ID": "11966",
    "Unique Entry ID": "ehhBAiZqTHaTExHYP"
  }],
  "989": [{
    "Name": "square backpack",
    "Variation": "Pink",
    "DIY": "No",
    "Buy": "1300",
    "Sell": "325",
    "HHA Base Points": "23",
    "Color 1": "Pink",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "everyday; outdoorsy; sporty",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackSquare1",
    "ClothGroup ID": "989",
    "Internal ID": "11967",
    "Unique Entry ID": "wN6jaJRRvg6cQZXhk"
  }, {
    "Name": "square backpack",
    "Variation": "Yellow",
    "DIY": "No",
    "Buy": "1300",
    "Sell": "325",
    "HHA Base Points": "23",
    "Color 1": "Yellow",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "everyday; outdoorsy; sporty",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackSquare0",
    "ClothGroup ID": "989",
    "Internal ID": "7500",
    "Unique Entry ID": "2RYepaMxTnXMZ9tXg"
  }, {
    "Name": "square backpack",
    "Variation": "Green",
    "DIY": "No",
    "Buy": "1300",
    "Sell": "325",
    "HHA Base Points": "23",
    "Color 1": "Green",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "everyday; outdoorsy; sporty",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackSquare2",
    "ClothGroup ID": "989",
    "Internal ID": "11968",
    "Unique Entry ID": "rJain6G9X749mG5p7"
  }],
  "990": [{
    "Name": "outdoor backpack",
    "Variation": "Orange",
    "DIY": "No",
    "Buy": "1560",
    "Sell": "390",
    "HHA Base Points": "23",
    "Color 1": "Orange",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackOutdoor1",
    "ClothGroup ID": "990",
    "Internal ID": "11969",
    "Unique Entry ID": "hiF7bqmoudyFJPcWG"
  }, {
    "Name": "outdoor backpack",
    "Variation": "Avocado",
    "DIY": "No",
    "Buy": "1560",
    "Sell": "390",
    "HHA Base Points": "23",
    "Color 1": "Green",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackOutdoor0",
    "ClothGroup ID": "990",
    "Internal ID": "7501",
    "Unique Entry ID": "CAsQFPPeo3vBGpHSo"
  }, {
    "Name": "outdoor backpack",
    "Variation": "Navy blue",
    "DIY": "No",
    "Buy": "1560",
    "Sell": "390",
    "HHA Base Points": "23",
    "Color 1": "Blue",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackOutdoor2",
    "ClothGroup ID": "990",
    "Internal ID": "11970",
    "Unique Entry ID": "qd8DJb8mX5zhewgyn"
  }],
  "991": [{
    "Name": "butterfly backpack",
    "Variation": "NA",
    "DIY": "No",
    "Buy": "NFS",
    "Sell": "210",
    "HHA Base Points": "501",
    "Color 1": "Pink",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Flick",
    "Season/Event": "Bug-Off",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Cute",
    "Label Themes": "everyday; formal; party",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackButterfly0",
    "ClothGroup ID": "991",
    "Internal ID": "7502",
    "Unique Entry ID": "unsmeHZemRaTnq62z"
  }],
  "992": [{
    "Name": "studded backpack",
    "Variation": "White",
    "DIY": "No",
    "Buy": "1560",
    "Sell": "390",
    "HHA Base Points": "23",
    "Color 1": "White",
    "Color 2": "Gray",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cool",
    "Style 2": "Cute",
    "Label Themes": "everyday; goth",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackStuds1",
    "ClothGroup ID": "992",
    "Internal ID": "12006",
    "Unique Entry ID": "e6iev2NrSfaxSg5nr"
  }, {
    "Name": "studded backpack",
    "Variation": "Black",
    "DIY": "No",
    "Buy": "1560",
    "Sell": "390",
    "HHA Base Points": "23",
    "Color 1": "Black",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cool",
    "Style 2": "Cute",
    "Label Themes": "everyday; goth",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackStuds0",
    "ClothGroup ID": "992",
    "Internal ID": "7503",
    "Unique Entry ID": "mTMCDJnwtFJzvQ9rs"
  }],
  "993": [{
    "Name": "mini pleather bag",
    "Variation": "White",
    "DIY": "No",
    "Buy": "1600",
    "Sell": "400",
    "HHA Base Points": "23",
    "Color 1": "White",
    "Color 2": "White",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Elegant",
    "Style 2": "Elegant",
    "Label Themes": "everyday; formal; party",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackSmall0",
    "ClothGroup ID": "993",
    "Internal ID": "7504",
    "Unique Entry ID": "FyrYDDhzABDegtZ6n"
  }, {
    "Name": "mini pleather bag",
    "Variation": "Black",
    "DIY": "No",
    "Buy": "1600",
    "Sell": "400",
    "HHA Base Points": "23",
    "Color 1": "Black",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Elegant",
    "Style 2": "Elegant",
    "Label Themes": "everyday; formal; party",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackSmall1",
    "ClothGroup ID": "993",
    "Internal ID": "12015",
    "Unique Entry ID": "hYJk97FFi4zJGQ5cH"
  }],
  "994": [{
    "Name": "extra-large backpack",
    "Variation": "Black",
    "DIY": "No",
    "Buy": "2100",
    "Sell": "525",
    "HHA Base Points": "23",
    "Color 1": "Black",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackMountain2",
    "ClothGroup ID": "994",
    "Internal ID": "11972",
    "Unique Entry ID": "HqReXLwGPigWMiJbS"
  }, {
    "Name": "extra-large backpack",
    "Variation": "Red",
    "DIY": "No",
    "Buy": "2100",
    "Sell": "525",
    "HHA Base Points": "23",
    "Color 1": "Red",
    "Color 2": "Red",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackMountain0",
    "ClothGroup ID": "994",
    "Internal ID": "7505",
    "Unique Entry ID": "sjT2tZJCMpWQNmhTy"
  }, {
    "Name": "extra-large backpack",
    "Variation": "Green",
    "DIY": "No",
    "Buy": "2100",
    "Sell": "525",
    "HHA Base Points": "23",
    "Color 1": "Green",
    "Color 2": "Green",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackMountain1",
    "ClothGroup ID": "994",
    "Internal ID": "11971",
    "Unique Entry ID": "MKeBKrETSTs4tyrg4"
  }, {
    "Name": "extra-large backpack",
    "Variation": "Blue",
    "DIY": "No",
    "Buy": "2100",
    "Sell": "525",
    "HHA Base Points": "23",
    "Color 1": "Blue",
    "Color 2": "Blue",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "4",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackMountain3",
    "ClothGroup ID": "994",
    "Internal ID": "11973",
    "Unique Entry ID": "vvEqA5aMBGyycpQFz"
  }],
  "995": [{
    "Name": "basket pack",
    "Variation": "NA",
    "DIY": "Yes",
    "Buy": "NFS",
    "Sell": "2400",
    "HHA Base Points": "103",
    "Color 1": "Green",
    "Color 2": "Green",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Crafting",
    "Season/Event": "young spring bamboo",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Simple",
    "Label Themes": "outdoorsy; work",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackBasket0",
    "ClothGroup ID": "995",
    "Internal ID": "7506",
    "Unique Entry ID": "BW764rj9aH3QL6GRH"
  }],
  "996": [{
    "Name": "foldover-top backpack",
    "Variation": "Gray",
    "DIY": "No",
    "Buy": "1300",
    "Sell": "325",
    "HHA Base Points": "23",
    "Color 1": "Gray",
    "Color 2": "White",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackLid2",
    "ClothGroup ID": "996",
    "Internal ID": "12017",
    "Unique Entry ID": "Z8WFCNZodHtW2DBPB"
  }, {
    "Name": "foldover-top backpack",
    "Variation": "Pink",
    "DIY": "No",
    "Buy": "1300",
    "Sell": "325",
    "HHA Base Points": "23",
    "Color 1": "Pink",
    "Color 2": "Purple",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackLid3",
    "ClothGroup ID": "996",
    "Internal ID": "12018",
    "Unique Entry ID": "nD9TYBr8sw4rhLAyG"
  }, {
    "Name": "foldover-top backpack",
    "Variation": "Green",
    "DIY": "No",
    "Buy": "1300",
    "Sell": "325",
    "HHA Base Points": "23",
    "Color 1": "Green",
    "Color 2": "Beige",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackLid0",
    "ClothGroup ID": "996",
    "Internal ID": "7507",
    "Unique Entry ID": "nkXJ2eRThdt4vEpFb"
  }, {
    "Name": "foldover-top backpack",
    "Variation": "Blue",
    "DIY": "No",
    "Buy": "1300",
    "Sell": "325",
    "HHA Base Points": "23",
    "Color 1": "Blue",
    "Color 2": "Aqua",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "outdoorsy; sporty",
    "Sort Order": "4",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackLid1",
    "ClothGroup ID": "996",
    "Internal ID": "12016",
    "Unique Entry ID": "M8i2DNwxgXKWADAtW"
  }],
  "997": [{
    "Name": "knapsack",
    "Variation": "Black",
    "DIY": "No",
    "Buy": "630",
    "Sell": "157",
    "HHA Base Points": "23",
    "Color 1": "Black",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "everyday; outdoorsy; sporty",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackKnapsack1",
    "ClothGroup ID": "997",
    "Internal ID": "12019",
    "Unique Entry ID": "Fx4M2zpFTWGww54rw"
  }, {
    "Name": "knapsack",
    "Variation": "Blue",
    "DIY": "No",
    "Buy": "630",
    "Sell": "157",
    "HHA Base Points": "23",
    "Color 1": "Blue",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Simple",
    "Label Themes": "everyday; outdoorsy; sporty",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackKnapsack0",
    "ClothGroup ID": "997",
    "Internal ID": "7508",
    "Unique Entry ID": "XbKqQChpAJXng37Mr"
  }],
  "998": [{
    "Name": "canvas backpack",
    "Variation": "NA",
    "DIY": "No",
    "Buy": "1300",
    "Sell": "325",
    "HHA Base Points": "23",
    "Color 1": "White",
    "Color 2": "Orange",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Simple",
    "Label Themes": "everyday",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackTote0",
    "ClothGroup ID": "998",
    "Internal ID": "7509",
    "Unique Entry ID": "ZtgYddBwpZfGMjewu"
  }],
  "999": [{
    "Name": "Mom's knapsack",
    "Variation": "Forest print",
    "DIY": "No",
    "Buy": "NFS",
    "Sell": "175",
    "HHA Base Points": "365",
    "Color 1": "White",
    "Color 2": "Beige",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Mom",
    "Source Notes": "Received in May in the Northern Hemisphere and received in November in the Southern Hemisphere",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Active",
    "Label Themes": "comfy",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackQuilt6",
    "ClothGroup ID": "999",
    "Internal ID": "12153",
    "Unique Entry ID": "E3XrB5LbBTu795xbM"
  }, {
    "Name": "Mom's knapsack",
    "Variation": "Flowers",
    "DIY": "No",
    "Buy": "NFS",
    "Sell": "175",
    "HHA Base Points": "365",
    "Color 1": "Gray",
    "Color 2": "Beige",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Mom",
    "Source Notes": "Received in May in the Northern Hemisphere and received in November in the Southern Hemisphere",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Active",
    "Label Themes": "comfy",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackQuilt1",
    "ClothGroup ID": "999",
    "Internal ID": "12148",
    "Unique Entry ID": "gqy4s4zFowLbNKTd2"
  }, {
    "Name": "Mom's knapsack",
    "Variation": "Polka dots",
    "DIY": "No",
    "Buy": "NFS",
    "Sell": "175",
    "HHA Base Points": "365",
    "Color 1": "Pink",
    "Color 2": "Beige",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Mom",
    "Source Notes": "Received in May in the Northern Hemisphere and received in November in the Southern Hemisphere",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Active",
    "Label Themes": "comfy",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackQuilt2",
    "ClothGroup ID": "999",
    "Internal ID": "12149",
    "Unique Entry ID": "Hkju8Bjb8Kaamsu3j"
  }, {
    "Name": "Mom's knapsack",
    "Variation": "Chick",
    "DIY": "No",
    "Buy": "NFS",
    "Sell": "175",
    "HHA Base Points": "365",
    "Color 1": "Orange",
    "Color 2": "Beige",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Mom",
    "Source Notes": "Received in May in the Northern Hemisphere and received in November in the Southern Hemisphere",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Active",
    "Label Themes": "comfy",
    "Sort Order": "4",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackQuilt7",
    "ClothGroup ID": "999",
    "Internal ID": "12154",
    "Unique Entry ID": "jCi92aiMtZB92idfQ"
  }, {
    "Name": "Mom's knapsack",
    "Variation": "M",
    "DIY": "No",
    "Buy": "NFS",
    "Sell": "175",
    "HHA Base Points": "365",
    "Color 1": "Yellow",
    "Color 2": "Beige",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Mom",
    "Source Notes": "Received in May in the Northern Hemisphere and received in November in the Southern Hemisphere",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Active",
    "Label Themes": "comfy",
    "Sort Order": "5",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackQuilt0",
    "ClothGroup ID": "999",
    "Internal ID": "7510",
    "Unique Entry ID": "szhWnj6jpymTsKce8"
  }, {
    "Name": "Mom's knapsack",
    "Variation": "Cherries",
    "DIY": "No",
    "Buy": "NFS",
    "Sell": "175",
    "HHA Base Points": "365",
    "Color 1": "Aqua",
    "Color 2": "Beige",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Mom",
    "Source Notes": "Received in May in the Northern Hemisphere and received in November in the Southern Hemisphere",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Active",
    "Label Themes": "comfy",
    "Sort Order": "6",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackQuilt4",
    "ClothGroup ID": "999",
    "Internal ID": "12151",
    "Unique Entry ID": "46PX3NMjAdrNiRQXb"
  }, {
    "Name": "Mom's knapsack",
    "Variation": "Denim with stripes",
    "DIY": "No",
    "Buy": "NFS",
    "Sell": "175",
    "HHA Base Points": "365",
    "Color 1": "Blue",
    "Color 2": "Beige",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Mom",
    "Source Notes": "Received in May in the Northern Hemisphere and received in November in the Southern Hemisphere",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Active",
    "Label Themes": "comfy",
    "Sort Order": "7",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackQuilt5",
    "ClothGroup ID": "999",
    "Internal ID": "12152",
    "Unique Entry ID": "hj8ixCKXNWBnGZSrw"
  }, {
    "Name": "Mom's knapsack",
    "Variation": "Colorful quilt design",
    "DIY": "No",
    "Buy": "NFS",
    "Sell": "175",
    "HHA Base Points": "365",
    "Color 1": "Colorful",
    "Color 2": "Beige",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Mom",
    "Source Notes": "Received in May in the Northern Hemisphere and received in November in the Southern Hemisphere",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cute",
    "Style 2": "Active",
    "Label Themes": "comfy",
    "Sort Order": "8",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackQuilt3",
    "ClothGroup ID": "999",
    "Internal ID": "12150",
    "Unique Entry ID": "6uKkNZRz7E8gkSiBF"
  }],
  "1000": [{
    "Name": "knitted-grass backpack",
    "Variation": "NA",
    "DIY": "Yes",
    "Buy": "NFS",
    "Sell": "400",
    "HHA Base Points": "103",
    "Color 1": "Green",
    "Color 2": "Brown",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Crafting",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Elegant",
    "Style 2": "Simple",
    "Label Themes": "outdoorsy; comfy; vacation",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackGrass0",
    "ClothGroup ID": "1000",
    "Internal ID": "7511",
    "Unique Entry ID": "xM5iaYn4gbZoR94Qm"
  }],
  "1001": [{
    "Name": "hard-shell backpack",
    "Variation": "Silver",
    "DIY": "No",
    "Buy": "1680",
    "Sell": "420",
    "HHA Base Points": "23",
    "Color 1": "Gray",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cool",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; work",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackHardshell2",
    "ClothGroup ID": "1001",
    "Internal ID": "11946",
    "Unique Entry ID": "yxnDx8JQqzZDM66oR"
  }, {
    "Name": "hard-shell backpack",
    "Variation": "Red",
    "DIY": "No",
    "Buy": "1680",
    "Sell": "420",
    "HHA Base Points": "23",
    "Color 1": "Red",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cool",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; work",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackHardshell1",
    "ClothGroup ID": "1001",
    "Internal ID": "10184",
    "Unique Entry ID": "qdP3rmZ7P7HgA2cin"
  }, {
    "Name": "hard-shell backpack",
    "Variation": "Blue",
    "DIY": "No",
    "Buy": "1680",
    "Sell": "420",
    "HHA Base Points": "23",
    "Color 1": "Blue",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cool",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; work",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackHardshell0",
    "ClothGroup ID": "1001",
    "Internal ID": "7512",
    "Unique Entry ID": "LETQjE3yFDKze4ntv"
  }],
  "1150": [{
    "Name": "Nook Inc. knapsack",
    "Variation": "NA",
    "DIY": "No",
    "Buy": "NFS",
    "Sell": "4000",
    "HHA Base Points": "151",
    "Color 1": "Brown",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "800",
    "Exchange Currency": "Nook Miles",
    "Source": "Nook Miles Redemption",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Gorgeous",
    "Style 2": "Active",
    "Label Themes": "everyday",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackNook0",
    "ClothGroup ID": "1150",
    "Internal ID": "9761",
    "Unique Entry ID": "zQh6chGG66h4f5JbX"
  }],
  "1185": [{
    "Name": "DAL backpack",
    "Variation": "NA",
    "DIY": "No",
    "Buy": "NFS",
    "Sell": "1010",
    "HHA Base Points": "251",
    "Color 1": "Blue",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Dodo Airlines",
    "Source Notes": "Received in mail from DAL after 200 flights",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cool",
    "Style 2": "Active",
    "Label Themes": "outdoorsy; vacation",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackDal0",
    "ClothGroup ID": "1185",
    "Internal ID": "12131",
    "Unique Entry ID": "3mGmqSPj5YPujiDgD"
  }],
  "1203": [{
    "Name": "Bunny Day bag",
    "Variation": "NA",
    "DIY": "Yes",
    "Buy": "NFS",
    "Sell": "2400",
    "HHA Base Points": "351",
    "Color 1": "Colorful",
    "Color 2": "Colorful",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Crafting",
    "Season/Event": "Bunny Day (ready days); Bunny Day",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Active",
    "Style 2": "Cute",
    "Label Themes": "fairy tale; party; theatrical",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not for sale",
    "Version Added": "1.1.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackEgg0",
    "ClothGroup ID": "1203",
    "Internal ID": "12447",
    "Unique Entry ID": "YGofzAZknSTYWmfWM"
  }],
  "1233": [{
    "Name": "grape-harvest basket",
    "Variation": "NA",
    "DIY": "No",
    "Buy": "800",
    "Sell": "200",
    "HHA Base Points": "201",
    "Color 1": "Brown",
    "Color 2": "Purple",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Nook Shopping Seasonal",
    "Season/Event": "Grape Harvest Festival",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Simple",
    "Style 2": "Active",
    "Label Themes": "everyday; fairy tale; outdoorsy; party",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not in catalog",
    "Version Added": "1.4.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackHarvest0",
    "ClothGroup ID": "1233",
    "Internal ID": "12797",
    "Unique Entry ID": "w3sCtnjHaNJwLD3vk"
  }],
  "1268": [{
    "Name": "impish wings",
    "Variation": "White",
    "DIY": "No",
    "Buy": "1000",
    "Sell": "250",
    "HHA Base Points": "231",
    "Color 1": "White",
    "Color 2": "White",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "Halloween (ready days); Halloween",
    "Season/Event Exclusive": "No",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cool",
    "Style 2": "Cool",
    "Label Themes": "fairy tale; goth; party",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.5.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackHalloween2",
    "ClothGroup ID": "1268",
    "Internal ID": "13409",
    "Unique Entry ID": "CcDoJoDqXaXyMYBEx"
  }, {
    "Name": "impish wings",
    "Variation": "Black",
    "DIY": "No",
    "Buy": "1000",
    "Sell": "250",
    "HHA Base Points": "231",
    "Color 1": "Black",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "Halloween (ready days); Halloween",
    "Season/Event Exclusive": "No",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cool",
    "Style 2": "Cool",
    "Label Themes": "fairy tale; goth; party",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.5.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackHalloween5",
    "ClothGroup ID": "1268",
    "Internal ID": "13412",
    "Unique Entry ID": "8v2gEqEZYuMibTdvv"
  }, {
    "Name": "impish wings",
    "Variation": "Red",
    "DIY": "No",
    "Buy": "1000",
    "Sell": "250",
    "HHA Base Points": "231",
    "Color 1": "Red",
    "Color 2": "Red",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "Halloween (ready days); Halloween",
    "Season/Event Exclusive": "No",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cool",
    "Style 2": "Cool",
    "Label Themes": "fairy tale; goth; party",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.5.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackHalloween4",
    "ClothGroup ID": "1268",
    "Internal ID": "13411",
    "Unique Entry ID": "FZZmBDBcsCn9cx29J"
  }, {
    "Name": "impish wings",
    "Variation": "Orange",
    "DIY": "No",
    "Buy": "1000",
    "Sell": "250",
    "HHA Base Points": "231",
    "Color 1": "Orange",
    "Color 2": "Orange",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "Halloween (ready days); Halloween",
    "Season/Event Exclusive": "No",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cool",
    "Style 2": "Cool",
    "Label Themes": "fairy tale; goth; party",
    "Sort Order": "4",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.5.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackHalloween0",
    "ClothGroup ID": "1268",
    "Internal ID": "13015",
    "Unique Entry ID": "N5Ydq8EZ3TTsKv34c"
  }, {
    "Name": "impish wings",
    "Variation": "Green",
    "DIY": "No",
    "Buy": "1000",
    "Sell": "250",
    "HHA Base Points": "231",
    "Color 1": "Green",
    "Color 2": "Green",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "Halloween (ready days); Halloween",
    "Season/Event Exclusive": "No",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cool",
    "Style 2": "Cool",
    "Label Themes": "fairy tale; goth; party",
    "Sort Order": "5",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.5.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackHalloween3",
    "ClothGroup ID": "1268",
    "Internal ID": "13410",
    "Unique Entry ID": "spWkjYsT4mKfBijAz"
  }, {
    "Name": "impish wings",
    "Variation": "Purple",
    "DIY": "No",
    "Buy": "1000",
    "Sell": "250",
    "HHA Base Points": "231",
    "Color 1": "Purple",
    "Color 2": "Purple",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Kicks",
    "Season/Event": "Halloween (ready days); Halloween",
    "Season/Event Exclusive": "No",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Cool",
    "Style 2": "Cool",
    "Label Themes": "fairy tale; goth; party",
    "Sort Order": "6",
    "Villager Equippable": "No",
    "Catalog": "For sale",
    "Version Added": "1.5.0",
    "Unlocked?": "Yes",
    "Filename": "BagBackpackHalloween1",
    "ClothGroup ID": "1268",
    "Internal ID": "13408",
    "Unique Entry ID": "BqyY8XSWSswej9Lap"
  }],
  "1362": [{
    "Name": "prom sash",
    "Variation": "White",
    "DIY": "No",
    "Buy": "3500",
    "Sell": "875",
    "HHA Base Points": "201",
    "Color 1": "White",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Nook Shopping Seasonal",
    "Season/Event": "Prom (2)",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Gorgeous",
    "Style 2": "Elegant",
    "Label Themes": "party; work",
    "Sort Order": "1",
    "Villager Equippable": "No",
    "Catalog": "Not in catalog",
    "Version Added": "1.9.0",
    "Unlocked?": "No",
    "Filename": "BagShoulderTasukiprom4",
    "ClothGroup ID": "1362",
    "Internal ID": "14398",
    "Unique Entry ID": "FW8Smcrt8BGxf9Ctd"
  }, {
    "Name": "prom sash",
    "Variation": "Black",
    "DIY": "No",
    "Buy": "3500",
    "Sell": "875",
    "HHA Base Points": "201",
    "Color 1": "Black",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Nook Shopping Seasonal",
    "Season/Event": "Prom (2)",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Gorgeous",
    "Style 2": "Elegant",
    "Label Themes": "party; work",
    "Sort Order": "2",
    "Villager Equippable": "No",
    "Catalog": "Not in catalog",
    "Version Added": "1.9.0",
    "Unlocked?": "No",
    "Filename": "BagShoulderTasukiprom5",
    "ClothGroup ID": "1362",
    "Internal ID": "14399",
    "Unique Entry ID": "9NYe8ov5e89jnZbwX"
  }, {
    "Name": "prom sash",
    "Variation": "Red",
    "DIY": "No",
    "Buy": "3500",
    "Sell": "875",
    "HHA Base Points": "201",
    "Color 1": "Red",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Nook Shopping Seasonal",
    "Season/Event": "Prom (2)",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Gorgeous",
    "Style 2": "Elegant",
    "Label Themes": "party; work",
    "Sort Order": "3",
    "Villager Equippable": "No",
    "Catalog": "Not in catalog",
    "Version Added": "1.9.0",
    "Unlocked?": "No",
    "Filename": "BagShoulderTasukiprom0",
    "ClothGroup ID": "1362",
    "Internal ID": "14262",
    "Unique Entry ID": "nnRZEztbMkE8W2heC"
  }, {
    "Name": "prom sash",
    "Variation": "Gold",
    "DIY": "No",
    "Buy": "3500",
    "Sell": "875",
    "HHA Base Points": "201",
    "Color 1": "Yellow",
    "Color 2": "Black",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Nook Shopping Seasonal",
    "Season/Event": "Prom (2)",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Gorgeous",
    "Style 2": "Elegant",
    "Label Themes": "party; work",
    "Sort Order": "4",
    "Villager Equippable": "No",
    "Catalog": "Not in catalog",
    "Version Added": "1.9.0",
    "Unlocked?": "No",
    "Filename": "BagShoulderTasukiprom6",
    "ClothGroup ID": "1362",
    "Internal ID": "14400",
    "Unique Entry ID": "cEnSBEPXFjAxYwCSA"
  }, {
    "Name": "prom sash",
    "Variation": "Green",
    "DIY": "No",
    "Buy": "3500",
    "Sell": "875",
    "HHA Base Points": "201",
    "Color 1": "Green",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Nook Shopping Seasonal",
    "Season/Event": "Prom (2)",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Gorgeous",
    "Style 2": "Elegant",
    "Label Themes": "party; work",
    "Sort Order": "5",
    "Villager Equippable": "No",
    "Catalog": "Not in catalog",
    "Version Added": "1.9.0",
    "Unlocked?": "No",
    "Filename": "BagShoulderTasukiprom2",
    "ClothGroup ID": "1362",
    "Internal ID": "14396",
    "Unique Entry ID": "4yeToTMfBL93og2df"
  }, {
    "Name": "prom sash",
    "Variation": "Blue",
    "DIY": "No",
    "Buy": "3500",
    "Sell": "875",
    "HHA Base Points": "201",
    "Color 1": "Blue",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Nook Shopping Seasonal",
    "Season/Event": "Prom (2)",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Gorgeous",
    "Style 2": "Elegant",
    "Label Themes": "party; work",
    "Sort Order": "6",
    "Villager Equippable": "No",
    "Catalog": "Not in catalog",
    "Version Added": "1.9.0",
    "Unlocked?": "No",
    "Filename": "BagShoulderTasukiprom1",
    "ClothGroup ID": "1362",
    "Internal ID": "14395",
    "Unique Entry ID": "w6X2SpfPsjYWxd9oS"
  }, {
    "Name": "prom sash",
    "Variation": "Purple",
    "DIY": "No",
    "Buy": "3500",
    "Sell": "875",
    "HHA Base Points": "201",
    "Color 1": "Purple",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Exchange Price": "NA",
    "Exchange Currency": "NA",
    "Source": "Nook Shopping Seasonal",
    "Season/Event": "Prom (2)",
    "Season/Event Exclusive": "Yes",
    "Seasonal Availability": "All Year",
    "Seasonality": "All Year",
    "Gender": "Free",
    "Style 1": "Gorgeous",
    "Style 2": "Elegant",
    "Label Themes": "party; work",
    "Sort Order": "7",
    "Villager Equippable": "No",
    "Catalog": "Not in catalog",
    "Version Added": "1.9.0",
    "Unlocked?": "No",
    "Filename": "BagShoulderTasukiprom3",
    "ClothGroup ID": "1362",
    "Internal ID": "14397",
    "Unique Entry ID": "3qy9db9JiHZwbkAXr"
  }]
}

export default bags;