const music = {
  "Agent K.K.": {
    "group": [{
      "Name": "Agent K.K.",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Orange",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Keiji",
      "Internal ID": "2472",
      "Unique Entry ID": "omxkkikQ5jwtoGiXa"
    }],
    "type": "Music"
  },
  "Aloha K.K.": {
    "group": [{
      "Name": "Aloha K.K.",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Aqua",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Aloha",
      "Internal ID": "2423",
      "Unique Entry ID": "rxKK6nfmC4rWvXxCv"
    }],
    "type": "Music"
  },
  "Animal City": {
    "group": [{
      "Name": "Animal City",
      "Buy": "NFS",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "None",
      "Size": "1x1",
      "Source": "K.K. concert",
      "Source Notes": "Hidden song - only by request",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_DoubutuNoMachi",
      "Internal ID": "4312",
      "Unique Entry ID": "PTLK2jL5rb7t5Rm5j"
    }],
    "type": "Music"
  },
  "Bubblegum K.K.": {
    "group": [{
      "Name": "Bubblegum K.K.",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Aqua",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Idol",
      "Internal ID": "2492",
      "Unique Entry ID": "ZgwCoTem6x9efZAnD"
    }],
    "type": "Music"
  },
  "CafÃ© K.K.": {
    "group": [{
      "Name": "CafÃ© K.K.",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Colorful",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Paris",
      "Internal ID": "2454",
      "Unique Entry ID": "ZXwXi8YnFpks2RPuK"
    }],
    "type": "Music"
  },
  "Comrade K.K.": {
    "group": [{
      "Name": "Comrade K.K.",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "White",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_ShowaKayo",
      "Internal ID": "2448",
      "Unique Entry ID": "5ufeoTSFwRxQTrXdq"
    }],
    "type": "Music"
  },
  "DJ K.K.": {
    "group": [{
      "Name": "DJ K.K.",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Pink",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_EuroBeat",
      "Internal ID": "2443",
      "Unique Entry ID": "6H8pzhuYdfNpD8KTd"
    }],
    "type": "Music"
  },
  "Drivin'": {
    "group": [{
      "Name": "Drivin'",
      "Buy": "NFS",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "None",
      "Size": "1x1",
      "Source": "K.K. concert",
      "Source Notes": "Hidden song - only by request",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Drive",
      "Internal ID": "4314",
      "Unique Entry ID": "at7FbmJfbKvsGHB5T"
    }],
    "type": "Music"
  },
  "Farewell": {
    "group": [{
      "Name": "Farewell",
      "Buy": "NFS",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "None",
      "Size": "1x1",
      "Source": "K.K. concert",
      "Source Notes": "Hidden song - only by request",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Sayonara",
      "Internal ID": "4313",
      "Unique Entry ID": "diprrz97SbCJGzXM3"
    }],
    "type": "Music"
  },
  "Forest Life": {
    "group": [{
      "Name": "Forest Life",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Yellow",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_MoriNoSeikatsu",
      "Internal ID": "2461",
      "Unique Entry ID": "ZM4S88gPPapGknNeR"
    }],
    "type": "Music"
  },
  "Go K.K. Rider": {
    "group": [{
      "Name": "Go K.K. Rider",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "White",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_KekeRider",
      "Internal ID": "2450",
      "Unique Entry ID": "w6jLsBX6ZX4oPDwDh"
    }],
    "type": "Music"
  },
  "Hypno K.K.": {
    "group": [{
      "Name": "Hypno K.K.",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "White",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_UtataneNoYume",
      "Internal ID": "2480",
      "Unique Entry ID": "qwHrcscJZNxD5mn8k"
    }],
    "type": "Music"
  },
  "I Love You": {
    "group": [{
      "Name": "I Love You",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Colorful",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Daisuki",
      "Internal ID": "2458",
      "Unique Entry ID": "cic3w9hqeY222ni2z"
    }],
    "type": "Music"
  },
  "Imperial K.K.": {
    "group": [{
      "Name": "Imperial K.K.",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Pink",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_China",
      "Internal ID": "2427",
      "Unique Entry ID": "6y3ftdfGBa3oYAfrA"
    }],
    "type": "Music"
  },
  "K.K. Adventure": {
    "group": [{
      "Name": "K.K. Adventure",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Orange",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Hollywood",
      "Internal ID": "2484",
      "Unique Entry ID": "6FWZByesWNcjXBPQX"
    }],
    "type": "Music"
  },
  "K.K. Aria": {
    "group": [{
      "Name": "K.K. Aria",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Blue",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Maria",
      "Internal ID": "2413",
      "Unique Entry ID": "9ZSqWa7JjfMhwPWEE"
    }],
    "type": "Music"
  },
  "K.K. Ballad": {
    "group": [{
      "Name": "K.K. Ballad",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Black",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Ballad",
      "Internal ID": "2447",
      "Unique Entry ID": "awbEqrBQ52aCi4YKj"
    }],
    "type": "Music"
  },
  "K.K. Bazaar": {
    "group": [{
      "Name": "K.K. Bazaar",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Black",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Roma",
      "Internal ID": "2486",
      "Unique Entry ID": "yJdhdZPjGQSs4xL7a"
    }],
    "type": "Music"
  },
  "K.K. Birthday": {
    "group": [{
      "Name": "K.K. Birthday",
      "Buy": "NFS",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Aqua",
      "Size": "1x1",
      "Source": "K.K. concert",
      "Source Notes": "Received on your first time seeing K.K. perform during your birthday",
      "Season/Event": "Birthday",
      "Season/Event Exclusive": "Yes",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_BirthdaySong",
      "Internal ID": "2495",
      "Unique Entry ID": "xrFkTdiZ9fHkYMvDr"
    }],
    "type": "Music"
  },
  "K.K. Blues": {
    "group": [{
      "Name": "K.K. Blues",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "White",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Blues",
      "Internal ID": "2436",
      "Unique Entry ID": "HtTcKk7AdJLrmwXXK"
    }],
    "type": "Music"
  },
  "K.K. Bossa": {
    "group": [{
      "Name": "K.K. Bossa",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "White",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Bossa",
      "Internal ID": "2415",
      "Unique Entry ID": "Bu3tGw6JnhnMEabz2"
    }],
    "type": "Music"
  },
  "K.K. Calypso": {
    "group": [{
      "Name": "K.K. Calypso",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "White",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Caripso",
      "Internal ID": "2416",
      "Unique Entry ID": "g7TbqwnzRw64kcmso"
    }],
    "type": "Music"
  },
  "K.K. Casbah": {
    "group": [{
      "Name": "K.K. Casbah",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Beige",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Turkey",
      "Internal ID": "2428",
      "Unique Entry ID": "CuWyihNkLbL5rwbYZ"
    }],
    "type": "Music"
  },
  "K.K. Chorale": {
    "group": [{
      "Name": "K.K. Chorale",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Beige",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Sanbika",
      "Internal ID": "2405",
      "Unique Entry ID": "rijxxXt45dqkXze5A"
    }],
    "type": "Music"
  },
  "K.K. Condor": {
    "group": [{
      "Name": "K.K. Condor",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Beige",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Peru",
      "Internal ID": "2425",
      "Unique Entry ID": "EoALBg9oEc9NmJpaf"
    }],
    "type": "Music"
  },
  "K.K. Country": {
    "group": [{
      "Name": "K.K. Country",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Black",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Country",
      "Internal ID": "2445",
      "Unique Entry ID": "rN2cyPLzaZaMGmrwj"
    }],
    "type": "Music"
  },
  "K.K. Cruisin'": {
    "group": [{
      "Name": "K.K. Cruisin'",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Black",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Urban",
      "Internal ID": "2439",
      "Unique Entry ID": "hPBjqhB66YBw6Tz4n"
    }],
    "type": "Music"
  },
  "K.K. D&B": {
    "group": [{
      "Name": "K.K. D&B",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Colorful",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Drumnbass",
      "Internal ID": "2441",
      "Unique Entry ID": "rkBHJtfrcabbt57bD"
    }],
    "type": "Music"
  },
  "K.K. Dirge": {
    "group": [{
      "Name": "K.K. Dirge",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Black",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_KowaiUta",
      "Internal ID": "2451",
      "Unique Entry ID": "2DDYNvo8uNo5zNPo8"
    }],
    "type": "Music"
  },
  "K.K. Disco": {
    "group": [{
      "Name": "K.K. Disco",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Colorful",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Disco",
      "Internal ID": "2494",
      "Unique Entry ID": "tAZn6EXuFip47sbbo"
    }],
    "type": "Music"
  },
  "K.K. Dixie": {
    "group": [{
      "Name": "K.K. Dixie",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Colorful",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Dixie",
      "Internal ID": "2464",
      "Unique Entry ID": "bCL6Df8hoG7kooXcL"
    }],
    "type": "Music"
  },
  "K.K. Ã‰tude": {
    "group": [{
      "Name": "K.K. Ã‰tude",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Black",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Etude",
      "Internal ID": "2411",
      "Unique Entry ID": "PgDmhWq5W4ciF6TW5"
    }],
    "type": "Music"
  },
  "K.K. Faire": {
    "group": [{
      "Name": "K.K. Faire",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Orange",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Haisai",
      "Internal ID": "2422",
      "Unique Entry ID": "3i2RNpZeHPhxq6bPY"
    }],
    "type": "Music"
  },
  "K.K. Flamenco": {
    "group": [{
      "Name": "K.K. Flamenco",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Red",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Flamenco",
      "Internal ID": "2490",
      "Unique Entry ID": "KXRPPacevShYgCh33"
    }],
    "type": "Music"
  },
  "K.K. Folk": {
    "group": [{
      "Name": "K.K. Folk",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Colorful",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Minyo",
      "Internal ID": "2430",
      "Unique Entry ID": "L9SqkeaoQNXGphs6H"
    }],
    "type": "Music"
  },
  "K.K. Fusion": {
    "group": [{
      "Name": "K.K. Fusion",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Colorful",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Fusion",
      "Internal ID": "2410",
      "Unique Entry ID": "Lx9Kk9gmmori3huxC"
    }],
    "type": "Music"
  },
  "K.K. Groove": {
    "group": [{
      "Name": "K.K. Groove",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Blue",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Raregroove",
      "Internal ID": "2488",
      "Unique Entry ID": "7ss8K3czErhJNQiXJ"
    }],
    "type": "Music"
  },
  "K.K. Gumbo": {
    "group": [{
      "Name": "K.K. Gumbo",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Beige",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_NewOrleans",
      "Internal ID": "2434",
      "Unique Entry ID": "nPNjtqN3AJdfxLuAx"
    }],
    "type": "Music"
  },
  "K.K. House": {
    "group": [{
      "Name": "K.K. House",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Pink",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_House",
      "Internal ID": "2478",
      "Unique Entry ID": "DoMmMBQBeXm7sTGPm"
    }],
    "type": "Music"
  },
  "K.K. Island": {
    "group": [{
      "Name": "K.K. Island",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Aqua",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_DoubutsuNoShima",
      "Internal ID": "2482",
      "Unique Entry ID": "LrdjwBdn7hS2NXeW2"
    }],
    "type": "Music"
  },
  "K.K. Jazz": {
    "group": [{
      "Name": "K.K. Jazz",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Aqua",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Jazz",
      "Internal ID": "2409",
      "Unique Entry ID": "eRNA3ktNpPi8qB5Yx"
    }],
    "type": "Music"
  },
  "K.K. Jongara": {
    "group": [{
      "Name": "K.K. Jongara",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Aqua",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Jongara",
      "Internal ID": "2489",
      "Unique Entry ID": "2tqAXsz3eiAFcZ5aS"
    }],
    "type": "Music"
  },
  "K.K. Lament": {
    "group": [{
      "Name": "K.K. Lament",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Gray",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Enka",
      "Internal ID": "2449",
      "Unique Entry ID": "LLDo3zTdcLf3JRexf"
    }],
    "type": "Music"
  },
  "K.K. Love Song": {
    "group": [{
      "Name": "K.K. Love Song",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "White",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_LoveSong",
      "Internal ID": "2440",
      "Unique Entry ID": "Zi4kijYWbE3taJy67"
    }],
    "type": "Music"
  },
  "K.K. Lullaby": {
    "group": [{
      "Name": "K.K. Lullaby",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Green",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Lullaby",
      "Internal ID": "2412",
      "Unique Entry ID": "WpCHmL6DBXK7RWQNJ"
    }],
    "type": "Music"
  },
  "K.K. Mambo": {
    "group": [{
      "Name": "K.K. Mambo",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Red",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Mambo",
      "Internal ID": "2418",
      "Unique Entry ID": "LftoxEHoft5xpn8ZK"
    }],
    "type": "Music"
  },
  "K.K. Marathon": {
    "group": [{
      "Name": "K.K. Marathon",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Colorful",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Gamelan",
      "Internal ID": "2465",
      "Unique Entry ID": "EAeRF5hCvgZvpf24R"
    }],
    "type": "Music"
  },
  "K.K. March": {
    "group": [{
      "Name": "K.K. March",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Pink",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_March",
      "Internal ID": "2406",
      "Unique Entry ID": "ZYeSh5EHDgX9bEY4L"
    }],
    "type": "Music"
  },
  "K.K. Mariachi": {
    "group": [{
      "Name": "K.K. Mariachi",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Orange",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Senor",
      "Internal ID": "2456",
      "Unique Entry ID": "yK4cu9gRJDzAchPip"
    }],
    "type": "Music"
  },
  "K.K. Metal": {
    "group": [{
      "Name": "K.K. Metal",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Purple",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Metal",
      "Internal ID": "2474",
      "Unique Entry ID": "TNdpcZiy6ZXb2sie3"
    }],
    "type": "Music"
  },
  "K.K. Milonga": {
    "group": [{
      "Name": "K.K. Milonga",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Red",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Milonga",
      "Internal ID": "2487",
      "Unique Entry ID": "bphgD53QrTdSQWrsw"
    }],
    "type": "Music"
  },
  "K.K. Moody": {
    "group": [{
      "Name": "K.K. Moody",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Orange",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Bolero",
      "Internal ID": "2491",
      "Unique Entry ID": "D3WoTWs7t3uojthok"
    }],
    "type": "Music"
  },
  "K.K. Oasis": {
    "group": [{
      "Name": "K.K. Oasis",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Colorful",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Maharaja",
      "Internal ID": "2485",
      "Unique Entry ID": "X45bf37FawXymbRTR"
    }],
    "type": "Music"
  },
  "K.K. Parade": {
    "group": [{
      "Name": "K.K. Parade",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Colorful",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Parade",
      "Internal ID": "2455",
      "Unique Entry ID": "vaxtch9tWPZTeJKBf"
    }],
    "type": "Music"
  },
  "K.K. Ragtime": {
    "group": [{
      "Name": "K.K. Ragtime",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Gray",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_RagTime",
      "Internal ID": "2433",
      "Unique Entry ID": "Rz7khNvFcekonfDC8"
    }],
    "type": "Music"
  },
  "K.K. Rally": {
    "group": [{
      "Name": "K.K. Rally",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Red",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Ondo",
      "Internal ID": "2473",
      "Unique Entry ID": "qPCRJqX3uM66bDrDb"
    }],
    "type": "Music"
  },
  "K.K. Reggae": {
    "group": [{
      "Name": "K.K. Reggae",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Colorful",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Reggae",
      "Internal ID": "2419",
      "Unique Entry ID": "BeXTGzse56iMWrovn"
    }],
    "type": "Music"
  },
  "K.K. Rock": {
    "group": [{
      "Name": "K.K. Rock",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Black",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Rock",
      "Internal ID": "2431",
      "Unique Entry ID": "dGWQ49YGhQ6uxxdth"
    }],
    "type": "Music"
  },
  "K.K. Rockabilly": {
    "group": [{
      "Name": "K.K. Rockabilly",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Aqua",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_KekeBilly",
      "Internal ID": "2471",
      "Unique Entry ID": "DogQSJB5472T5PTgX"
    }],
    "type": "Music"
  },
  "K.K. Safari": {
    "group": [{
      "Name": "K.K. Safari",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Orange",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Afro",
      "Internal ID": "2429",
      "Unique Entry ID": "YxQuKist5jbDN6YeX"
    }],
    "type": "Music"
  },
  "K.K. Salsa": {
    "group": [{
      "Name": "K.K. Salsa",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Red",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Salsa",
      "Internal ID": "2417",
      "Unique Entry ID": "hMAkxLymhpg5Zt6Xm"
    }],
    "type": "Music"
  },
  "K.K. Samba": {
    "group": [{
      "Name": "K.K. Samba",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Aqua",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Samba",
      "Internal ID": "2414",
      "Unique Entry ID": "XYFSnTG8QFbGXZJ79"
    }],
    "type": "Music"
  },
  "K.K. Ska": {
    "group": [{
      "Name": "K.K. Ska",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Black",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Ska",
      "Internal ID": "2420",
      "Unique Entry ID": "TMiRa4nHYSbtCx4Em"
    }],
    "type": "Music"
  },
  "K.K. Sonata": {
    "group": [{
      "Name": "K.K. Sonata",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "White",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Sonata",
      "Internal ID": "2479",
      "Unique Entry ID": "zxHYzEN2Q7gt5JYMm"
    }],
    "type": "Music"
  },
  "K.K. Song": {
    "group": [{
      "Name": "K.K. Song",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Colorful",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_KekeSong",
      "Internal ID": "2457",
      "Unique Entry ID": "xjLPmvzuXaBSZx4Fy"
    }],
    "type": "Music"
  },
  "K.K. Soul": {
    "group": [{
      "Name": "K.K. Soul",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Black",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Soul",
      "Internal ID": "2438",
      "Unique Entry ID": "mXvujh5YZscWL5pKg"
    }],
    "type": "Music"
  },
  "K.K. Steppe": {
    "group": [{
      "Name": "K.K. Steppe",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Colorful",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Cossack",
      "Internal ID": "2426",
      "Unique Entry ID": "mGhDWyj7f83gryu4g"
    }],
    "type": "Music"
  },
  "K.K. Stroll": {
    "group": [{
      "Name": "K.K. Stroll",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "White",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Osanpo",
      "Internal ID": "2481",
      "Unique Entry ID": "QmR5zsjrqjsYdDcYy"
    }],
    "type": "Music"
  },
  "K.K. Swing": {
    "group": [{
      "Name": "K.K. Swing",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Beige",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Swing",
      "Internal ID": "2408",
      "Unique Entry ID": "BxCLYKFj8yeJMqxwD"
    }],
    "type": "Music"
  },
  "K.K. Synth": {
    "group": [{
      "Name": "K.K. Synth",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "White",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Electronica",
      "Internal ID": "2493",
      "Unique Entry ID": "S7sa9ugfRSHNPr9zX"
    }],
    "type": "Music"
  },
  "K.K. Tango": {
    "group": [{
      "Name": "K.K. Tango",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Black",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Tango",
      "Internal ID": "2421",
      "Unique Entry ID": "9gwFYo6HKxqfxnimX"
    }],
    "type": "Music"
  },
  "K.K. Technopop": {
    "group": [{
      "Name": "K.K. Technopop",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Black",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_TechnoBeat",
      "Internal ID": "2442",
      "Unique Entry ID": "opZrX852viqZH7RJX"
    }],
    "type": "Music"
  },
  "K.K. Waltz": {
    "group": [{
      "Name": "K.K. Waltz",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Red",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Waltz",
      "Internal ID": "2407",
      "Unique Entry ID": "pYKWYuRTejcTphjzd"
    }],
    "type": "Music"
  },
  "K.K. Western": {
    "group": [{
      "Name": "K.K. Western",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Gray",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Western",
      "Internal ID": "2452",
      "Unique Entry ID": "AnjsMygxJozFjZCGC"
    }],
    "type": "Music"
  },
  "King K.K.": {
    "group": [{
      "Name": "King K.K.",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Yellow",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Daimyo",
      "Internal ID": "2466",
      "Unique Entry ID": "B6siK6dLxCJACfGZY"
    }],
    "type": "Music"
  },
  "Lucky K.K.": {
    "group": [{
      "Name": "Lucky K.K.",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "White",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Irish",
      "Internal ID": "2424",
      "Unique Entry ID": "jCGA9eAgRjkLuNf2q"
    }],
    "type": "Music"
  },
  "Marine Song 2001": {
    "group": [{
      "Name": "Marine Song 2001",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Aqua",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_HunaUta2001",
      "Internal ID": "2468",
      "Unique Entry ID": "F8BvgZMycRgAjJv2A"
    }],
    "type": "Music"
  },
  "Mountain Song": {
    "group": [{
      "Name": "Mountain Song",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Aqua",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Alpine",
      "Internal ID": "2467",
      "Unique Entry ID": "5gDvnQ4uLnLwL85MK"
    }],
    "type": "Music"
  },
  "Mr. K.K.": {
    "group": [{
      "Name": "Mr. K.K.",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Beige",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Sensei",
      "Internal ID": "2453",
      "Unique Entry ID": "tGCobmkpe7AKsPmyn"
    }],
    "type": "Music"
  },
  "My Place": {
    "group": [{
      "Name": "My Place",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Green",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_BokuNoBasho",
      "Internal ID": "2460",
      "Unique Entry ID": "gQvdSw38P4QZwpkCh"
    }],
    "type": "Music"
  },
  "Neapolitan": {
    "group": [{
      "Name": "Neapolitan",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Black",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Napolitan",
      "Internal ID": "2469",
      "Unique Entry ID": "GDhwzHPsaEws6ciix"
    }],
    "type": "Music"
  },
  "Only Me": {
    "group": [{
      "Name": "Only Me",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Gray",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_OnlyMe",
      "Internal ID": "2444",
      "Unique Entry ID": "wwhnr7dEdx36E8SRv"
    }],
    "type": "Music"
  },
  "Pondering": {
    "group": [{
      "Name": "Pondering",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Black",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_KangaeChu",
      "Internal ID": "2463",
      "Unique Entry ID": "Gkk2Ck8DK627tiZkS"
    }],
    "type": "Music"
  },
  "Rockin' K.K.": {
    "group": [{
      "Name": "Rockin' K.K.",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Black",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_RocknRoll",
      "Internal ID": "2432",
      "Unique Entry ID": "asXTn3mfi7tzowcuj"
    }],
    "type": "Music"
  },
  "Soulful K.K.": {
    "group": [{
      "Name": "Soulful K.K.",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Orange",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Gospel",
      "Internal ID": "2437",
      "Unique Entry ID": "g2F79ptmGzFrrFf55"
    }],
    "type": "Music"
  },
  "Space K.K.": {
    "group": [{
      "Name": "Space K.K.",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "White",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Minimal",
      "Internal ID": "2483",
      "Unique Entry ID": "WbnqF3FqDQYJwfXed"
    }],
    "type": "Music"
  },
  "Spring Blossoms": {
    "group": [{
      "Name": "Spring Blossoms",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Pink",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_HaruNoKomorebi",
      "Internal ID": "2476",
      "Unique Entry ID": "q4ZmbxwwgjaNzvR4e"
    }],
    "type": "Music"
  },
  "Stale Cupcakes": {
    "group": [{
      "Name": "Stale Cupcakes",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Blue",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_BlueOnigiri",
      "Internal ID": "2475",
      "Unique Entry ID": "wh9i62k97gw3B34ER"
    }],
    "type": "Music"
  },
  "Steep Hill": {
    "group": [{
      "Name": "Steep Hill",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Orange",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_NiDanZaka",
      "Internal ID": "2470",
      "Unique Entry ID": "v3WHjrpgdgeZ3jaFC"
    }],
    "type": "Music"
  },
  "Surfin' K.K.": {
    "group": [{
      "Name": "Surfin' K.K.",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Blue",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Eleki",
      "Internal ID": "2446",
      "Unique Entry ID": "HEX474yLBRZ5xY5Pv"
    }],
    "type": "Music"
  },
  "The K. Funk": {
    "group": [{
      "Name": "The K. Funk",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Orange",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Funk",
      "Internal ID": "2435",
      "Unique Entry ID": "8ciaF2Yxuhc5Jqpar"
    }],
    "type": "Music"
  },
  "To the Edge": {
    "group": [{
      "Name": "To the Edge",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "White",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_NamiNami",
      "Internal ID": "2462",
      "Unique Entry ID": "P5ABGwMHvnYiFHcQN"
    }],
    "type": "Music"
  },
  "Two Days Ago": {
    "group": [{
      "Name": "Two Days Ago",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Black",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Ototoi",
      "Internal ID": "2459",
      "Unique Entry ID": "AzAHbHLA9oY2ihxrq"
    }],
    "type": "Music"
  },
  "Wandering": {
    "group": [{
      "Name": "Wandering",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Gray",
      "Size": "1x1",
      "Source": "K.K. concert; Nook Shopping Daily Selection",
      "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Horo",
      "Internal ID": "2477",
      "Unique Entry ID": "eDgjD4iS8sHZ64k3k"
    }],
    "type": "Music"
  },
  "Welcome Horizons": {
    "group": [{
      "Name": "Welcome Horizons",
      "Buy": "NFS",
      "Sell": "800",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "None",
      "Size": "1x1",
      "Source": "K.K. concert",
      "Source Notes": "Received on your first time seeing K.K. perform",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_MainTheme",
      "Internal ID": "4318",
      "Unique Entry ID": "eBR8TwgdbAKWEQc3T"
    }],
    "type": "Music"
  },
  "Hazure01": {
    "group": [{
      "Name": "Hazure01",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "0",
      "Color 1": "None",
      "Color 2": "None",
      "Size": "1x1",
      "Source": "K.K. concert",
      "Source Notes": "Played by K.K. if you request something he doesn't have (does not give take-home track)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "Not in catalog",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Miss1",
      "Internal ID": "4315",
      "Unique Entry ID": "yzpTLMjxFrMMyPe9t"
    }],
    "type": "Music"
  },
  "Hazure02": {
    "group": [{
      "Name": "Hazure02",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "0",
      "Color 1": "None",
      "Color 2": "None",
      "Size": "1x1",
      "Source": "K.K. concert",
      "Source Notes": "Played by K.K. if you request something he doesn't have (does not give take-home track)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "Not in catalog",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Miss2",
      "Internal ID": "4316",
      "Unique Entry ID": "oeZ6a9qJA54fyuwA3"
    }],
    "type": "Music"
  },
  "Hazure03": {
    "group": [{
      "Name": "Hazure03",
      "Buy": "3200",
      "Sell": "800",
      "HHA Base Points": "0",
      "Color 1": "None",
      "Color 2": "None",
      "Size": "1x2",
      "Source": "K.K. concert",
      "Source Notes": "Played by K.K. if you request something he doesn't have (does not give take-home track)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Catalog": "Not in catalog",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "mjk_Miss3",
      "Internal ID": "4317",
      "Unique Entry ID": "cXrvAEgQstHcnP5Zf"
    }],
    "type": "Music"
  }
}
export default music;