const music = {
  "Agent K.K.": [{
    "Name": "Agent K.K.",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Orange",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Keiji",
    "Internal ID": "2472",
    "Unique Entry ID": "omxkkikQ5jwtoGiXa"
  }],
  "Aloha K.K.": [{
    "Name": "Aloha K.K.",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Aqua",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Aloha",
    "Internal ID": "2423",
    "Unique Entry ID": "rxKK6nfmC4rWvXxCv"
  }],
  "Animal City": [{
    "Name": "Animal City",
    "Buy": "NFS",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "None",
    "Size": "1x1",
    "Source": "K.K. concert",
    "Source Notes": "Hidden song - only by request",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_DoubutuNoMachi",
    "Internal ID": "4312",
    "Unique Entry ID": "PTLK2jL5rb7t5Rm5j"
  }],
  "Bubblegum K.K.": [{
    "Name": "Bubblegum K.K.",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Aqua",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Idol",
    "Internal ID": "2492",
    "Unique Entry ID": "ZgwCoTem6x9efZAnD"
  }],
  "CafÃ© K.K.": [{
    "Name": "CafÃ© K.K.",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Colorful",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Paris",
    "Internal ID": "2454",
    "Unique Entry ID": "ZXwXi8YnFpks2RPuK"
  }],
  "Comrade K.K.": [{
    "Name": "Comrade K.K.",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "White",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_ShowaKayo",
    "Internal ID": "2448",
    "Unique Entry ID": "5ufeoTSFwRxQTrXdq"
  }],
  "DJ K.K.": [{
    "Name": "DJ K.K.",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Pink",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_EuroBeat",
    "Internal ID": "2443",
    "Unique Entry ID": "6H8pzhuYdfNpD8KTd"
  }],
  "Drivin'": [{
    "Name": "Drivin'",
    "Buy": "NFS",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "None",
    "Size": "1x1",
    "Source": "K.K. concert",
    "Source Notes": "Hidden song - only by request",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Drive",
    "Internal ID": "4314",
    "Unique Entry ID": "at7FbmJfbKvsGHB5T"
  }],
  "Farewell": [{
    "Name": "Farewell",
    "Buy": "NFS",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "None",
    "Size": "1x1",
    "Source": "K.K. concert",
    "Source Notes": "Hidden song - only by request",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Sayonara",
    "Internal ID": "4313",
    "Unique Entry ID": "diprrz97SbCJGzXM3"
  }],
  "Forest Life": [{
    "Name": "Forest Life",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_MoriNoSeikatsu",
    "Internal ID": "2461",
    "Unique Entry ID": "ZM4S88gPPapGknNeR"
  }],
  "Go K.K. Rider": [{
    "Name": "Go K.K. Rider",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "White",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_KekeRider",
    "Internal ID": "2450",
    "Unique Entry ID": "w6jLsBX6ZX4oPDwDh"
  }],
  "Hypno K.K.": [{
    "Name": "Hypno K.K.",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "White",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_UtataneNoYume",
    "Internal ID": "2480",
    "Unique Entry ID": "qwHrcscJZNxD5mn8k"
  }],
  "I Love You": [{
    "Name": "I Love You",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Colorful",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Daisuki",
    "Internal ID": "2458",
    "Unique Entry ID": "cic3w9hqeY222ni2z"
  }],
  "Imperial K.K.": [{
    "Name": "Imperial K.K.",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Pink",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_China",
    "Internal ID": "2427",
    "Unique Entry ID": "6y3ftdfGBa3oYAfrA"
  }],
  "K.K. Adventure": [{
    "Name": "K.K. Adventure",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Orange",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Hollywood",
    "Internal ID": "2484",
    "Unique Entry ID": "6FWZByesWNcjXBPQX"
  }],
  "K.K. Aria": [{
    "Name": "K.K. Aria",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Blue",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Maria",
    "Internal ID": "2413",
    "Unique Entry ID": "9ZSqWa7JjfMhwPWEE"
  }],
  "K.K. Ballad": [{
    "Name": "K.K. Ballad",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Black",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Ballad",
    "Internal ID": "2447",
    "Unique Entry ID": "awbEqrBQ52aCi4YKj"
  }],
  "K.K. Bazaar": [{
    "Name": "K.K. Bazaar",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Black",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Roma",
    "Internal ID": "2486",
    "Unique Entry ID": "yJdhdZPjGQSs4xL7a"
  }],
  "K.K. Birthday": [{
    "Name": "K.K. Birthday",
    "Buy": "NFS",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Aqua",
    "Size": "1x1",
    "Source": "K.K. concert",
    "Source Notes": "Received on your first time seeing K.K. perform during your birthday",
    "Season/Event": "Birthday",
    "Season/Event Exclusive": "Yes",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_BirthdaySong",
    "Internal ID": "2495",
    "Unique Entry ID": "xrFkTdiZ9fHkYMvDr"
  }],
  "K.K. Blues": [{
    "Name": "K.K. Blues",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "White",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Blues",
    "Internal ID": "2436",
    "Unique Entry ID": "HtTcKk7AdJLrmwXXK"
  }],
  "K.K. Bossa": [{
    "Name": "K.K. Bossa",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "White",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Bossa",
    "Internal ID": "2415",
    "Unique Entry ID": "Bu3tGw6JnhnMEabz2"
  }],
  "K.K. Calypso": [{
    "Name": "K.K. Calypso",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "White",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Caripso",
    "Internal ID": "2416",
    "Unique Entry ID": "g7TbqwnzRw64kcmso"
  }],
  "K.K. Casbah": [{
    "Name": "K.K. Casbah",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Beige",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Turkey",
    "Internal ID": "2428",
    "Unique Entry ID": "CuWyihNkLbL5rwbYZ"
  }],
  "K.K. Chorale": [{
    "Name": "K.K. Chorale",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Beige",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Sanbika",
    "Internal ID": "2405",
    "Unique Entry ID": "rijxxXt45dqkXze5A"
  }],
  "K.K. Condor": [{
    "Name": "K.K. Condor",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Beige",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Peru",
    "Internal ID": "2425",
    "Unique Entry ID": "EoALBg9oEc9NmJpaf"
  }],
  "K.K. Country": [{
    "Name": "K.K. Country",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Black",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Country",
    "Internal ID": "2445",
    "Unique Entry ID": "rN2cyPLzaZaMGmrwj"
  }],
  "K.K. Cruisin'": [{
    "Name": "K.K. Cruisin'",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Black",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Urban",
    "Internal ID": "2439",
    "Unique Entry ID": "hPBjqhB66YBw6Tz4n"
  }],
  "K.K. D&B": [{
    "Name": "K.K. D&B",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Colorful",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Drumnbass",
    "Internal ID": "2441",
    "Unique Entry ID": "rkBHJtfrcabbt57bD"
  }],
  "K.K. Dirge": [{
    "Name": "K.K. Dirge",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Black",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_KowaiUta",
    "Internal ID": "2451",
    "Unique Entry ID": "2DDYNvo8uNo5zNPo8"
  }],
  "K.K. Disco": [{
    "Name": "K.K. Disco",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Colorful",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Disco",
    "Internal ID": "2494",
    "Unique Entry ID": "tAZn6EXuFip47sbbo"
  }],
  "K.K. Dixie": [{
    "Name": "K.K. Dixie",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Colorful",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Dixie",
    "Internal ID": "2464",
    "Unique Entry ID": "bCL6Df8hoG7kooXcL"
  }],
  "K.K. Ã‰tude": [{
    "Name": "K.K. Ã‰tude",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Black",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Etude",
    "Internal ID": "2411",
    "Unique Entry ID": "PgDmhWq5W4ciF6TW5"
  }],
  "K.K. Faire": [{
    "Name": "K.K. Faire",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Orange",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Haisai",
    "Internal ID": "2422",
    "Unique Entry ID": "3i2RNpZeHPhxq6bPY"
  }],
  "K.K. Flamenco": [{
    "Name": "K.K. Flamenco",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Red",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Flamenco",
    "Internal ID": "2490",
    "Unique Entry ID": "KXRPPacevShYgCh33"
  }],
  "K.K. Folk": [{
    "Name": "K.K. Folk",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Colorful",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Minyo",
    "Internal ID": "2430",
    "Unique Entry ID": "L9SqkeaoQNXGphs6H"
  }],
  "K.K. Fusion": [{
    "Name": "K.K. Fusion",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Colorful",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Fusion",
    "Internal ID": "2410",
    "Unique Entry ID": "Lx9Kk9gmmori3huxC"
  }],
  "K.K. Groove": [{
    "Name": "K.K. Groove",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Blue",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Raregroove",
    "Internal ID": "2488",
    "Unique Entry ID": "7ss8K3czErhJNQiXJ"
  }],
  "K.K. Gumbo": [{
    "Name": "K.K. Gumbo",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Beige",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_NewOrleans",
    "Internal ID": "2434",
    "Unique Entry ID": "nPNjtqN3AJdfxLuAx"
  }],
  "K.K. House": [{
    "Name": "K.K. House",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Pink",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_House",
    "Internal ID": "2478",
    "Unique Entry ID": "DoMmMBQBeXm7sTGPm"
  }],
  "K.K. Island": [{
    "Name": "K.K. Island",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Aqua",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_DoubutsuNoShima",
    "Internal ID": "2482",
    "Unique Entry ID": "LrdjwBdn7hS2NXeW2"
  }],
  "K.K. Jazz": [{
    "Name": "K.K. Jazz",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Aqua",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Jazz",
    "Internal ID": "2409",
    "Unique Entry ID": "eRNA3ktNpPi8qB5Yx"
  }],
  "K.K. Jongara": [{
    "Name": "K.K. Jongara",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Aqua",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Jongara",
    "Internal ID": "2489",
    "Unique Entry ID": "2tqAXsz3eiAFcZ5aS"
  }],
  "K.K. Lament": [{
    "Name": "K.K. Lament",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Gray",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Enka",
    "Internal ID": "2449",
    "Unique Entry ID": "LLDo3zTdcLf3JRexf"
  }],
  "K.K. Love Song": [{
    "Name": "K.K. Love Song",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "White",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_LoveSong",
    "Internal ID": "2440",
    "Unique Entry ID": "Zi4kijYWbE3taJy67"
  }],
  "K.K. Lullaby": [{
    "Name": "K.K. Lullaby",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Green",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Lullaby",
    "Internal ID": "2412",
    "Unique Entry ID": "WpCHmL6DBXK7RWQNJ"
  }],
  "K.K. Mambo": [{
    "Name": "K.K. Mambo",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Red",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Mambo",
    "Internal ID": "2418",
    "Unique Entry ID": "LftoxEHoft5xpn8ZK"
  }],
  "K.K. Marathon": [{
    "Name": "K.K. Marathon",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Colorful",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Gamelan",
    "Internal ID": "2465",
    "Unique Entry ID": "EAeRF5hCvgZvpf24R"
  }],
  "K.K. March": [{
    "Name": "K.K. March",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Pink",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_March",
    "Internal ID": "2406",
    "Unique Entry ID": "ZYeSh5EHDgX9bEY4L"
  }],
  "K.K. Mariachi": [{
    "Name": "K.K. Mariachi",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Orange",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Senor",
    "Internal ID": "2456",
    "Unique Entry ID": "yK4cu9gRJDzAchPip"
  }],
  "K.K. Metal": [{
    "Name": "K.K. Metal",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Purple",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Metal",
    "Internal ID": "2474",
    "Unique Entry ID": "TNdpcZiy6ZXb2sie3"
  }],
  "K.K. Milonga": [{
    "Name": "K.K. Milonga",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Red",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Milonga",
    "Internal ID": "2487",
    "Unique Entry ID": "bphgD53QrTdSQWrsw"
  }],
  "K.K. Moody": [{
    "Name": "K.K. Moody",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Orange",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Bolero",
    "Internal ID": "2491",
    "Unique Entry ID": "D3WoTWs7t3uojthok"
  }],
  "K.K. Oasis": [{
    "Name": "K.K. Oasis",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Colorful",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Maharaja",
    "Internal ID": "2485",
    "Unique Entry ID": "X45bf37FawXymbRTR"
  }],
  "K.K. Parade": [{
    "Name": "K.K. Parade",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Colorful",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Parade",
    "Internal ID": "2455",
    "Unique Entry ID": "vaxtch9tWPZTeJKBf"
  }],
  "K.K. Ragtime": [{
    "Name": "K.K. Ragtime",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Gray",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_RagTime",
    "Internal ID": "2433",
    "Unique Entry ID": "Rz7khNvFcekonfDC8"
  }],
  "K.K. Rally": [{
    "Name": "K.K. Rally",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Red",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Ondo",
    "Internal ID": "2473",
    "Unique Entry ID": "qPCRJqX3uM66bDrDb"
  }],
  "K.K. Reggae": [{
    "Name": "K.K. Reggae",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Colorful",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Reggae",
    "Internal ID": "2419",
    "Unique Entry ID": "BeXTGzse56iMWrovn"
  }],
  "K.K. Rock": [{
    "Name": "K.K. Rock",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Black",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Rock",
    "Internal ID": "2431",
    "Unique Entry ID": "dGWQ49YGhQ6uxxdth"
  }],
  "K.K. Rockabilly": [{
    "Name": "K.K. Rockabilly",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Aqua",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_KekeBilly",
    "Internal ID": "2471",
    "Unique Entry ID": "DogQSJB5472T5PTgX"
  }],
  "K.K. Safari": [{
    "Name": "K.K. Safari",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Orange",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Afro",
    "Internal ID": "2429",
    "Unique Entry ID": "YxQuKist5jbDN6YeX"
  }],
  "K.K. Salsa": [{
    "Name": "K.K. Salsa",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Red",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Salsa",
    "Internal ID": "2417",
    "Unique Entry ID": "hMAkxLymhpg5Zt6Xm"
  }],
  "K.K. Samba": [{
    "Name": "K.K. Samba",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Aqua",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Samba",
    "Internal ID": "2414",
    "Unique Entry ID": "XYFSnTG8QFbGXZJ79"
  }],
  "K.K. Ska": [{
    "Name": "K.K. Ska",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Black",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Ska",
    "Internal ID": "2420",
    "Unique Entry ID": "TMiRa4nHYSbtCx4Em"
  }],
  "K.K. Sonata": [{
    "Name": "K.K. Sonata",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "White",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Sonata",
    "Internal ID": "2479",
    "Unique Entry ID": "zxHYzEN2Q7gt5JYMm"
  }],
  "K.K. Song": [{
    "Name": "K.K. Song",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Colorful",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_KekeSong",
    "Internal ID": "2457",
    "Unique Entry ID": "xjLPmvzuXaBSZx4Fy"
  }],
  "K.K. Soul": [{
    "Name": "K.K. Soul",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Black",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Soul",
    "Internal ID": "2438",
    "Unique Entry ID": "mXvujh5YZscWL5pKg"
  }],
  "K.K. Steppe": [{
    "Name": "K.K. Steppe",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Colorful",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Cossack",
    "Internal ID": "2426",
    "Unique Entry ID": "mGhDWyj7f83gryu4g"
  }],
  "K.K. Stroll": [{
    "Name": "K.K. Stroll",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "White",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Osanpo",
    "Internal ID": "2481",
    "Unique Entry ID": "QmR5zsjrqjsYdDcYy"
  }],
  "K.K. Swing": [{
    "Name": "K.K. Swing",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Beige",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Swing",
    "Internal ID": "2408",
    "Unique Entry ID": "BxCLYKFj8yeJMqxwD"
  }],
  "K.K. Synth": [{
    "Name": "K.K. Synth",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "White",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Electronica",
    "Internal ID": "2493",
    "Unique Entry ID": "S7sa9ugfRSHNPr9zX"
  }],
  "K.K. Tango": [{
    "Name": "K.K. Tango",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Black",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Tango",
    "Internal ID": "2421",
    "Unique Entry ID": "9gwFYo6HKxqfxnimX"
  }],
  "K.K. Technopop": [{
    "Name": "K.K. Technopop",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Black",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_TechnoBeat",
    "Internal ID": "2442",
    "Unique Entry ID": "opZrX852viqZH7RJX"
  }],
  "K.K. Waltz": [{
    "Name": "K.K. Waltz",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Red",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Waltz",
    "Internal ID": "2407",
    "Unique Entry ID": "pYKWYuRTejcTphjzd"
  }],
  "K.K. Western": [{
    "Name": "K.K. Western",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Gray",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Western",
    "Internal ID": "2452",
    "Unique Entry ID": "AnjsMygxJozFjZCGC"
  }],
  "King K.K.": [{
    "Name": "King K.K.",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Yellow",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Daimyo",
    "Internal ID": "2466",
    "Unique Entry ID": "B6siK6dLxCJACfGZY"
  }],
  "Lucky K.K.": [{
    "Name": "Lucky K.K.",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "White",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Irish",
    "Internal ID": "2424",
    "Unique Entry ID": "jCGA9eAgRjkLuNf2q"
  }],
  "Marine Song 2001": [{
    "Name": "Marine Song 2001",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Aqua",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_HunaUta2001",
    "Internal ID": "2468",
    "Unique Entry ID": "F8BvgZMycRgAjJv2A"
  }],
  "Mountain Song": [{
    "Name": "Mountain Song",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Aqua",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Alpine",
    "Internal ID": "2467",
    "Unique Entry ID": "5gDvnQ4uLnLwL85MK"
  }],
  "Mr. K.K.": [{
    "Name": "Mr. K.K.",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Beige",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Sensei",
    "Internal ID": "2453",
    "Unique Entry ID": "tGCobmkpe7AKsPmyn"
  }],
  "My Place": [{
    "Name": "My Place",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Green",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_BokuNoBasho",
    "Internal ID": "2460",
    "Unique Entry ID": "gQvdSw38P4QZwpkCh"
  }],
  "Neapolitan": [{
    "Name": "Neapolitan",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Black",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Napolitan",
    "Internal ID": "2469",
    "Unique Entry ID": "GDhwzHPsaEws6ciix"
  }],
  "Only Me": [{
    "Name": "Only Me",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Gray",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_OnlyMe",
    "Internal ID": "2444",
    "Unique Entry ID": "wwhnr7dEdx36E8SRv"
  }],
  "Pondering": [{
    "Name": "Pondering",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Black",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_KangaeChu",
    "Internal ID": "2463",
    "Unique Entry ID": "Gkk2Ck8DK627tiZkS"
  }],
  "Rockin' K.K.": [{
    "Name": "Rockin' K.K.",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Black",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_RocknRoll",
    "Internal ID": "2432",
    "Unique Entry ID": "asXTn3mfi7tzowcuj"
  }],
  "Soulful K.K.": [{
    "Name": "Soulful K.K.",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Orange",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Gospel",
    "Internal ID": "2437",
    "Unique Entry ID": "g2F79ptmGzFrrFf55"
  }],
  "Space K.K.": [{
    "Name": "Space K.K.",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "White",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Minimal",
    "Internal ID": "2483",
    "Unique Entry ID": "WbnqF3FqDQYJwfXed"
  }],
  "Spring Blossoms": [{
    "Name": "Spring Blossoms",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Pink",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'I feel good!' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_HaruNoKomorebi",
    "Internal ID": "2476",
    "Unique Entry ID": "q4ZmbxwwgjaNzvR4e"
  }],
  "Stale Cupcakes": [{
    "Name": "Stale Cupcakes",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Blue",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_BlueOnigiri",
    "Internal ID": "2475",
    "Unique Entry ID": "wh9i62k97gw3B34ER"
  }],
  "Steep Hill": [{
    "Name": "Steep Hill",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Orange",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_NiDanZaka",
    "Internal ID": "2470",
    "Unique Entry ID": "v3WHjrpgdgeZ3jaFC"
  }],
  "Surfin' K.K.": [{
    "Name": "Surfin' K.K.",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Blue",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little grumpy...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Eleki",
    "Internal ID": "2446",
    "Unique Entry ID": "HEX474yLBRZ5xY5Pv"
  }],
  "The K. Funk": [{
    "Name": "The K. Funk",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Orange",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Funk",
    "Internal ID": "2435",
    "Unique Entry ID": "8ciaF2Yxuhc5Jqpar"
  }],
  "To the Edge": [{
    "Name": "To the Edge",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "White",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'It's hard to say.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_NamiNami",
    "Internal ID": "2462",
    "Unique Entry ID": "P5ABGwMHvnYiFHcQN"
  }],
  "Two Days Ago": [{
    "Name": "Two Days Ago",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Black",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'A little blue...' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Ototoi",
    "Internal ID": "2459",
    "Unique Entry ID": "AzAHbHLA9oY2ihxrq"
  }],
  "Wandering": [{
    "Name": "Wandering",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "Gray",
    "Size": "1x1",
    "Source": "K.K. concert; Nook Shopping Daily Selection",
    "Source Notes": "Possible song K.K. will play when choosing 'Laid-back.' as your mood",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "For sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Horo",
    "Internal ID": "2477",
    "Unique Entry ID": "eDgjD4iS8sHZ64k3k"
  }],
  "Welcome Horizons": [{
    "Name": "Welcome Horizons",
    "Buy": "NFS",
    "Sell": "800",
    "HHA Base Points": "103",
    "Color 1": "Brown",
    "Color 2": "None",
    "Size": "1x1",
    "Source": "K.K. concert",
    "Source Notes": "Received on your first time seeing K.K. perform",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "Not for sale",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_MainTheme",
    "Internal ID": "4318",
    "Unique Entry ID": "eBR8TwgdbAKWEQc3T"
  }],
  "Hazure01": [{
    "Name": "Hazure01",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "0",
    "Color 1": "None",
    "Color 2": "None",
    "Size": "1x1",
    "Source": "K.K. concert",
    "Source Notes": "Played by K.K. if you request something he doesn't have (does not give take-home track)",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "Not in catalog",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Miss1",
    "Internal ID": "4315",
    "Unique Entry ID": "yzpTLMjxFrMMyPe9t"
  }],
  "Hazure02": [{
    "Name": "Hazure02",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "0",
    "Color 1": "None",
    "Color 2": "None",
    "Size": "1x1",
    "Source": "K.K. concert",
    "Source Notes": "Played by K.K. if you request something he doesn't have (does not give take-home track)",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "Not in catalog",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Miss2",
    "Internal ID": "4316",
    "Unique Entry ID": "oeZ6a9qJA54fyuwA3"
  }],
  "Hazure03": [{
    "Name": "Hazure03",
    "Buy": "3200",
    "Sell": "800",
    "HHA Base Points": "0",
    "Color 1": "None",
    "Color 2": "None",
    "Size": "1x2",
    "Source": "K.K. concert",
    "Source Notes": "Played by K.K. if you request something he doesn't have (does not give take-home track)",
    "Season/Event": "NA",
    "Season/Event Exclusive": "NA",
    "Catalog": "Not in catalog",
    "Version Added": "1.0.0",
    "Unlocked?": "Yes",
    "Filename": "mjk_Miss3",
    "Internal ID": "4317",
    "Unique Entry ID": "cXrvAEgQstHcnP5Zf"
  }]
}
export default music;