const reactions = [
	{
		"#": "40",
		"Name": "Aggravation",
		"Source": "Peppy villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Outraged",
		"Internal ID": "25",
		"Unique Entry ID": "6suhKYAAhh5QMKt64"
	},
	{
		"#": "2",
		"Name": "Agreement",
		"Source": "Cranky villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Nodding",
		"Internal ID": "39",
		"Unique Entry ID": "7smqwK9J7eFBxta28"
	},
	{
		"#": "20",
		"Name": "Amazed",
		"Source": "Snooty villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Shocked",
		"Internal ID": "33",
		"Unique Entry ID": "vosig4bbr4kPq57AT"
	},
	{
		"#": "16",
		"Name": "Apologetic",
		"Source": "Big Sister villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Apologize",
		"Internal ID": "126",
		"Unique Entry ID": "jBKsQYCAd7PtymQeB"
	},
	{
		"#": "24",
		"Name": "Bashfulness",
		"Source": "Lazy villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Blushing",
		"Internal ID": "44",
		"Unique Entry ID": "wzvKbFrEJCseTohoz"
	},
	{
		"#": "17",
		"Name": "Bewilderment",
		"Source": "Cranky villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Pardon",
		"Internal ID": "253",
		"Unique Entry ID": "WRSSRZMtM6rXfXBrR"
	},
	{
		"#": "41",
		"Name": "Cold Chill",
		"Source": "Big Sister villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "ColdChill",
		"Internal ID": "37",
		"Unique Entry ID": "K62u2owKFDLmPCB3Q"
	},
	{
		"#": "56",
		"Name": "Confetti",
		"Source": "Viva Festivale Reaction Set",
		"Season/Event": "Festivale (ready days); Festivale",
		"Season/Event Exclusive": "Yes",
		"Version Added": "1.7.0",
		"Icon Filename": "AddConfetti",
		"Internal ID": "848",
		"Unique Entry ID": "ZQwAqpKEDkTHTQXEn"
	},
	{
		"#": "10",
		"Name": "Confident",
		"Source": "Big Sister villagers",
		"Source Notes": "Requires a high level of friendship",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Assent",
		"Internal ID": "127",
		"Unique Entry ID": "TGifHTbyLBh4f3gDQ"
	},
	{
		"#": "18",
		"Name": "Curiosity",
		"Source": "Peppy villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "QuestionMark",
		"Internal ID": "41",
		"Unique Entry ID": "SskgipgnKzm5TsK7d"
	},
	{
		"#": "30",
		"Name": "Daydreaming",
		"Source": "Normal villagers",
		"Source Notes": "Requires a high level of friendship",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "AbsentMindedness",
		"Internal ID": "61",
		"Unique Entry ID": "JFrTBJCEaX5R4kABT"
	},
	{
		"#": "15",
		"Name": "Delight",
		"Source": "All villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Clapping",
		"Internal ID": "47",
		"Unique Entry ID": "F9DpGeqZzDeSTh2bq"
	},
	{
		"#": "3",
		"Name": "Disagreement",
		"Source": "Big Sister villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Negative",
		"Internal ID": "58",
		"Unique Entry ID": "Bw5YBM6iuWgMzutWq"
	},
	{
		"#": "42",
		"Name": "Distress",
		"Source": "Jock villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Frantic",
		"Internal ID": "31",
		"Unique Entry ID": "vsSjQBZXPeSK6uDTK"
	},
	{
		"#": "33",
		"Name": "Dozing",
		"Source": "Smug villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Sleep",
		"Internal ID": "63",
		"Unique Entry ID": "2vvgAacGjthcFW5Qa"
	},
	{
		"#": "14",
		"Name": "Encouraging",
		"Source": "Jock villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Cheering",
		"Internal ID": "49",
		"Unique Entry ID": "fomfML4NWdY8x6adv"
	},
	{
		"#": "54",
		"Name": "Excited",
		"Source": "Hip Reaction Collection",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.6.0",
		"Icon Filename": "AddExcited",
		"Internal ID": "813",
		"Unique Entry ID": "n7AxvQcyuPEtdD7uF"
	},
	{
		"#": "43",
		"Name": "Fearful",
		"Source": "Normal villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Shaking",
		"Internal ID": "38",
		"Unique Entry ID": "noKrWYCMSWcH4jwvi"
	},
	{
		"#": "59",
		"Name": "Feelin' It",
		"Source": "Viva Festivale Reaction Set",
		"Season/Event": "Festivale (ready days); Festivale",
		"Season/Event Exclusive": "Yes",
		"Version Added": "1.7.0",
		"Icon Filename": "AddDance",
		"Internal ID": "856",
		"Unique Entry ID": "r6wW7uebEBsLwP3XT"
	},
	{
		"#": "12",
		"Name": "Flourish",
		"Source": "Jock villagers",
		"Source Notes": "Requires a high level of friendship",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Dance",
		"Internal ID": "60",
		"Unique Entry ID": "5QDD3DcwdPhbGoJAf"
	},
	{
		"#": "7",
		"Name": "Glee",
		"Source": "Normal villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "HappyDance",
		"Internal ID": "23",
		"Unique Entry ID": "8nAwdhzZfotqpLC9R"
	},
	{
		"#": "1",
		"Name": "Greetings",
		"Source": "All villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Greeting",
		"Internal ID": "50",
		"Unique Entry ID": "oE6uqhZYjYfuqb55n"
	},
	{
		"#": "5",
		"Name": "Happiness",
		"Source": "Peppy villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Smiling",
		"Internal ID": "19",
		"Unique Entry ID": "TWENXBbBENgnFiGq3"
	},
	{
		"#": "45",
		"Name": "Haunt",
		"Source": "Jack",
		"Season/Event": "Halloween",
		"Season/Event Exclusive": "Yes",
		"Version Added": "1.5.0",
		"Icon Filename": "AddScaring",
		"Internal ID": "801",
		"Unique Entry ID": "fA3nXJsXHNT67zyT2"
	},
	{
		"#": "37",
		"Name": "Heartbreak",
		"Source": "Smug villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "BrokenHeart",
		"Internal ID": "42",
		"Unique Entry ID": "ex6gKZu6zsyd6MgDr"
	},
	{
		"#": "53",
		"Name": "Here You Go",
		"Source": "Hip Reaction Collection",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.6.0",
		"Icon Filename": "AddHereYouGo",
		"Internal ID": "816",
		"Unique Entry ID": "7mskmgbcDnZMfaa8d"
	},
	{
		"#": "21",
		"Name": "Inspiration",
		"Source": "Cranky villagers",
		"Source Notes": "Requires a high level of friendship",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "IdeaBulb",
		"Internal ID": "40",
		"Unique Entry ID": "8ux4ddfibJQR2EuWW"
	},
	{
		"#": "39",
		"Name": "Intense",
		"Source": "Snooty villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Silent",
		"Internal ID": "119",
		"Unique Entry ID": "X2kzqTaPwtG6SGNT8"
	},
	{
		"#": "6",
		"Name": "Joy",
		"Source": "All villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "HappyFlower",
		"Internal ID": "21",
		"Unique Entry ID": "fSNyHJHgLKac5mSLT"
	},
	{
		"#": "8",
		"Name": "Laughter",
		"Source": "Big Sister villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Laughing",
		"Internal ID": "20",
		"Unique Entry ID": "EBenMHMpwnkMgS6eg"
	},
	{
		"#": "58",
		"Name": "Let's Go",
		"Source": "Viva Festivale Reaction Set",
		"Season/Event": "Festivale (ready days); Festivale",
		"Season/Event Exclusive": "Yes",
		"Version Added": "1.7.0",
		"Icon Filename": "AddEntice",
		"Internal ID": "855",
		"Unique Entry ID": "mcdAptLF325uqyDKa"
	},
	{
		"#": "9",
		"Name": "Love",
		"Source": "Snooty villagers",
		"Source Notes": "Requires a high level of friendship",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Love",
		"Internal ID": "22",
		"Unique Entry ID": "GvAsErCFuGAcMAeXM"
	},
	{
		"#": "28",
		"Name": "Mischief",
		"Source": "Peppy villagers",
		"Source Notes": "Requires a high level of friendship",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Scheming",
		"Internal ID": "46",
		"Unique Entry ID": "E7it7yLfFaddFvEhQ"
	},
	{
		"#": "23",
		"Name": "Mistaken",
		"Source": "Lazy villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Oops",
		"Internal ID": "59",
		"Unique Entry ID": "DPR7WWkmR36Bsf2LG"
	},
	{
		"#": "4",
		"Name": "Pleased",
		"Source": "Normal villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Hello",
		"Internal ID": "120",
		"Unique Entry ID": "Z3MuKfQMaH3D8vkPA"
	},
	{
		"#": "13",
		"Name": "Pride",
		"Source": "Lazy villagers",
		"Source Notes": "Requires a high level of friendship",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "SmugFace",
		"Internal ID": "51",
		"Unique Entry ID": "xKoQpdJMtocNFRckm"
	},
	{
		"#": "29",
		"Name": "Resignation",
		"Source": "Smug villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "OhGeez",
		"Internal ID": "45",
		"Unique Entry ID": "7YdF3ZMr95XP3FaoW"
	},
	{
		"#": "36",
		"Name": "Sadness",
		"Source": "Normal villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "SadSpiral",
		"Internal ID": "30",
		"Unique Entry ID": "Wo8q6KhPtL2CYwat4"
	},
	{
		"#": "46",
		"Name": "Scare",
		"Source": "All villagers",
		"Season/Event": "Halloween",
		"Season/Event Exclusive": "Yes",
		"Version Added": "1.5.0",
		"Icon Filename": "AddPrank",
		"Internal ID": "805",
		"Unique Entry ID": "sBW2mWEs7FW8mN8e5"
	},
	{
		"#": "26",
		"Name": "Sheepishness",
		"Source": "Cranky villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "WrySmile",
		"Internal ID": "54",
		"Unique Entry ID": "5cRnCPDJRdRpPJF8D"
	},
	{
		"#": "22",
		"Name": "Shocked",
		"Source": "Jock villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Surprised",
		"Internal ID": "36",
		"Unique Entry ID": "bn29da8SNdMYYyWAa"
	},
	{
		"#": "11",
		"Name": "Showmanship",
		"Source": "Smug villagers",
		"Source Notes": "Requires a high level of friendship",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Shaki",
		"Internal ID": "62",
		"Unique Entry ID": "Bj5iG7kc6tLND9bjn"
	},
	{
		"#": "25",
		"Name": "Shyness",
		"Source": "Lazy villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Hesitate",
		"Internal ID": "57",
		"Unique Entry ID": "9H7jt7AGKbh6mW4y8"
	},
	{
		"#": "35",
		"Name": "Sighing",
		"Source": "Snooty villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Sighing",
		"Internal ID": "28",
		"Unique Entry ID": "ntjLqg82EQNsgnzYA"
	},
	{
		"#": "47",
		"Name": "Sit Down",
		"Source": "Hip Reaction Collection",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.6.0",
		"Icon Filename": "AddSitDown",
		"Internal ID": "808",
		"Unique Entry ID": "vZLdKXLdnjvN4J5Je"
	},
	{
		"#": "32",
		"Name": "Sleepy",
		"Source": "Peppy villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Sleepy",
		"Internal ID": "43",
		"Unique Entry ID": "9e5BhxmqtMurNWqW4"
	},
	{
		"#": "27",
		"Name": "Smirking",
		"Source": "Smug villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Grin",
		"Internal ID": "53",
		"Unique Entry ID": "KDAWT9zDKpufEWgaW"
	},
	{
		"#": "44",
		"Name": "Sneezing",
		"Source": "Jock villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Sneezing",
		"Internal ID": "48",
		"Unique Entry ID": "F6Dkk4PGtjDMCgry3"
	},
	{
		"#": "50",
		"Name": "Sniff Sniff",
		"Source": "Hip Reaction Collection",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.6.0",
		"Icon Filename": "AddSmell",
		"Internal ID": "814",
		"Unique Entry ID": "M3JksnoqmWyo9otrd"
	},
	{
		"#": "38",
		"Name": "Sorrow",
		"Source": "Lazy villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Crying",
		"Internal ID": "32",
		"Unique Entry ID": "W8nngMS98uwpHHW4m"
	},
	{
		"#": "19",
		"Name": "Surprise",
		"Source": "All villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Aha",
		"Internal ID": "34",
		"Unique Entry ID": "7jmkZiSxrYT7MMm4P"
	},
	{
		"#": "55",
		"Name": "Ta-da",
		"Source": "Hip Reaction Collection",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.6.0",
		"Icon Filename": "AddPraise",
		"Internal ID": "817",
		"Unique Entry ID": "r5knh2R8vmx7J4pxR"
	},
	{
		"#": "49",
		"Name": "Take a Picture",
		"Source": "Hip Reaction Collection",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.6.0",
		"Icon Filename": "AddTakePictures",
		"Internal ID": "815",
		"Unique Entry ID": "77uFv5cZp43Rt3LaP"
	},
	{
		"#": "31",
		"Name": "Thought",
		"Source": "Snooty villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Thinking",
		"Internal ID": "29",
		"Unique Entry ID": "HEFCeCGtJ7Bkb5PXG"
	},
	{
		"#": "57",
		"Name": "Viva",
		"Source": "Viva Festivale Reaction Set",
		"Season/Event": "Festivale (ready days); Festivale",
		"Season/Event Exclusive": "Yes",
		"Version Added": "1.7.0",
		"Icon Filename": "AddViva",
		"Internal ID": "851",
		"Unique Entry ID": "awBmqTsqEP6vSyH3k"
	},
	{
		"#": "48",
		"Name": "Wave Goodbye",
		"Source": "Hip Reaction Collection",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.6.0",
		"Icon Filename": "AddWaveHands",
		"Internal ID": "809",
		"Unique Entry ID": "dbiQgwwQZxAQw54ur"
	},
	{
		"#": "51",
		"Name": "Work Out",
		"Source": "Hip Reaction Collection",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.6.0",
		"Icon Filename": "AddGymnastics",
		"Internal ID": "804",
		"Unique Entry ID": "oXMGkQsnaXyB2WLKp"
	},
	{
		"#": "34",
		"Name": "Worry",
		"Source": "Cranky villagers",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.0.0",
		"Icon Filename": "Worried",
		"Internal ID": "27",
		"Unique Entry ID": "TygKeKxvotLEzWqvY"
	},
	{
		"#": "52",
		"Name": "Yoga",
		"Source": "Hip Reaction Collection",
		"Season/Event": "NA",
		"Season/Event Exclusive": "NA",
		"Version Added": "1.6.0",
		"Icon Filename": "AddYoga",
		"Internal ID": "802",
		"Unique Entry ID": "yeh2FF6fzMn3BdAi6"
	}
]

export default reactions;