const seasonsAndEvents = {
  "young spring bamboo": {
    "group": [{
      "Name": "young spring bamboo",
      "Type": "Crafting season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "February 25 â€“ May 21",
      "Dates (Southern Hemisphere)": "August 25 â€“Â November 30",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "February 25 â€“ May 21",
      "Southern Hemisphere Dates": "August 25 â€“Â November 30",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "young spring bamboo",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "B4yFhfZgohc6mpGye"
    }],
    "type": "Seasons and Events"
  },
  "cherry-blossom petals": {
    "group": [{
      "Name": "cherry-blossom petals",
      "Type": "Crafting season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "April 1 â€“Â April 10",
      "Dates (Southern Hemisphere)": "October 1 â€“ October 10",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "April 1 â€“Â April 10",
      "Southern Hemisphere Dates": "October 1 â€“ October 10",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "cherry-blossom petals",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "Xo3c8z7JTrEth4NW7"
    }],
    "type": "Seasons and Events"
  },
  "summer shells": {
    "group": [{
      "Name": "summer shells",
      "Type": "Crafting season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "June 1 â€“Â August 31",
      "Dates (Southern Hemisphere)": "December 1 â€“Â February 29",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "June 1 â€“Â August 31",
      "Southern Hemisphere Dates": "December 1 â€“Â February 29",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "summer shells",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "sjovDaZqkh4jafozk"
    }],
    "type": "Seasons and Events"
  },
  "acorns and pine cones": {
    "group": [{
      "Name": "acorns and pine cones",
      "Type": "Crafting season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "September 1 â€“Â December 10",
      "Dates (Southern Hemisphere)": "March 1 â€“Â June 10",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "September 1 â€“Â December 10",
      "Southern Hemisphere Dates": "March 1 â€“Â June 10",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "acorns and pine cones",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "Rj8eWkGTM5STPvprt"
    }],
    "type": "Seasons and Events"
  },
  "mushrooms": {
    "group": [{
      "Name": "mushrooms",
      "Type": "Crafting season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "November 1 â€“ November 30",
      "Dates (Southern Hemisphere)": "May 1 â€“Â May 31",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "November 1 â€“ November 30",
      "Southern Hemisphere Dates": "May 1 â€“Â May 31",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "mushrooms",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "hAE9QzEyaKskMpTfw"
    }],
    "type": "Seasons and Events"
  },
  "maple leaves": {
    "group": [{
      "Name": "maple leaves",
      "Type": "Crafting season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "November 16 â€“ November 25",
      "Dates (Southern Hemisphere)": "May 16 â€“ May 25",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "November 16 â€“ November 25",
      "Southern Hemisphere Dates": "May 16 â€“ May 25",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "maple leaves",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "2pHZfthLCYjYxEGXJ"
    }],
    "type": "Seasons and Events"
  },
  "snowflakes": {
    "group": [{
      "Name": "snowflakes",
      "Type": "Crafting season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "December 11 â€“ February 24",
      "Dates (Southern Hemisphere)": "June 11 â€“Â August 24",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "December 11 â€“ February 24",
      "Southern Hemisphere Dates": "June 11 â€“Â August 24",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "snowflakes",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "owiAqbhvj8Ej62yer"
    }],
    "type": "Seasons and Events"
  },
  "ornaments": {
    "group": [{
      "Name": "ornaments",
      "Type": "Crafting season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "December 15 â€“Â January 6",
      "Dates (Southern Hemisphere)": "December 15 â€“Â January 6",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "December 15 â€“Â January 6",
      "Southern Hemisphere Dates": "December 15 â€“Â January 6",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "ornaments",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "hMjjfnZoboSEfX6kN"
    }],
    "type": "Seasons and Events"
  },
  "Aries": {
    "group": [{
      "Name": "Aries",
      "Type": "Zodiac season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "March 21 â€“Â April 19",
      "Dates (Southern Hemisphere)": "March 21 â€“Â April 19",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "March 21 â€“Â April 19",
      "Southern Hemisphere Dates": "March 21 â€“Â April 19",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Aries",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "x8ieT7oBnYmXxDq7A"
    }],
    "type": "Seasons and Events"
  },
  "Taurus": {
    "group": [{
      "Name": "Taurus",
      "Type": "Zodiac season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "April 20 â€“Â May 20",
      "Dates (Southern Hemisphere)": "April 20 â€“Â May 20",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "April 20 â€“Â May 20",
      "Southern Hemisphere Dates": "April 20 â€“Â May 20",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Taurus",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "zhNANPmM76brtTv8z"
    }],
    "type": "Seasons and Events"
  },
  "Gemini": {
    "group": [{
      "Name": "Gemini",
      "Type": "Zodiac season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "May 21 â€“Â June 21",
      "Dates (Southern Hemisphere)": "May 21 â€“Â June 21",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "May 21 â€“Â June 21",
      "Southern Hemisphere Dates": "May 21 â€“Â June 21",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Gemini",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "vKNjJizgqpQfBgf5y"
    }],
    "type": "Seasons and Events"
  },
  "Cancer": {
    "group": [{
      "Name": "Cancer",
      "Type": "Zodiac season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "June 22 â€“Â July 22",
      "Dates (Southern Hemisphere)": "June 22 â€“Â July 22",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "June 22 â€“Â July 22",
      "Southern Hemisphere Dates": "June 22 â€“Â July 22",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Cancer",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "d7jo5yXDsHr7ZPSn7"
    }],
    "type": "Seasons and Events"
  },
  "Leo": {
    "group": [{
      "Name": "Leo",
      "Type": "Zodiac season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "July 23 â€“Â August 22",
      "Dates (Southern Hemisphere)": "July 23 â€“Â August 22",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "July 23 â€“Â August 22",
      "Southern Hemisphere Dates": "July 23 â€“Â August 22",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Leo",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "TKcZ9NSsgrFpDgsa8"
    }],
    "type": "Seasons and Events"
  },
  "Virgo": {
    "group": [{
      "Name": "Virgo",
      "Type": "Zodiac season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "August 23 â€“ September 22",
      "Dates (Southern Hemisphere)": "August 23 â€“ September 22",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "August 23 â€“ September 22",
      "Southern Hemisphere Dates": "August 23 â€“ September 22",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Virgo",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "s5pDRHdgiSvDQqHdL"
    }],
    "type": "Seasons and Events"
  },
  "Libra": {
    "group": [{
      "Name": "Libra",
      "Type": "Zodiac season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "September 23 â€“ October 23",
      "Dates (Southern Hemisphere)": "September 23 â€“ October 23",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "September 23 â€“ October 23",
      "Southern Hemisphere Dates": "September 23 â€“ October 23",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Libra",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "9XGhdA9uRd8wpFcnF"
    }],
    "type": "Seasons and Events"
  },
  "Scorpio": {
    "group": [{
      "Name": "Scorpio",
      "Type": "Zodiac season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "October 24 â€“Â November 22",
      "Dates (Southern Hemisphere)": "October 24 â€“Â November 22",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "October 24 â€“Â November 22",
      "Southern Hemisphere Dates": "October 24 â€“Â November 22",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Scorpio",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "596kyafmfDmHdW7ce"
    }],
    "type": "Seasons and Events"
  },
  "Sagittarius": {
    "group": [{
      "Name": "Sagittarius",
      "Type": "Zodiac season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "November 23 â€“Â December 21",
      "Dates (Southern Hemisphere)": "November 23 â€“Â December 21",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "November 23 â€“Â December 21",
      "Southern Hemisphere Dates": "November 23 â€“Â December 21",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Sagittarius",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "bTaE6agqsduPGZ9h3"
    }],
    "type": "Seasons and Events"
  },
  "Capricorn": {
    "group": [{
      "Name": "Capricorn",
      "Type": "Zodiac season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "December 22 â€“Â January 19",
      "Dates (Southern Hemisphere)": "December 22 â€“Â January 19",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "December 22 â€“Â January 19",
      "Southern Hemisphere Dates": "December 22 â€“Â January 19",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Capricorn",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "Hg5dLT2EZYv4AqRHS"
    }],
    "type": "Seasons and Events"
  },
  "Aquarius": {
    "group": [{
      "Name": "Aquarius",
      "Type": "Zodiac season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "January 20 â€“Â February 18",
      "Dates (Southern Hemisphere)": "January 20 â€“Â February 18",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "January 20 â€“Â February 18",
      "Southern Hemisphere Dates": "January 20 â€“Â February 18",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Aquarius",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "qhhHqPBRzJ7qLsocW"
    }],
    "type": "Seasons and Events"
  },
  "Pisces": {
    "group": [{
      "Name": "Pisces",
      "Type": "Zodiac season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "February 19 â€“Â March 20",
      "Dates (Southern Hemisphere)": "February 19 â€“Â March 20",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "February 19 â€“Â March 20",
      "Southern Hemisphere Dates": "February 19 â€“Â March 20",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Pisces",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "t3oLZbrWRDCqGFWff"
    }],
    "type": "Seasons and Events"
  },
  "Spring shopping": {
    "group": [{
      "Name": "Spring shopping",
      "Type": "Shopping season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "March 1 â€“Â May 31",
      "Dates (Southern Hemisphere)": "September 1 â€“ November 30",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "March 1 â€“Â May 31",
      "Southern Hemisphere Dates": "September 1 â€“ November 30",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Spring shopping",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "cgstqsmrRFsG3HRHm"
    }],
    "type": "Seasons and Events"
  },
  "Summer shopping": {
    "group": [{
      "Name": "Summer shopping",
      "Type": "Shopping season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "June 1 â€“Â August 31",
      "Dates (Southern Hemisphere)": "December 1 â€“ February 29",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "June 1 â€“Â August 31",
      "Southern Hemisphere Dates": "December 1 â€“ February 29",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Summer shopping",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "gdqi5z5jot9H4fsz9"
    }],
    "type": "Seasons and Events"
  },
  "Fall shopping": {
    "group": [{
      "Name": "Fall shopping",
      "Type": "Shopping season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "September 1 â€“ November 30",
      "Dates (Southern Hemisphere)": "March 1 â€“Â May 31",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "September 1 â€“ November 30",
      "Southern Hemisphere Dates": "March 1 â€“Â May 31",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Fall shopping",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "pmM4yBFvMXTXcooL5"
    }],
    "type": "Seasons and Events"
  },
  "Winter shopping": {
    "group": [{
      "Name": "Winter shopping",
      "Type": "Shopping season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "December 1 â€“ February 29",
      "Dates (Southern Hemisphere)": "June 1 â€“Â August 31",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "December 1 â€“ February 29",
      "Southern Hemisphere Dates": "June 1 â€“Â August 31",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Winter shopping",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "h5W3JH8kDC4xJHgva"
    }],
    "type": "Seasons and Events"
  },
  "Festive shopping": {
    "group": [{
      "Name": "Festive shopping",
      "Type": "Shopping season",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "December 1 â€“ December 25",
      "Dates (Southern Hemisphere)": "December 1 â€“ December 25",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "December 1 â€“ December 25",
      "Southern Hemisphere Dates": "December 1 â€“ December 25",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Festive shopping",
      "Internal Label": "NA",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "z3NNqZMg7eDZRK3JD"
    }],
    "type": "Seasons and Events"
  },
  "Birthday": {
    "group": [{
      "Name": "Birthday",
      "Type": "Basegame event",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "NA",
      "Dates (Southern Hemisphere)": "NA",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Birthday",
      "Internal Label": "PlayerBirthday",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "8gF25cNHcBJxveb5A"
    }],
    "type": "Seasons and Events"
  },
  "Fishing Tourney": {
    "group": [{
      "Name": "Fishing Tourney",
      "Type": "Basegame event",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "2nd Saturday of April; 2nd Saturday of July; 2nd Saturday of October; 2nd Saturday of January",
      "Dates (Southern Hemisphere)": "2nd Saturday of October; 2nd Saturday of January; 2nd Saturday of April; 2nd Saturday of July",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "2nd Saturday of April; 2nd Saturday of July; 2nd Saturday of October; 2nd Saturday of January",
      "Southern Hemisphere Dates": "2nd Saturday of October; 2nd Saturday of January; 2nd Saturday of April; 2nd Saturday of July",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Fishing Tourney",
      "Internal Label": "FishingConventionSpring; FishingConventionSummer; FishingConventionAutumn; FishingConventionWinter",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "FGE5KSaw2fEX9M7Er"
    }],
    "type": "Seasons and Events"
  },
  "Bug-Off": {
    "group": [{
      "Name": "Bug-Off",
      "Type": "Basegame event",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "4th Saturday of June; 4th Saturday of July; 4th Saturday of August; 4th Saturday of September",
      "Dates (Southern Hemisphere)": "3rd Saturday of November; 3rd Saturday of December; 3rd Saturday of January; 3rd Saturday of February",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "4th Saturday of June; 4th Saturday of July; 4th Saturday of August; 4th Saturday of September",
      "Southern Hemisphere Dates": "3rd Saturday of November; 3rd Saturday of December; 3rd Saturday of January; 3rd Saturday of February",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Bug-Off",
      "Internal Label": "InsectConvention1; InsectConvention2; InsectConvention3; InsectConvention4",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "ARcnvRvmH6ug2JBXi"
    }],
    "type": "Seasons and Events"
  },
  "Countdown": {
    "group": [{
      "Name": "Countdown",
      "Type": "Basegame event",
      "Version Added": "1.0.0",
      "Version Last Updated": "1.0.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "December 31",
      "Dates (Southern Hemisphere)": "December 31",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "December 31",
      "Southern Hemisphere Dates": "December 31",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Countdown",
      "Internal Label": "Countdown",
      "Unlock Date": "2020-03-20",
      "Unlock Method": "No",
      "Unique Entry ID": "ofQGGtcwwK7dm9tpW"
    }],
    "type": "Seasons and Events"
  },
  "Bunny Day (ready days)": {
    "group": [{
      "Name": "Bunny Day (ready days)",
      "Type": "Special event",
      "Version Added": "1.1.0",
      "Version Last Updated": "1.9.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "March 28 â€“Â April 3",
      "Dates (Southern Hemisphere)": "March 28 â€“Â April 3",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "March 28 â€“Â April 3",
      "Display Name": "Bunny Day",
      "Internal Label": "Easter",
      "Unlock Date": "2021-03-28",
      "Unlock Method": "BCAT (a)",
      "Unique Entry ID": "4ku2HWxsXtYsHZPnA"
    }],
    "type": "Seasons and Events"
  },
  "Bunny Day": {
    "group": [{
      "Name": "Bunny Day",
      "Type": "Special event",
      "Version Added": "1.1.0",
      "Version Last Updated": "1.9.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "April 4",
      "Dates (Southern Hemisphere)": "April 4",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "April 4",
      "Display Name": "Bunny Day",
      "Internal Label": "Easter",
      "Unlock Date": "2021-04-04",
      "Unlock Method": "BCAT (b)",
      "Unique Entry ID": "mN6SNYaRhEqushr8n"
    }],
    "type": "Seasons and Events"
  },
  "Nature Day": {
    "group": [{
      "Name": "Nature Day",
      "Type": "Special event",
      "Version Added": "1.2.0",
      "Version Last Updated": "1.9.0",
      "Year": "NA",
      "Dates (Northern Hemisphere)": "NA",
      "Dates (Southern Hemisphere)": "NA",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Nature Day",
      "Internal Label": "EarthDay",
      "Unlock Date": "2020-04-23",
      "Unlock Method": "No",
      "Unique Entry ID": "ej9oowKQuQmZs4sZY"
    }],
    "type": "Seasons and Events"
  },
  "May Day": {
    "group": [{
      "Name": "May Day",
      "Type": "Special event",
      "Version Added": "1.2.0",
      "Version Last Updated": "1.2.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "May 1 â€“ May 7",
      "Dates (Southern Hemisphere)": "May 1 â€“ May 7",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "May 1 â€“ May 7",
      "2021 Dates": "NA",
      "Display Name": "May Day",
      "Internal Label": "MayDay",
      "Unlock Date": "2020-05-01",
      "Unlock Method": "BCAT (a)",
      "Unique Entry ID": "cRAsXSu4L5HHoScER"
    }],
    "type": "Seasons and Events"
  },
  "International Museum Day": {
    "group": [{
      "Name": "International Museum Day",
      "Type": "Special event",
      "Version Added": "1.2.0",
      "Version Last Updated": "1.2.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "May 18 â€“ May 31",
      "Dates (Southern Hemisphere)": "May 18 â€“ May 31",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "May 18 â€“ May 31",
      "2021 Dates": "NA",
      "Display Name": "International Museum Day",
      "Internal Label": "InternationalMuseum",
      "Unlock Date": "2020-05-18",
      "Unlock Method": "BCAT (b)",
      "Unique Entry ID": "Dk8YdEvdKBNihCDFM"
    }],
    "type": "Seasons and Events"
  },
  "Wedding Season": {
    "group": [{
      "Name": "Wedding Season",
      "Type": "Special event",
      "Version Added": "1.2.0",
      "Version Last Updated": "1.2.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "June 1 â€“ June 30",
      "Dates (Southern Hemisphere)": "June 1 â€“ June 30",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "June 1 â€“ June 30",
      "2021 Dates": "NA",
      "Display Name": "Wedding Season",
      "Internal Label": "JuneBride",
      "Unlock Date": "2020-06-01",
      "Unlock Method": "BCAT (c)",
      "Unique Entry ID": "67TSSQDefBj5N8gp8"
    }],
    "type": "Seasons and Events"
  },
  "Mother's Day": {
    "group": [{
      "Name": "Mother's Day",
      "Type": "Nook Shopping event",
      "Version Added": "1.2.0",
      "Version Last Updated": "1.2.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "May 1 â€“Â May 31",
      "Dates (Southern Hemisphere)": "May 1 â€“Â May 31",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "May 1 â€“Â May 31",
      "2021 Dates": "NA",
      "Display Name": "Mother's Day",
      "Internal Label": "MothersDay",
      "Unlock Date": "2020-05-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "Hs623rDkgMAhnsjhy"
    }],
    "type": "Seasons and Events"
  },
  "International Children's Day": {
    "group": [{
      "Name": "International Children's Day",
      "Type": "Nook Shopping event",
      "Version Added": "1.2.0",
      "Version Last Updated": "1.2.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "June 1 â€“ June 30",
      "Dates (Southern Hemisphere)": "June 1 â€“ June 30",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "June 1 â€“ June 30",
      "2021 Dates": "NA",
      "Display Name": "International Children's Day",
      "Internal Label": "WorldChild",
      "Unlock Date": "2020-06-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "PSzeGZ8iagsS3juM8"
    }],
    "type": "Seasons and Events"
  },
  "Father's Day": {
    "group": [{
      "Name": "Father's Day",
      "Type": "Nook Shopping event",
      "Version Added": "1.2.0",
      "Version Last Updated": "1.2.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "June 1 â€“ June 30",
      "Dates (Southern Hemisphere)": "June 1 â€“ June 30",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "June 1 â€“ June 30",
      "2021 Dates": "NA",
      "Display Name": "Father's Day",
      "Internal Label": "FathersDay",
      "Unlock Date": "2020-06-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "DGpj63PS3qXFbSYBK"
    }],
    "type": "Seasons and Events"
  },
  "Summer Solstice (northern hemisphere)": {
    "group": [{
      "Name": "Summer Solstice (northern hemisphere)",
      "Type": "Nook Shopping event",
      "Version Added": "1.2.0",
      "Version Last Updated": "1.2.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "June 7 â€“Â July 6",
      "Dates (Southern Hemisphere)": "NA",
      "Availability": "Specific years (NH only)",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "June 7 â€“Â July 6",
      "2021 Dates": "NA",
      "Display Name": "Summer Solstice",
      "Internal Label": "SummerSolstice",
      "Unlock Date": "2020-06-07",
      "Unlock Method": "NTP",
      "Unique Entry ID": "vQbgAS6zTFgMZ2Ci4"
    }],
    "type": "Seasons and Events"
  },
  "Winter Solstice (southern hemisphere)": {
    "group": [{
      "Name": "Winter Solstice (southern hemisphere)",
      "Type": "Nook Shopping event",
      "Version Added": "1.2.0",
      "Version Last Updated": "1.2.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "NA",
      "Dates (Southern Hemisphere)": "June 7 â€“Â July 6",
      "Availability": "Specific years (SH only)",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "June 7 â€“Â July 6",
      "2021 Dates": "NA",
      "Display Name": "Winter Solstice",
      "Internal Label": "WinterSolstice",
      "Unlock Date": "2020-06-07",
      "Unlock Method": "NTP",
      "Unique Entry ID": "WTek3FANZJsBDDQrf"
    }],
    "type": "Seasons and Events"
  },
  "Tanabata": {
    "group": [{
      "Name": "Tanabata",
      "Type": "Nook Shopping event",
      "Version Added": "1.3.0",
      "Version Last Updated": "1.3.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "July 1 â€“ July 31",
      "Dates (Southern Hemisphere)": "July 1 â€“ July 31",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "July 1 â€“ July 31",
      "2021 Dates": "NA",
      "Display Name": "Tanabata",
      "Internal Label": "Tanabata",
      "Unlock Date": "2020-07-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "DRHv3aXj2usrWdsHQ"
    }],
    "type": "Seasons and Events"
  },
  "Fireworks Show": {
    "group": [{
      "Name": "Fireworks Show",
      "Type": "Special event",
      "Version Added": "1.4.0",
      "Version Last Updated": "1.4.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "August 2; August 9; August 16; August 23; August 30",
      "Dates (Southern Hemisphere)": "August 2; August 9; August 16; August 23; August 30",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "August 2; August 9; August 16; August 23; August 30",
      "2021 Dates": "NA",
      "Display Name": "Fireworks Show",
      "Internal Label": "Fireworks1; Fireworks2; Fireworks3; Fireworks4; Fireworks5",
      "Unlock Date": "2020-07-30",
      "Unlock Method": "No",
      "Unique Entry ID": "h6b7G8S5L36zMPLFg"
    }],
    "type": "Seasons and Events"
  },
  "Cowboy Festival": {
    "group": [{
      "Name": "Cowboy Festival",
      "Type": "Nook Shopping event",
      "Version Added": "1.4.0",
      "Version Last Updated": "1.4.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "August 1 â€“Â August 31",
      "Dates (Southern Hemisphere)": "August 1 â€“Â August 31",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "August 1 â€“Â August 31",
      "2021 Dates": "NA",
      "Display Name": "Cowboy Festival",
      "Internal Label": "CowBoyFestival",
      "Unlock Date": "2020-08-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "DRqqw3iMu6sranZ5Y"
    }],
    "type": "Seasons and Events"
  },
  "Cowherd & Weaver Girl Day": {
    "group": [{
      "Name": "Cowherd & Weaver Girl Day",
      "Type": "Nook Shopping event",
      "Version Added": "1.4.0",
      "Version Last Updated": "1.4.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "August 1 â€“Â August 31",
      "Dates (Southern Hemisphere)": "August 1 â€“Â August 31",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "August 1 â€“Â August 31",
      "2021 Dates": "NA",
      "Display Name": "Cowherd & Weaver Girl Day",
      "Internal Label": "GyurouSyokujyo",
      "Unlock Date": "2020-08-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "RpMgTwZcCL82njXnh"
    }],
    "type": "Seasons and Events"
  },
  "Grape Harvest Festival": {
    "group": [{
      "Name": "Grape Harvest Festival",
      "Type": "Nook Shopping event",
      "Version Added": "1.4.0",
      "Version Last Updated": "1.4.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "September 1 â€“ September 30",
      "Dates (Southern Hemisphere)": "September 1 â€“ September 30",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "September 1 â€“ September 30",
      "2021 Dates": "NA",
      "Display Name": "Grape Harvest Festival",
      "Internal Label": "GrapeHarvestFestival",
      "Unlock Date": "2020-09-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "e6vjhAiYsg9Jzua5t"
    }],
    "type": "Seasons and Events"
  },
  "Moon-Viewing Day": {
    "group": [{
      "Name": "Moon-Viewing Day",
      "Type": "Nook Shopping event",
      "Version Added": "1.4.0",
      "Version Last Updated": "1.4.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "September 7 â€“ October 8",
      "Dates (Southern Hemisphere)": "September 7 â€“ October 8",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "September 7 â€“ October 8",
      "2021 Dates": "NA",
      "Display Name": "Moon-Viewing Day",
      "Internal Label": "MidAutumnFestival",
      "Unlock Date": "2020-09-07",
      "Unlock Method": "NTP",
      "Unique Entry ID": "cs2qcLkD4RFZpJRDY"
    }],
    "type": "Seasons and Events"
  },
  "Halloween (ready days)": {
    "group": [{
      "Name": "Halloween (ready days)",
      "Type": "Special event",
      "Version Added": "1.5.0",
      "Version Last Updated": "1.5.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "October 1 â€“ October 30",
      "Dates (Southern Hemisphere)": "October 1 â€“ October 30",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "October 1 â€“ October 30",
      "2021 Dates": "NA",
      "Display Name": "Halloween",
      "Internal Label": "Halloween",
      "Unlock Date": "2020-09-30",
      "Unlock Method": "No",
      "Unique Entry ID": "CkhTdh8xBcjRPmCCM"
    }],
    "type": "Seasons and Events"
  },
  "Halloween": {
    "group": [{
      "Name": "Halloween",
      "Type": "Special event",
      "Version Added": "1.5.0",
      "Version Last Updated": "1.5.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "October 31",
      "Dates (Southern Hemisphere)": "October 31",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "October 31",
      "2021 Dates": "NA",
      "Display Name": "Halloween",
      "Internal Label": "Halloween",
      "Unlock Date": "2020-09-30",
      "Unlock Method": "No",
      "Unique Entry ID": "ZYoPaw7SennvjdMqj"
    }],
    "type": "Seasons and Events"
  },
  "Turkey Day": {
    "group": [{
      "Name": "Turkey Day",
      "Type": "Special event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "November 26",
      "Dates (Southern Hemisphere)": "November 26",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "November 26",
      "2021 Dates": "NA",
      "Display Name": "Turkey Day",
      "Internal Label": "HarvestFestival",
      "Unlock Date": "2020-11-26",
      "Unlock Method": "BCAT (a)",
      "Unique Entry ID": "n3cSGsDLnJJqLC76K"
    }],
    "type": "Seasons and Events"
  },
  "Turkey Day (shopping days)": {
    "group": [{
      "Name": "Turkey Day (shopping days)",
      "Type": "Special event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "November 27 â€“ November 30",
      "Dates (Southern Hemisphere)": "November 27 â€“ November 30",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "November 27 â€“ November 30",
      "2021 Dates": "NA",
      "Display Name": "Turkey Day",
      "Internal Label": "HarvestAfterTerm",
      "Unlock Date": "2020-11-26",
      "Unlock Method": "BCAT (a)",
      "Unique Entry ID": "LWQHvmgWcWpx6EBfn"
    }],
    "type": "Seasons and Events"
  },
  "Toy Day (ready days phase 1)": {
    "group": [{
      "Name": "Toy Day (ready days phase 1)",
      "Type": "Special event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "December 1 â€“ December 14",
      "Dates (Southern Hemisphere)": "December 1 â€“ December 14",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "December 1 â€“ December 14",
      "2021 Dates": "NA",
      "Display Name": "Toy Day",
      "Internal Label": "XmasReady1",
      "Unlock Date": "2020-12-01",
      "Unlock Method": "BCAT (b)",
      "Unique Entry ID": "WwqGv6zGXSbpdW7B2"
    }],
    "type": "Seasons and Events"
  },
  "Toy Day (ready days phase 2)": {
    "group": [{
      "Name": "Toy Day (ready days phase 2)",
      "Type": "Special event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "December 15 â€“Â December 23",
      "Dates (Southern Hemisphere)": "December 15 â€“Â December 23",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "December 15 â€“Â December 23",
      "2021 Dates": "NA",
      "Display Name": "Toy Day",
      "Internal Label": "XmasReady2",
      "Unlock Date": "2020-12-01",
      "Unlock Method": "BCAT (b)",
      "Unique Entry ID": "4b2C4HeZzZhtbjYo3"
    }],
    "type": "Seasons and Events"
  },
  "Toy Day": {
    "group": [{
      "Name": "Toy Day",
      "Type": "Special event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "December 24",
      "Dates (Southern Hemisphere)": "December 24",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "December 24",
      "2021 Dates": "NA",
      "Display Name": "Toy Day",
      "Internal Label": "XmasEve",
      "Unlock Date": "2020-12-24",
      "Unlock Method": "BCAT (c)",
      "Unique Entry ID": "8BTw75h6CYtPousz7"
    }],
    "type": "Seasons and Events"
  },
  "Toy Day (day after)": {
    "group": [{
      "Name": "Toy Day (day after)",
      "Type": "Special event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "December 25",
      "Dates (Southern Hemisphere)": "December 25",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "December 25",
      "2021 Dates": "NA",
      "Display Name": "Toy Day",
      "Internal Label": "XmasAfter",
      "Unlock Date": "2020-12-24",
      "Unlock Method": "BCAT (c)",
      "Unique Entry ID": "WRJS7x258JZXcBhiD"
    }],
    "type": "Seasons and Events"
  },
  "Winter Solstice (northern hemisphere)": {
    "group": [{
      "Name": "Winter Solstice (northern hemisphere)",
      "Type": "Nook Shopping event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "December 1 â€“ December 31",
      "Dates (Southern Hemisphere)": "NA",
      "Availability": "Specific years (NH only)",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "December 1 â€“ December 31",
      "2021 Dates": "NA",
      "Display Name": "Winter Solstice",
      "Internal Label": "Midwinter",
      "Unlock Date": "2020-12-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "fdqSGfgLZy6xzrL49"
    }],
    "type": "Seasons and Events"
  },
  "Summer Solstice (southern hemisphere)": {
    "group": [{
      "Name": "Summer Solstice (southern hemisphere)",
      "Type": "Nook Shopping event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "NA",
      "Dates (Southern Hemisphere)": "December 1 â€“ December 31",
      "Availability": "Specific years (SH only)",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "December 1 â€“ December 31",
      "2021 Dates": "NA",
      "Display Name": "Summer Solstice",
      "Internal Label": "SouthernMidwinter",
      "Unlock Date": "2020-12-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "sQSJrS3vHKbtpNL2L"
    }],
    "type": "Seasons and Events"
  },
  "ÅŒmisoka": {
    "group": [{
      "Name": "ÅŒmisoka",
      "Type": "Nook Shopping event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "December 26 â€“ December 31",
      "Dates (Southern Hemisphere)": "December 26 â€“ December 31",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "December 26 â€“ December 31",
      "2021 Dates": "NA",
      "Display Name": "New Year's Eve",
      "Internal Label": "Oomisoka",
      "Unlock Date": "2020-12-26",
      "Unlock Method": "NTP",
      "Unique Entry ID": "8rWzJhnPupkFxeeE5"
    }],
    "type": "Seasons and Events"
  },
  "Silvester": {
    "group": [{
      "Name": "Silvester",
      "Type": "Nook Shopping event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "December 26 â€“ December 31",
      "Dates (Southern Hemisphere)": "December 26 â€“ December 31",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "December 26 â€“ December 31",
      "2021 Dates": "NA",
      "Display Name": "New Year's Eve",
      "Internal Label": "NewYearsEveGermany",
      "Unlock Date": "2020-12-26",
      "Unlock Method": "NTP",
      "Unique Entry ID": "pg7Wus3cgYWtn4wAg"
    }],
    "type": "Seasons and Events"
  },
  "Nochevieja": {
    "group": [{
      "Name": "Nochevieja",
      "Type": "Nook Shopping event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "December 26 â€“ December 31",
      "Dates (Southern Hemisphere)": "December 26 â€“ December 31",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "December 26 â€“ December 31",
      "2021 Dates": "NA",
      "Display Name": "New Year's Eve",
      "Internal Label": "NewYearsEveSpain",
      "Unlock Date": "2020-12-26",
      "Unlock Method": "NTP",
      "Unique Entry ID": "QgqtGLo5zitZsvcPE"
    }],
    "type": "Seasons and Events"
  },
  "New Year's Eve": {
    "group": [{
      "Name": "New Year's Eve",
      "Type": "Nook Shopping event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2020",
      "Dates (Northern Hemisphere)": "December 26 â€“ December 31",
      "Dates (Southern Hemisphere)": "December 26 â€“ December 31",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "December 26 â€“ December 31",
      "2021 Dates": "NA",
      "Display Name": "New Year's Eve",
      "Internal Label": "NewYearsEveWorld",
      "Unlock Date": "2020-12-26",
      "Unlock Method": "NTP",
      "Unique Entry ID": "cBXYqjysyynrFu7fw"
    }],
    "type": "Seasons and Events"
  },
  "ShÅgatsu (1)": {
    "group": [{
      "Name": "ShÅgatsu (1)",
      "Type": "Nook Shopping event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "January 1 â€“ January 15",
      "Dates (Southern Hemisphere)": "January 1 â€“ January 15",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "January 1 â€“ January 15",
      "Display Name": "New Year's Day",
      "Internal Label": "RegionNewYear",
      "Unlock Date": "2021-01-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "LwmgQ2WpBrBhJDDcZ"
    }],
    "type": "Seasons and Events"
  },
  "ShÅgatsu (2)": {
    "group": [{
      "Name": "ShÅgatsu (2)",
      "Type": "Nook Shopping event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "January 1 â€“ January 15",
      "Dates (Southern Hemisphere)": "January 1 â€“ January 15",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "January 1 â€“ January 15",
      "Display Name": "New Year's Day",
      "Internal Label": "RegionNewYear2",
      "Unlock Date": "2021-01-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "Yvq5mrsjYX9HBBoN2"
    }],
    "type": "Seasons and Events"
  },
  "ShÅgatsu (3)": {
    "group": [{
      "Name": "ShÅgatsu (3)",
      "Type": "Nook Shopping event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "January 1 â€“ January 15",
      "Dates (Southern Hemisphere)": "January 1 â€“ January 15",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "January 1 â€“ January 15",
      "Display Name": "New Year's Day",
      "Internal Label": "RegionNewYear3",
      "Unlock Date": "2021-01-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "j6XM3Bsw5vtskwub2"
    }],
    "type": "Seasons and Events"
  },
  "New Year's Day (Russia)": {
    "group": [{
      "Name": "New Year's Day (Russia)",
      "Type": "Nook Shopping event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "January 1 â€“ January 15",
      "Dates (Southern Hemisphere)": "January 1 â€“ January 15",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "January 1 â€“ January 15",
      "Display Name": "New Year's Day",
      "Internal Label": "RoshiaNewYear",
      "Unlock Date": "2021-01-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "7tSXFbSyGohRqRcAd"
    }],
    "type": "Seasons and Events"
  },
  "New Year's Day (World)": {
    "group": [{
      "Name": "New Year's Day (World)",
      "Type": "Nook Shopping event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "January 1 â€“ January 15",
      "Dates (Southern Hemisphere)": "January 1 â€“ January 15",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "January 1 â€“ January 15",
      "Display Name": "New Year's Day",
      "Internal Label": "WorldNewYear",
      "Unlock Date": "2021-01-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "s9EY4eT28FvMq4MmR"
    }],
    "type": "Seasons and Events"
  },
  "New Year's Day (Korea)": {
    "group": [{
      "Name": "New Year's Day (Korea)",
      "Type": "Nook Shopping event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "January 1 â€“ January 15",
      "Dates (Southern Hemisphere)": "January 1 â€“ January 15",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "January 1 â€“ January 15",
      "Display Name": "New Year's Day",
      "Internal Label": "KoreaNewYear",
      "Unlock Date": "2021-01-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "9sayQ8ZTXonPimMf2"
    }],
    "type": "Seasons and Events"
  },
  "New Year's Day (Asia)": {
    "group": [{
      "Name": "New Year's Day (Asia)",
      "Type": "Nook Shopping event",
      "Version Added": "1.6.0",
      "Version Last Updated": "1.6.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "January 1 â€“ January 15",
      "Dates (Southern Hemisphere)": "January 1 â€“ January 15",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "January 1 â€“ January 15",
      "Display Name": "New Year's Day",
      "Internal Label": "ChinaNewYear",
      "Unlock Date": "2021-01-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "PnPBujYf6ztitFX7F"
    }],
    "type": "Seasons and Events"
  },
  "Festivale (ready days)": {
    "group": [{
      "Name": "Festivale (ready days)",
      "Type": "Special event",
      "Version Added": "1.7.0",
      "Version Last Updated": "1.7.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "February 1 â€“Â February 14",
      "Dates (Southern Hemisphere)": "February 1 â€“Â February 14",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "February 1 â€“Â February 14",
      "Display Name": "Festivale",
      "Internal Label": "Carnival",
      "Unlock Date": "2021-01-28",
      "Unlock Method": "No",
      "Unique Entry ID": "F7bzc2pLevmboA8DF"
    }],
    "type": "Seasons and Events"
  },
  "Festivale": {
    "group": [{
      "Name": "Festivale",
      "Type": "Special event",
      "Version Added": "1.7.0",
      "Version Last Updated": "1.7.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "February 15",
      "Dates (Southern Hemisphere)": "February 15",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "February 15",
      "Display Name": "Festivale",
      "Internal Label": "Carnival",
      "Unlock Date": "2021-02-14",
      "Unlock Method": "BCAT (a)",
      "Unique Entry ID": "FvssW626ddQ3aLQFd"
    }],
    "type": "Seasons and Events"
  },
  "Valentine's Day": {
    "group": [{
      "Name": "Valentine's Day",
      "Type": "Special event",
      "Version Added": "1.7.0",
      "Version Last Updated": "1.7.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "February 14",
      "Dates (Southern Hemisphere)": "February 14",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "February 14",
      "Display Name": "Valentine's Day",
      "Internal Label": "Valentine",
      "Unlock Date": "2021-02-14",
      "Unlock Method": "BCAT (a)",
      "Unique Entry ID": "wFQawZsWKLnDfSjjN"
    }],
    "type": "Seasons and Events"
  },
  "Groundhog Day": {
    "group": [{
      "Name": "Groundhog Day",
      "Type": "Nook Shopping event",
      "Version Added": "1.7.0",
      "Version Last Updated": "1.7.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "January 25 â€“Â February 2",
      "Dates (Southern Hemisphere)": "January 25 â€“Â February 2",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "January 25 â€“Â February 2",
      "Display Name": "Groundhog Day",
      "Internal Label": "GroundhogDay",
      "Unlock Date": "2021-01-28",
      "Unlock Method": "NTP",
      "Unique Entry ID": "y9Bn4GYZPnMEoBgfB"
    }],
    "type": "Seasons and Events"
  },
  "Setsubun": {
    "group": [{
      "Name": "Setsubun",
      "Type": "Nook Shopping event",
      "Version Added": "1.7.0",
      "Version Last Updated": "1.7.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "January 25 â€“Â February 3",
      "Dates (Southern Hemisphere)": "January 25 â€“Â February 3",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "January 25 â€“Â February 3",
      "Display Name": "Setsubun",
      "Internal Label": "Setsubun",
      "Unlock Date": "2021-01-28",
      "Unlock Method": "NTP",
      "Unique Entry ID": "JanWTpqgkvHZzetxk"
    }],
    "type": "Seasons and Events"
  },
  "Setsubun (Able Sisters)": {
    "group": [{
      "Name": "Setsubun (Able Sisters)",
      "Type": "Shopping season",
      "Version Added": "1.7.0",
      "Version Last Updated": "1.7.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "February 1 â€“Â February 3",
      "Dates (Southern Hemisphere)": "February 1 â€“Â February 3",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "February 1 â€“Â February 3",
      "Southern Hemisphere Dates": "February 1 â€“Â February 3",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Setsubun",
      "Internal Label": "NA",
      "Unlock Date": "2021-01-28",
      "Unlock Method": "No",
      "Unique Entry ID": "kFoAs7RfGYzw62LLt"
    }],
    "type": "Seasons and Events"
  },
  "Big Game Celebration (1)": {
    "group": [{
      "Name": "Big Game Celebration (1)",
      "Type": "Nook Shopping event",
      "Version Added": "1.7.0",
      "Version Last Updated": "1.7.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "January 15 â€“Â February 15",
      "Dates (Southern Hemisphere)": "January 15 â€“Â February 15",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "January 15 â€“Â February 15",
      "Display Name": "Big Game Celebration",
      "Internal Label": "RegionBigGame",
      "Unlock Date": "2021-01-28",
      "Unlock Method": "NTP",
      "Unique Entry ID": "cxbGFKdkmqFsskvuj"
    }],
    "type": "Seasons and Events"
  },
  "Big Game Celebration (2)": {
    "group": [{
      "Name": "Big Game Celebration (2)",
      "Type": "Nook Shopping event",
      "Version Added": "1.7.0",
      "Version Last Updated": "1.7.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "January 15 â€“Â February 15",
      "Dates (Southern Hemisphere)": "January 15 â€“Â February 15",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "January 15 â€“Â February 15",
      "Display Name": "Big Game Celebration",
      "Internal Label": "RegionBigGame2",
      "Unlock Date": "2021-01-28",
      "Unlock Method": "NTP",
      "Unique Entry ID": "EPBKFGfCaW9bEAZan"
    }],
    "type": "Seasons and Events"
  },
  "Valentine's Day (Nook Shopping)": {
    "group": [{
      "Name": "Valentine's Day (Nook Shopping)",
      "Type": "Nook Shopping event",
      "Version Added": "1.7.0",
      "Version Last Updated": "1.7.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "February 1 â€“Â February 14",
      "Dates (Southern Hemisphere)": "February 1 â€“Â February 14",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "February 1 â€“Â February 14",
      "Display Name": "Valentine's Day",
      "Internal Label": "RegionValentine",
      "Unlock Date": "2021-02-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "scq9e4MNaxBDnzdsf"
    }],
    "type": "Seasons and Events"
  },
  "Lunar New Year": {
    "group": [{
      "Name": "Lunar New Year",
      "Type": "Nook Shopping event",
      "Version Added": "1.7.0",
      "Version Last Updated": "1.7.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "February 10 â€“ February 17",
      "Dates (Southern Hemisphere)": "February 10 â€“ February 17",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "February 10 â€“ February 17",
      "Display Name": "Lunar New Year",
      "Internal Label": "RegionLunarNewYearAsia",
      "Unlock Date": "2021-02-10",
      "Unlock Method": "NTP",
      "Unique Entry ID": "GrhL6oc4Fikexi9mE"
    }],
    "type": "Seasons and Events"
  },
  "Seollal": {
    "group": [{
      "Name": "Seollal",
      "Type": "Nook Shopping event",
      "Version Added": "1.7.0",
      "Version Last Updated": "1.7.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "February 10 â€“ February 17",
      "Dates (Southern Hemisphere)": "February 10 â€“ February 17",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "February 10 â€“ February 17",
      "Display Name": "Lunar New Year",
      "Internal Label": "RegionLunarNewYearKR",
      "Unlock Date": "2021-02-10",
      "Unlock Method": "NTP",
      "Unique Entry ID": "i36Hq5eemLtYtg8x4"
    }],
    "type": "Seasons and Events"
  },
  "Hinamatsuri": {
    "group": [{
      "Name": "Hinamatsuri",
      "Type": "Nook Shopping event",
      "Version Added": "1.8.0",
      "Version Last Updated": "1.8.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "February 25 â€“Â March 3",
      "Dates (Southern Hemisphere)": "February 25 â€“Â March 3",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "February 25 â€“Â March 3",
      "Display Name": "Hinamatsuri",
      "Internal Label": "RegionHinamatsuri",
      "Unlock Date": "2021-02-25",
      "Unlock Method": "NTP",
      "Unique Entry ID": "nca8hecauJyrMuTe6"
    }],
    "type": "Seasons and Events"
  },
  "Super Mario Bros.": {
    "group": [{
      "Name": "Super Mario Bros.",
      "Type": "Nook Shopping event",
      "Version Added": "1.8.0",
      "Version Last Updated": "1.8.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "March 1 â€“ December 31",
      "Dates (Southern Hemisphere)": "March 1 â€“ December 31",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "March 1 â€“ December 31",
      "Display Name": "Super Mario Bros.",
      "Internal Label": "MarioCollaboration",
      "Unlock Date": "2021-03-01",
      "Unlock Method": "BCAT (a)",
      "Unique Entry ID": "2TaNitnLqDtXr9SQK"
    }],
    "type": "Seasons and Events"
  },
  "Ï€ Day": {
    "group": [{
      "Name": "Ï€ Day",
      "Type": "Nook Shopping event",
      "Version Added": "1.8.0",
      "Version Last Updated": "1.8.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "March 1 â€“Â March 14",
      "Dates (Southern Hemisphere)": "March 1 â€“Â March 14",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "March 1 â€“Â March 14",
      "Display Name": "Ï€ Day",
      "Internal Label": "RegionPiDay",
      "Unlock Date": "2021-03-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "atSCGTvcdHq2EKNfy"
    }],
    "type": "Seasons and Events"
  },
  "Shamrock Day": {
    "group": [{
      "Name": "Shamrock Day",
      "Type": "Nook Shopping event",
      "Version Added": "1.8.0",
      "Version Last Updated": "1.8.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "March 10 â€“Â March 17",
      "Dates (Southern Hemisphere)": "March 10 â€“Â March 17",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "March 10 â€“Â March 17",
      "Display Name": "Shamrock Day",
      "Internal Label": "RegionShamrockDay",
      "Unlock Date": "2021-03-10",
      "Unlock Method": "NTP",
      "Unique Entry ID": "zZcYX6kijYEszM3u8"
    }],
    "type": "Seasons and Events"
  },
  "Shamrock Day (Able Sisters)": {
    "group": [{
      "Name": "Shamrock Day (Able Sisters)",
      "Type": "Shopping season",
      "Version Added": "1.8.0",
      "Version Last Updated": "1.8.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "March 10 â€“Â March 17",
      "Dates (Southern Hemisphere)": "March 10 â€“Â March 17",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "March 10 â€“Â March 17",
      "Southern Hemisphere Dates": "March 10 â€“Â March 17",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Shamrock Day",
      "Internal Label": "NA",
      "Unlock Date": "2021-01-28",
      "Unlock Method": "No",
      "Unique Entry ID": "CQeFs5yEfzL3kFdhp"
    }],
    "type": "Seasons and Events"
  },
  "April Fools' Day": {
    "group": [{
      "Name": "April Fools' Day",
      "Type": "Nook Shopping event",
      "Version Added": "1.9.0",
      "Version Last Updated": "1.9.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "March 26 â€“Â April 1",
      "Dates (Southern Hemisphere)": "March 26 â€“Â April 1",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "March 26 â€“Â April 1",
      "Display Name": "April Fools' Day",
      "Internal Label": "RegionAprilFool",
      "Unlock Date": "2021-03-26",
      "Unlock Method": "NTP",
      "Unique Entry ID": "PQbKAS4Jt7mWpBBxx"
    }],
    "type": "Seasons and Events"
  },
  "Singmogil": {
    "group": [{
      "Name": "Singmogil",
      "Type": "Nook Shopping event",
      "Version Added": "1.9.0",
      "Version Last Updated": "1.9.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "April 1 â€“ April 10",
      "Dates (Southern Hemisphere)": "April 1 â€“ April 10",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "April 1 â€“ April 10",
      "Display Name": "Singmogil",
      "Internal Label": "RegionTreeDay",
      "Unlock Date": "2021-04-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "33Y77jAzMCTuwH2Dq"
    }],
    "type": "Seasons and Events"
  },
  "Prom (1)": {
    "group": [{
      "Name": "Prom (1)",
      "Type": "Nook Shopping event",
      "Version Added": "1.9.0",
      "Version Last Updated": "1.9.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "April 1 â€“Â April 30",
      "Dates (Southern Hemisphere)": "April 1 â€“Â April 30",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "April 1 â€“Â April 30",
      "Display Name": "Prom",
      "Internal Label": "RegionProm",
      "Unlock Date": "2021-04-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "GEpYcBtjkvLTEahT4"
    }],
    "type": "Seasons and Events"
  },
  "Prom (2)": {
    "group": [{
      "Name": "Prom (2)",
      "Type": "Nook Shopping event",
      "Version Added": "1.9.0",
      "Version Last Updated": "1.9.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "April 1 â€“Â April 30",
      "Dates (Southern Hemisphere)": "April 1 â€“Â April 30",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "April 1 â€“Â April 30",
      "Display Name": "Prom",
      "Internal Label": "RegionProm2",
      "Unlock Date": "2021-04-01",
      "Unlock Method": "NTP",
      "Unique Entry ID": "LQZH8ucChbLZn79gS"
    }],
    "type": "Seasons and Events"
  },
  "Prom (Able Sisters)": {
    "group": [{
      "Name": "Prom (Able Sisters)",
      "Type": "Shopping season",
      "Version Added": "1.9.0",
      "Version Last Updated": "1.9.0",
      "Year": "Any",
      "Dates (Northern Hemisphere)": "April 1 â€“Â April 30",
      "Dates (Southern Hemisphere)": "April 1 â€“Â April 30",
      "Availability": "Every year",
      "Northern Hemisphere Dates": "April 1 â€“Â April 30",
      "Southern Hemisphere Dates": "April 1 â€“Â April 30",
      "2020 Dates": "NA",
      "2021 Dates": "NA",
      "Display Name": "Prom",
      "Internal Label": "NA",
      "Unlock Date": "2021-03-18",
      "Unlock Method": "No",
      "Unique Entry ID": "9cNxPyHeSSrSRFfTw"
    }],
    "type": "Seasons and Events"
  },
  "Nature Day (Nook Shopping)": {
    "group": [{
      "Name": "Nature Day (Nook Shopping)",
      "Type": "Nook Shopping event",
      "Version Added": "1.9.0",
      "Version Last Updated": "1.9.0",
      "Year": "2021",
      "Dates (Northern Hemisphere)": "April 15 â€“Â April 22",
      "Dates (Southern Hemisphere)": "April 15 â€“Â April 22",
      "Availability": "Specific years",
      "Northern Hemisphere Dates": "NA",
      "Southern Hemisphere Dates": "NA",
      "2020 Dates": "NA",
      "2021 Dates": "April 15 â€“Â April 22",
      "Display Name": "Nature Day",
      "Internal Label": "RegionEarthDay",
      "Unlock Date": "2021-04-15",
      "Unlock Method": "NTP",
      "Unique Entry ID": "SwxjFbKbQzaP5t4xC"
    }],
    "type": "Seasons and Events"
  }
}
export default seasonsAndEvents;