const seasonsAndEvents = [
	{
		"Name": "young spring bamboo",
		"Type": "Crafting season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "February 25 â€“ May 21",
		"Dates (Southern Hemisphere)": "August 25 â€“Â November 30",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "February 25 â€“ May 21",
		"Southern Hemisphere Dates": "August 25 â€“Â November 30",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "young spring bamboo",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "B4yFhfZgohc6mpGye"
	},
	{
		"Name": "cherry-blossom petals",
		"Type": "Crafting season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "April 1 â€“Â April 10",
		"Dates (Southern Hemisphere)": "October 1 â€“ October 10",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "April 1 â€“Â April 10",
		"Southern Hemisphere Dates": "October 1 â€“ October 10",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "cherry-blossom petals",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "Xo3c8z7JTrEth4NW7"
	},
	{
		"Name": "summer shells",
		"Type": "Crafting season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "June 1 â€“Â August 31",
		"Dates (Southern Hemisphere)": "December 1 â€“Â February 29",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "June 1 â€“Â August 31",
		"Southern Hemisphere Dates": "December 1 â€“Â February 29",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "summer shells",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "sjovDaZqkh4jafozk"
	},
	{
		"Name": "acorns and pine cones",
		"Type": "Crafting season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "September 1 â€“Â December 10",
		"Dates (Southern Hemisphere)": "March 1 â€“Â June 10",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "September 1 â€“Â December 10",
		"Southern Hemisphere Dates": "March 1 â€“Â June 10",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "acorns and pine cones",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "Rj8eWkGTM5STPvprt"
	},
	{
		"Name": "mushrooms",
		"Type": "Crafting season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "November 1 â€“ November 30",
		"Dates (Southern Hemisphere)": "May 1 â€“Â May 31",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "November 1 â€“ November 30",
		"Southern Hemisphere Dates": "May 1 â€“Â May 31",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "mushrooms",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "hAE9QzEyaKskMpTfw"
	},
	{
		"Name": "maple leaves",
		"Type": "Crafting season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "November 16 â€“ November 25",
		"Dates (Southern Hemisphere)": "May 16 â€“ May 25",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "November 16 â€“ November 25",
		"Southern Hemisphere Dates": "May 16 â€“ May 25",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "maple leaves",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "2pHZfthLCYjYxEGXJ"
	},
	{
		"Name": "snowflakes",
		"Type": "Crafting season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "December 11 â€“ February 24",
		"Dates (Southern Hemisphere)": "June 11 â€“Â August 24",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "December 11 â€“ February 24",
		"Southern Hemisphere Dates": "June 11 â€“Â August 24",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "snowflakes",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "owiAqbhvj8Ej62yer"
	},
	{
		"Name": "ornaments",
		"Type": "Crafting season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "December 15 â€“Â January 6",
		"Dates (Southern Hemisphere)": "December 15 â€“Â January 6",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "December 15 â€“Â January 6",
		"Southern Hemisphere Dates": "December 15 â€“Â January 6",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "ornaments",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "hMjjfnZoboSEfX6kN"
	},
	{
		"Name": "Aries",
		"Type": "Zodiac season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "March 21 â€“Â April 19",
		"Dates (Southern Hemisphere)": "March 21 â€“Â April 19",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "March 21 â€“Â April 19",
		"Southern Hemisphere Dates": "March 21 â€“Â April 19",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Aries",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "x8ieT7oBnYmXxDq7A"
	},
	{
		"Name": "Taurus",
		"Type": "Zodiac season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "April 20 â€“Â May 20",
		"Dates (Southern Hemisphere)": "April 20 â€“Â May 20",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "April 20 â€“Â May 20",
		"Southern Hemisphere Dates": "April 20 â€“Â May 20",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Taurus",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "zhNANPmM76brtTv8z"
	},
	{
		"Name": "Gemini",
		"Type": "Zodiac season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "May 21 â€“Â June 21",
		"Dates (Southern Hemisphere)": "May 21 â€“Â June 21",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "May 21 â€“Â June 21",
		"Southern Hemisphere Dates": "May 21 â€“Â June 21",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Gemini",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "vKNjJizgqpQfBgf5y"
	},
	{
		"Name": "Cancer",
		"Type": "Zodiac season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "June 22 â€“Â July 22",
		"Dates (Southern Hemisphere)": "June 22 â€“Â July 22",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "June 22 â€“Â July 22",
		"Southern Hemisphere Dates": "June 22 â€“Â July 22",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Cancer",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "d7jo5yXDsHr7ZPSn7"
	},
	{
		"Name": "Leo",
		"Type": "Zodiac season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "July 23 â€“Â August 22",
		"Dates (Southern Hemisphere)": "July 23 â€“Â August 22",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "July 23 â€“Â August 22",
		"Southern Hemisphere Dates": "July 23 â€“Â August 22",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Leo",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "TKcZ9NSsgrFpDgsa8"
	},
	{
		"Name": "Virgo",
		"Type": "Zodiac season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "August 23 â€“ September 22",
		"Dates (Southern Hemisphere)": "August 23 â€“ September 22",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "August 23 â€“ September 22",
		"Southern Hemisphere Dates": "August 23 â€“ September 22",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Virgo",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "s5pDRHdgiSvDQqHdL"
	},
	{
		"Name": "Libra",
		"Type": "Zodiac season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "September 23 â€“ October 23",
		"Dates (Southern Hemisphere)": "September 23 â€“ October 23",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "September 23 â€“ October 23",
		"Southern Hemisphere Dates": "September 23 â€“ October 23",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Libra",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "9XGhdA9uRd8wpFcnF"
	},
	{
		"Name": "Scorpio",
		"Type": "Zodiac season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "October 24 â€“Â November 22",
		"Dates (Southern Hemisphere)": "October 24 â€“Â November 22",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "October 24 â€“Â November 22",
		"Southern Hemisphere Dates": "October 24 â€“Â November 22",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Scorpio",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "596kyafmfDmHdW7ce"
	},
	{
		"Name": "Sagittarius",
		"Type": "Zodiac season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "November 23 â€“Â December 21",
		"Dates (Southern Hemisphere)": "November 23 â€“Â December 21",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "November 23 â€“Â December 21",
		"Southern Hemisphere Dates": "November 23 â€“Â December 21",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Sagittarius",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "bTaE6agqsduPGZ9h3"
	},
	{
		"Name": "Capricorn",
		"Type": "Zodiac season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "December 22 â€“Â January 19",
		"Dates (Southern Hemisphere)": "December 22 â€“Â January 19",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "December 22 â€“Â January 19",
		"Southern Hemisphere Dates": "December 22 â€“Â January 19",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Capricorn",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "Hg5dLT2EZYv4AqRHS"
	},
	{
		"Name": "Aquarius",
		"Type": "Zodiac season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "January 20 â€“Â February 18",
		"Dates (Southern Hemisphere)": "January 20 â€“Â February 18",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "January 20 â€“Â February 18",
		"Southern Hemisphere Dates": "January 20 â€“Â February 18",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Aquarius",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "qhhHqPBRzJ7qLsocW"
	},
	{
		"Name": "Pisces",
		"Type": "Zodiac season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "February 19 â€“Â March 20",
		"Dates (Southern Hemisphere)": "February 19 â€“Â March 20",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "February 19 â€“Â March 20",
		"Southern Hemisphere Dates": "February 19 â€“Â March 20",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Pisces",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "t3oLZbrWRDCqGFWff"
	},
	{
		"Name": "Spring shopping",
		"Type": "Shopping season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "March 1 â€“Â May 31",
		"Dates (Southern Hemisphere)": "September 1 â€“ November 30",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "March 1 â€“Â May 31",
		"Southern Hemisphere Dates": "September 1 â€“ November 30",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Spring shopping",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "cgstqsmrRFsG3HRHm"
	},
	{
		"Name": "Summer shopping",
		"Type": "Shopping season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "June 1 â€“Â August 31",
		"Dates (Southern Hemisphere)": "December 1 â€“ February 29",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "June 1 â€“Â August 31",
		"Southern Hemisphere Dates": "December 1 â€“ February 29",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Summer shopping",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "gdqi5z5jot9H4fsz9"
	},
	{
		"Name": "Fall shopping",
		"Type": "Shopping season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "September 1 â€“ November 30",
		"Dates (Southern Hemisphere)": "March 1 â€“Â May 31",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "September 1 â€“ November 30",
		"Southern Hemisphere Dates": "March 1 â€“Â May 31",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Fall shopping",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "pmM4yBFvMXTXcooL5"
	},
	{
		"Name": "Winter shopping",
		"Type": "Shopping season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "December 1 â€“ February 29",
		"Dates (Southern Hemisphere)": "June 1 â€“Â August 31",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "December 1 â€“ February 29",
		"Southern Hemisphere Dates": "June 1 â€“Â August 31",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Winter shopping",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "h5W3JH8kDC4xJHgva"
	},
	{
		"Name": "Festive shopping",
		"Type": "Shopping season",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "December 1 â€“ December 25",
		"Dates (Southern Hemisphere)": "December 1 â€“ December 25",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "December 1 â€“ December 25",
		"Southern Hemisphere Dates": "December 1 â€“ December 25",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Festive shopping",
		"Internal Label": "NA",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "z3NNqZMg7eDZRK3JD"
	},
	{
		"Name": "Birthday",
		"Type": "Basegame event",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "NA",
		"Dates (Southern Hemisphere)": "NA",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Birthday",
		"Internal Label": "PlayerBirthday",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "8gF25cNHcBJxveb5A"
	},
	{
		"Name": "Fishing Tourney",
		"Type": "Basegame event",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "2nd Saturday of April; 2nd Saturday of July; 2nd Saturday of October; 2nd Saturday of January",
		"Dates (Southern Hemisphere)": "2nd Saturday of October; 2nd Saturday of January; 2nd Saturday of April; 2nd Saturday of July",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "2nd Saturday of April; 2nd Saturday of July; 2nd Saturday of October; 2nd Saturday of January",
		"Southern Hemisphere Dates": "2nd Saturday of October; 2nd Saturday of January; 2nd Saturday of April; 2nd Saturday of July",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Fishing Tourney",
		"Internal Label": "FishingConventionSpring; FishingConventionSummer; FishingConventionAutumn; FishingConventionWinter",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "FGE5KSaw2fEX9M7Er"
	},
	{
		"Name": "Bug-Off",
		"Type": "Basegame event",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "4th Saturday of June; 4th Saturday of July; 4th Saturday of August; 4th Saturday of September",
		"Dates (Southern Hemisphere)": "3rd Saturday of November; 3rd Saturday of December; 3rd Saturday of January; 3rd Saturday of February",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "4th Saturday of June; 4th Saturday of July; 4th Saturday of August; 4th Saturday of September",
		"Southern Hemisphere Dates": "3rd Saturday of November; 3rd Saturday of December; 3rd Saturday of January; 3rd Saturday of February",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Bug-Off",
		"Internal Label": "InsectConvention1; InsectConvention2; InsectConvention3; InsectConvention4",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "ARcnvRvmH6ug2JBXi"
	},
	{
		"Name": "Countdown",
		"Type": "Basegame event",
		"Version Added": "1.0.0",
		"Version Last Updated": "1.0.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "December 31",
		"Dates (Southern Hemisphere)": "December 31",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "December 31",
		"Southern Hemisphere Dates": "December 31",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Countdown",
		"Internal Label": "Countdown",
		"Unlock Date": "2020-03-20",
		"Unlock Method": "No",
		"Unique Entry ID": "ofQGGtcwwK7dm9tpW"
	},
	{
		"Name": "Bunny Day (ready days)",
		"Type": "Special event",
		"Version Added": "1.1.0",
		"Version Last Updated": "1.9.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "March 28 â€“Â April 3",
		"Dates (Southern Hemisphere)": "March 28 â€“Â April 3",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "March 28 â€“Â April 3",
		"Display Name": "Bunny Day",
		"Internal Label": "Easter",
		"Unlock Date": "2021-03-28",
		"Unlock Method": "BCAT (a)",
		"Unique Entry ID": "4ku2HWxsXtYsHZPnA"
	},
	{
		"Name": "Bunny Day",
		"Type": "Special event",
		"Version Added": "1.1.0",
		"Version Last Updated": "1.9.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "April 4",
		"Dates (Southern Hemisphere)": "April 4",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "April 4",
		"Display Name": "Bunny Day",
		"Internal Label": "Easter",
		"Unlock Date": "2021-04-04",
		"Unlock Method": "BCAT (b)",
		"Unique Entry ID": "mN6SNYaRhEqushr8n"
	},
	{
		"Name": "Nature Day",
		"Type": "Special event",
		"Version Added": "1.2.0",
		"Version Last Updated": "1.9.0",
		"Year": "NA",
		"Dates (Northern Hemisphere)": "NA",
		"Dates (Southern Hemisphere)": "NA",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Nature Day",
		"Internal Label": "EarthDay",
		"Unlock Date": "2020-04-23",
		"Unlock Method": "No",
		"Unique Entry ID": "ej9oowKQuQmZs4sZY"
	},
	{
		"Name": "May Day",
		"Type": "Special event",
		"Version Added": "1.2.0",
		"Version Last Updated": "1.2.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "May 1 â€“ May 7",
		"Dates (Southern Hemisphere)": "May 1 â€“ May 7",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "May 1 â€“ May 7",
		"2021 Dates": "NA",
		"Display Name": "May Day",
		"Internal Label": "MayDay",
		"Unlock Date": "2020-05-01",
		"Unlock Method": "BCAT (a)",
		"Unique Entry ID": "cRAsXSu4L5HHoScER"
	},
	{
		"Name": "International Museum Day",
		"Type": "Special event",
		"Version Added": "1.2.0",
		"Version Last Updated": "1.2.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "May 18 â€“ May 31",
		"Dates (Southern Hemisphere)": "May 18 â€“ May 31",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "May 18 â€“ May 31",
		"2021 Dates": "NA",
		"Display Name": "International Museum Day",
		"Internal Label": "InternationalMuseum",
		"Unlock Date": "2020-05-18",
		"Unlock Method": "BCAT (b)",
		"Unique Entry ID": "Dk8YdEvdKBNihCDFM"
	},
	{
		"Name": "Wedding Season",
		"Type": "Special event",
		"Version Added": "1.2.0",
		"Version Last Updated": "1.2.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "June 1 â€“ June 30",
		"Dates (Southern Hemisphere)": "June 1 â€“ June 30",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "June 1 â€“ June 30",
		"2021 Dates": "NA",
		"Display Name": "Wedding Season",
		"Internal Label": "JuneBride",
		"Unlock Date": "2020-06-01",
		"Unlock Method": "BCAT (c)",
		"Unique Entry ID": "67TSSQDefBj5N8gp8"
	},
	{
		"Name": "Mother's Day",
		"Type": "Nook Shopping event",
		"Version Added": "1.2.0",
		"Version Last Updated": "1.2.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "May 1 â€“Â May 31",
		"Dates (Southern Hemisphere)": "May 1 â€“Â May 31",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "May 1 â€“Â May 31",
		"2021 Dates": "NA",
		"Display Name": "Mother's Day",
		"Internal Label": "MothersDay",
		"Unlock Date": "2020-05-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "Hs623rDkgMAhnsjhy"
	},
	{
		"Name": "International Children's Day",
		"Type": "Nook Shopping event",
		"Version Added": "1.2.0",
		"Version Last Updated": "1.2.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "June 1 â€“ June 30",
		"Dates (Southern Hemisphere)": "June 1 â€“ June 30",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "June 1 â€“ June 30",
		"2021 Dates": "NA",
		"Display Name": "International Children's Day",
		"Internal Label": "WorldChild",
		"Unlock Date": "2020-06-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "PSzeGZ8iagsS3juM8"
	},
	{
		"Name": "Father's Day",
		"Type": "Nook Shopping event",
		"Version Added": "1.2.0",
		"Version Last Updated": "1.2.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "June 1 â€“ June 30",
		"Dates (Southern Hemisphere)": "June 1 â€“ June 30",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "June 1 â€“ June 30",
		"2021 Dates": "NA",
		"Display Name": "Father's Day",
		"Internal Label": "FathersDay",
		"Unlock Date": "2020-06-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "DGpj63PS3qXFbSYBK"
	},
	{
		"Name": "Summer Solstice (northern hemisphere)",
		"Type": "Nook Shopping event",
		"Version Added": "1.2.0",
		"Version Last Updated": "1.2.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "June 7 â€“Â July 6",
		"Dates (Southern Hemisphere)": "NA",
		"Availability": "Specific years (NH only)",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "June 7 â€“Â July 6",
		"2021 Dates": "NA",
		"Display Name": "Summer Solstice",
		"Internal Label": "SummerSolstice",
		"Unlock Date": "2020-06-07",
		"Unlock Method": "NTP",
		"Unique Entry ID": "vQbgAS6zTFgMZ2Ci4"
	},
	{
		"Name": "Winter Solstice (southern hemisphere)",
		"Type": "Nook Shopping event",
		"Version Added": "1.2.0",
		"Version Last Updated": "1.2.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "NA",
		"Dates (Southern Hemisphere)": "June 7 â€“Â July 6",
		"Availability": "Specific years (SH only)",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "June 7 â€“Â July 6",
		"2021 Dates": "NA",
		"Display Name": "Winter Solstice",
		"Internal Label": "WinterSolstice",
		"Unlock Date": "2020-06-07",
		"Unlock Method": "NTP",
		"Unique Entry ID": "WTek3FANZJsBDDQrf"
	},
	{
		"Name": "Tanabata",
		"Type": "Nook Shopping event",
		"Version Added": "1.3.0",
		"Version Last Updated": "1.3.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "July 1 â€“ July 31",
		"Dates (Southern Hemisphere)": "July 1 â€“ July 31",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "July 1 â€“ July 31",
		"2021 Dates": "NA",
		"Display Name": "Tanabata",
		"Internal Label": "Tanabata",
		"Unlock Date": "2020-07-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "DRHv3aXj2usrWdsHQ"
	},
	{
		"Name": "Fireworks Show",
		"Type": "Special event",
		"Version Added": "1.4.0",
		"Version Last Updated": "1.4.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "August 2; August 9; August 16; August 23; August 30",
		"Dates (Southern Hemisphere)": "August 2; August 9; August 16; August 23; August 30",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "August 2; August 9; August 16; August 23; August 30",
		"2021 Dates": "NA",
		"Display Name": "Fireworks Show",
		"Internal Label": "Fireworks1; Fireworks2; Fireworks3; Fireworks4; Fireworks5",
		"Unlock Date": "2020-07-30",
		"Unlock Method": "No",
		"Unique Entry ID": "h6b7G8S5L36zMPLFg"
	},
	{
		"Name": "Cowboy Festival",
		"Type": "Nook Shopping event",
		"Version Added": "1.4.0",
		"Version Last Updated": "1.4.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "August 1 â€“Â August 31",
		"Dates (Southern Hemisphere)": "August 1 â€“Â August 31",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "August 1 â€“Â August 31",
		"2021 Dates": "NA",
		"Display Name": "Cowboy Festival",
		"Internal Label": "CowBoyFestival",
		"Unlock Date": "2020-08-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "DRqqw3iMu6sranZ5Y"
	},
	{
		"Name": "Cowherd & Weaver Girl Day",
		"Type": "Nook Shopping event",
		"Version Added": "1.4.0",
		"Version Last Updated": "1.4.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "August 1 â€“Â August 31",
		"Dates (Southern Hemisphere)": "August 1 â€“Â August 31",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "August 1 â€“Â August 31",
		"2021 Dates": "NA",
		"Display Name": "Cowherd & Weaver Girl Day",
		"Internal Label": "GyurouSyokujyo",
		"Unlock Date": "2020-08-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "RpMgTwZcCL82njXnh"
	},
	{
		"Name": "Grape Harvest Festival",
		"Type": "Nook Shopping event",
		"Version Added": "1.4.0",
		"Version Last Updated": "1.4.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "September 1 â€“ September 30",
		"Dates (Southern Hemisphere)": "September 1 â€“ September 30",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "September 1 â€“ September 30",
		"2021 Dates": "NA",
		"Display Name": "Grape Harvest Festival",
		"Internal Label": "GrapeHarvestFestival",
		"Unlock Date": "2020-09-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "e6vjhAiYsg9Jzua5t"
	},
	{
		"Name": "Moon-Viewing Day",
		"Type": "Nook Shopping event",
		"Version Added": "1.4.0",
		"Version Last Updated": "1.4.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "September 7 â€“ October 8",
		"Dates (Southern Hemisphere)": "September 7 â€“ October 8",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "September 7 â€“ October 8",
		"2021 Dates": "NA",
		"Display Name": "Moon-Viewing Day",
		"Internal Label": "MidAutumnFestival",
		"Unlock Date": "2020-09-07",
		"Unlock Method": "NTP",
		"Unique Entry ID": "cs2qcLkD4RFZpJRDY"
	},
	{
		"Name": "Halloween (ready days)",
		"Type": "Special event",
		"Version Added": "1.5.0",
		"Version Last Updated": "1.5.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "October 1 â€“ October 30",
		"Dates (Southern Hemisphere)": "October 1 â€“ October 30",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "October 1 â€“ October 30",
		"2021 Dates": "NA",
		"Display Name": "Halloween",
		"Internal Label": "Halloween",
		"Unlock Date": "2020-09-30",
		"Unlock Method": "No",
		"Unique Entry ID": "CkhTdh8xBcjRPmCCM"
	},
	{
		"Name": "Halloween",
		"Type": "Special event",
		"Version Added": "1.5.0",
		"Version Last Updated": "1.5.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "October 31",
		"Dates (Southern Hemisphere)": "October 31",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "October 31",
		"2021 Dates": "NA",
		"Display Name": "Halloween",
		"Internal Label": "Halloween",
		"Unlock Date": "2020-09-30",
		"Unlock Method": "No",
		"Unique Entry ID": "ZYoPaw7SennvjdMqj"
	},
	{
		"Name": "Turkey Day",
		"Type": "Special event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "November 26",
		"Dates (Southern Hemisphere)": "November 26",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "November 26",
		"2021 Dates": "NA",
		"Display Name": "Turkey Day",
		"Internal Label": "HarvestFestival",
		"Unlock Date": "2020-11-26",
		"Unlock Method": "BCAT (a)",
		"Unique Entry ID": "n3cSGsDLnJJqLC76K"
	},
	{
		"Name": "Turkey Day (shopping days)",
		"Type": "Special event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "November 27 â€“ November 30",
		"Dates (Southern Hemisphere)": "November 27 â€“ November 30",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "November 27 â€“ November 30",
		"2021 Dates": "NA",
		"Display Name": "Turkey Day",
		"Internal Label": "HarvestAfterTerm",
		"Unlock Date": "2020-11-26",
		"Unlock Method": "BCAT (a)",
		"Unique Entry ID": "LWQHvmgWcWpx6EBfn"
	},
	{
		"Name": "Toy Day (ready days phase 1)",
		"Type": "Special event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "December 1 â€“ December 14",
		"Dates (Southern Hemisphere)": "December 1 â€“ December 14",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "December 1 â€“ December 14",
		"2021 Dates": "NA",
		"Display Name": "Toy Day",
		"Internal Label": "XmasReady1",
		"Unlock Date": "2020-12-01",
		"Unlock Method": "BCAT (b)",
		"Unique Entry ID": "WwqGv6zGXSbpdW7B2"
	},
	{
		"Name": "Toy Day (ready days phase 2)",
		"Type": "Special event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "December 15 â€“Â December 23",
		"Dates (Southern Hemisphere)": "December 15 â€“Â December 23",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "December 15 â€“Â December 23",
		"2021 Dates": "NA",
		"Display Name": "Toy Day",
		"Internal Label": "XmasReady2",
		"Unlock Date": "2020-12-01",
		"Unlock Method": "BCAT (b)",
		"Unique Entry ID": "4b2C4HeZzZhtbjYo3"
	},
	{
		"Name": "Toy Day",
		"Type": "Special event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "December 24",
		"Dates (Southern Hemisphere)": "December 24",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "December 24",
		"2021 Dates": "NA",
		"Display Name": "Toy Day",
		"Internal Label": "XmasEve",
		"Unlock Date": "2020-12-24",
		"Unlock Method": "BCAT (c)",
		"Unique Entry ID": "8BTw75h6CYtPousz7"
	},
	{
		"Name": "Toy Day (day after)",
		"Type": "Special event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "December 25",
		"Dates (Southern Hemisphere)": "December 25",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "December 25",
		"2021 Dates": "NA",
		"Display Name": "Toy Day",
		"Internal Label": "XmasAfter",
		"Unlock Date": "2020-12-24",
		"Unlock Method": "BCAT (c)",
		"Unique Entry ID": "WRJS7x258JZXcBhiD"
	},
	{
		"Name": "Winter Solstice (northern hemisphere)",
		"Type": "Nook Shopping event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "December 1 â€“ December 31",
		"Dates (Southern Hemisphere)": "NA",
		"Availability": "Specific years (NH only)",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "December 1 â€“ December 31",
		"2021 Dates": "NA",
		"Display Name": "Winter Solstice",
		"Internal Label": "Midwinter",
		"Unlock Date": "2020-12-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "fdqSGfgLZy6xzrL49"
	},
	{
		"Name": "Summer Solstice (southern hemisphere)",
		"Type": "Nook Shopping event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "NA",
		"Dates (Southern Hemisphere)": "December 1 â€“ December 31",
		"Availability": "Specific years (SH only)",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "December 1 â€“ December 31",
		"2021 Dates": "NA",
		"Display Name": "Summer Solstice",
		"Internal Label": "SouthernMidwinter",
		"Unlock Date": "2020-12-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "sQSJrS3vHKbtpNL2L"
	},
	{
		"Name": "ÅŒmisoka",
		"Type": "Nook Shopping event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "December 26 â€“ December 31",
		"Dates (Southern Hemisphere)": "December 26 â€“ December 31",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "December 26 â€“ December 31",
		"2021 Dates": "NA",
		"Display Name": "New Year's Eve",
		"Internal Label": "Oomisoka",
		"Unlock Date": "2020-12-26",
		"Unlock Method": "NTP",
		"Unique Entry ID": "8rWzJhnPupkFxeeE5"
	},
	{
		"Name": "Silvester",
		"Type": "Nook Shopping event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "December 26 â€“ December 31",
		"Dates (Southern Hemisphere)": "December 26 â€“ December 31",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "December 26 â€“ December 31",
		"2021 Dates": "NA",
		"Display Name": "New Year's Eve",
		"Internal Label": "NewYearsEveGermany",
		"Unlock Date": "2020-12-26",
		"Unlock Method": "NTP",
		"Unique Entry ID": "pg7Wus3cgYWtn4wAg"
	},
	{
		"Name": "Nochevieja",
		"Type": "Nook Shopping event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "December 26 â€“ December 31",
		"Dates (Southern Hemisphere)": "December 26 â€“ December 31",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "December 26 â€“ December 31",
		"2021 Dates": "NA",
		"Display Name": "New Year's Eve",
		"Internal Label": "NewYearsEveSpain",
		"Unlock Date": "2020-12-26",
		"Unlock Method": "NTP",
		"Unique Entry ID": "QgqtGLo5zitZsvcPE"
	},
	{
		"Name": "New Year's Eve",
		"Type": "Nook Shopping event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2020",
		"Dates (Northern Hemisphere)": "December 26 â€“ December 31",
		"Dates (Southern Hemisphere)": "December 26 â€“ December 31",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "December 26 â€“ December 31",
		"2021 Dates": "NA",
		"Display Name": "New Year's Eve",
		"Internal Label": "NewYearsEveWorld",
		"Unlock Date": "2020-12-26",
		"Unlock Method": "NTP",
		"Unique Entry ID": "cBXYqjysyynrFu7fw"
	},
	{
		"Name": "ShÅgatsu (1)",
		"Type": "Nook Shopping event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "January 1 â€“ January 15",
		"Dates (Southern Hemisphere)": "January 1 â€“ January 15",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "January 1 â€“ January 15",
		"Display Name": "New Year's Day",
		"Internal Label": "RegionNewYear",
		"Unlock Date": "2021-01-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "LwmgQ2WpBrBhJDDcZ"
	},
	{
		"Name": "ShÅgatsu (2)",
		"Type": "Nook Shopping event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "January 1 â€“ January 15",
		"Dates (Southern Hemisphere)": "January 1 â€“ January 15",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "January 1 â€“ January 15",
		"Display Name": "New Year's Day",
		"Internal Label": "RegionNewYear2",
		"Unlock Date": "2021-01-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "Yvq5mrsjYX9HBBoN2"
	},
	{
		"Name": "ShÅgatsu (3)",
		"Type": "Nook Shopping event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "January 1 â€“ January 15",
		"Dates (Southern Hemisphere)": "January 1 â€“ January 15",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "January 1 â€“ January 15",
		"Display Name": "New Year's Day",
		"Internal Label": "RegionNewYear3",
		"Unlock Date": "2021-01-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "j6XM3Bsw5vtskwub2"
	},
	{
		"Name": "New Year's Day (Russia)",
		"Type": "Nook Shopping event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "January 1 â€“ January 15",
		"Dates (Southern Hemisphere)": "January 1 â€“ January 15",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "January 1 â€“ January 15",
		"Display Name": "New Year's Day",
		"Internal Label": "RoshiaNewYear",
		"Unlock Date": "2021-01-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "7tSXFbSyGohRqRcAd"
	},
	{
		"Name": "New Year's Day (World)",
		"Type": "Nook Shopping event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "January 1 â€“ January 15",
		"Dates (Southern Hemisphere)": "January 1 â€“ January 15",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "January 1 â€“ January 15",
		"Display Name": "New Year's Day",
		"Internal Label": "WorldNewYear",
		"Unlock Date": "2021-01-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "s9EY4eT28FvMq4MmR"
	},
	{
		"Name": "New Year's Day (Korea)",
		"Type": "Nook Shopping event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "January 1 â€“ January 15",
		"Dates (Southern Hemisphere)": "January 1 â€“ January 15",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "January 1 â€“ January 15",
		"Display Name": "New Year's Day",
		"Internal Label": "KoreaNewYear",
		"Unlock Date": "2021-01-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "9sayQ8ZTXonPimMf2"
	},
	{
		"Name": "New Year's Day (Asia)",
		"Type": "Nook Shopping event",
		"Version Added": "1.6.0",
		"Version Last Updated": "1.6.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "January 1 â€“ January 15",
		"Dates (Southern Hemisphere)": "January 1 â€“ January 15",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "January 1 â€“ January 15",
		"Display Name": "New Year's Day",
		"Internal Label": "ChinaNewYear",
		"Unlock Date": "2021-01-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "PnPBujYf6ztitFX7F"
	},
	{
		"Name": "Festivale (ready days)",
		"Type": "Special event",
		"Version Added": "1.7.0",
		"Version Last Updated": "1.7.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "February 1 â€“Â February 14",
		"Dates (Southern Hemisphere)": "February 1 â€“Â February 14",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "February 1 â€“Â February 14",
		"Display Name": "Festivale",
		"Internal Label": "Carnival",
		"Unlock Date": "2021-01-28",
		"Unlock Method": "No",
		"Unique Entry ID": "F7bzc2pLevmboA8DF"
	},
	{
		"Name": "Festivale",
		"Type": "Special event",
		"Version Added": "1.7.0",
		"Version Last Updated": "1.7.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "February 15",
		"Dates (Southern Hemisphere)": "February 15",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "February 15",
		"Display Name": "Festivale",
		"Internal Label": "Carnival",
		"Unlock Date": "2021-02-14",
		"Unlock Method": "BCAT (a)",
		"Unique Entry ID": "FvssW626ddQ3aLQFd"
	},
	{
		"Name": "Valentine's Day",
		"Type": "Special event",
		"Version Added": "1.7.0",
		"Version Last Updated": "1.7.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "February 14",
		"Dates (Southern Hemisphere)": "February 14",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "February 14",
		"Display Name": "Valentine's Day",
		"Internal Label": "Valentine",
		"Unlock Date": "2021-02-14",
		"Unlock Method": "BCAT (a)",
		"Unique Entry ID": "wFQawZsWKLnDfSjjN"
	},
	{
		"Name": "Groundhog Day",
		"Type": "Nook Shopping event",
		"Version Added": "1.7.0",
		"Version Last Updated": "1.7.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "January 25 â€“Â February 2",
		"Dates (Southern Hemisphere)": "January 25 â€“Â February 2",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "January 25 â€“Â February 2",
		"Display Name": "Groundhog Day",
		"Internal Label": "GroundhogDay",
		"Unlock Date": "2021-01-28",
		"Unlock Method": "NTP",
		"Unique Entry ID": "y9Bn4GYZPnMEoBgfB"
	},
	{
		"Name": "Setsubun",
		"Type": "Nook Shopping event",
		"Version Added": "1.7.0",
		"Version Last Updated": "1.7.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "January 25 â€“Â February 3",
		"Dates (Southern Hemisphere)": "January 25 â€“Â February 3",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "January 25 â€“Â February 3",
		"Display Name": "Setsubun",
		"Internal Label": "Setsubun",
		"Unlock Date": "2021-01-28",
		"Unlock Method": "NTP",
		"Unique Entry ID": "JanWTpqgkvHZzetxk"
	},
	{
		"Name": "Setsubun (Able Sisters)",
		"Type": "Shopping season",
		"Version Added": "1.7.0",
		"Version Last Updated": "1.7.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "February 1 â€“Â February 3",
		"Dates (Southern Hemisphere)": "February 1 â€“Â February 3",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "February 1 â€“Â February 3",
		"Southern Hemisphere Dates": "February 1 â€“Â February 3",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Setsubun",
		"Internal Label": "NA",
		"Unlock Date": "2021-01-28",
		"Unlock Method": "No",
		"Unique Entry ID": "kFoAs7RfGYzw62LLt"
	},
	{
		"Name": "Big Game Celebration (1)",
		"Type": "Nook Shopping event",
		"Version Added": "1.7.0",
		"Version Last Updated": "1.7.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "January 15 â€“Â February 15",
		"Dates (Southern Hemisphere)": "January 15 â€“Â February 15",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "January 15 â€“Â February 15",
		"Display Name": "Big Game Celebration",
		"Internal Label": "RegionBigGame",
		"Unlock Date": "2021-01-28",
		"Unlock Method": "NTP",
		"Unique Entry ID": "cxbGFKdkmqFsskvuj"
	},
	{
		"Name": "Big Game Celebration (2)",
		"Type": "Nook Shopping event",
		"Version Added": "1.7.0",
		"Version Last Updated": "1.7.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "January 15 â€“Â February 15",
		"Dates (Southern Hemisphere)": "January 15 â€“Â February 15",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "January 15 â€“Â February 15",
		"Display Name": "Big Game Celebration",
		"Internal Label": "RegionBigGame2",
		"Unlock Date": "2021-01-28",
		"Unlock Method": "NTP",
		"Unique Entry ID": "EPBKFGfCaW9bEAZan"
	},
	{
		"Name": "Valentine's Day (Nook Shopping)",
		"Type": "Nook Shopping event",
		"Version Added": "1.7.0",
		"Version Last Updated": "1.7.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "February 1 â€“Â February 14",
		"Dates (Southern Hemisphere)": "February 1 â€“Â February 14",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "February 1 â€“Â February 14",
		"Display Name": "Valentine's Day",
		"Internal Label": "RegionValentine",
		"Unlock Date": "2021-02-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "scq9e4MNaxBDnzdsf"
	},
	{
		"Name": "Lunar New Year",
		"Type": "Nook Shopping event",
		"Version Added": "1.7.0",
		"Version Last Updated": "1.7.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "February 10 â€“ February 17",
		"Dates (Southern Hemisphere)": "February 10 â€“ February 17",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "February 10 â€“ February 17",
		"Display Name": "Lunar New Year",
		"Internal Label": "RegionLunarNewYearAsia",
		"Unlock Date": "2021-02-10",
		"Unlock Method": "NTP",
		"Unique Entry ID": "GrhL6oc4Fikexi9mE"
	},
	{
		"Name": "Seollal",
		"Type": "Nook Shopping event",
		"Version Added": "1.7.0",
		"Version Last Updated": "1.7.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "February 10 â€“ February 17",
		"Dates (Southern Hemisphere)": "February 10 â€“ February 17",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "February 10 â€“ February 17",
		"Display Name": "Lunar New Year",
		"Internal Label": "RegionLunarNewYearKR",
		"Unlock Date": "2021-02-10",
		"Unlock Method": "NTP",
		"Unique Entry ID": "i36Hq5eemLtYtg8x4"
	},
	{
		"Name": "Hinamatsuri",
		"Type": "Nook Shopping event",
		"Version Added": "1.8.0",
		"Version Last Updated": "1.8.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "February 25 â€“Â March 3",
		"Dates (Southern Hemisphere)": "February 25 â€“Â March 3",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "February 25 â€“Â March 3",
		"Display Name": "Hinamatsuri",
		"Internal Label": "RegionHinamatsuri",
		"Unlock Date": "2021-02-25",
		"Unlock Method": "NTP",
		"Unique Entry ID": "nca8hecauJyrMuTe6"
	},
	{
		"Name": "Super Mario Bros.",
		"Type": "Nook Shopping event",
		"Version Added": "1.8.0",
		"Version Last Updated": "1.8.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "March 1 â€“ December 31",
		"Dates (Southern Hemisphere)": "March 1 â€“ December 31",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "March 1 â€“ December 31",
		"Display Name": "Super Mario Bros.",
		"Internal Label": "MarioCollaboration",
		"Unlock Date": "2021-03-01",
		"Unlock Method": "BCAT (a)",
		"Unique Entry ID": "2TaNitnLqDtXr9SQK"
	},
	{
		"Name": "Ï€ Day",
		"Type": "Nook Shopping event",
		"Version Added": "1.8.0",
		"Version Last Updated": "1.8.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "March 1 â€“Â March 14",
		"Dates (Southern Hemisphere)": "March 1 â€“Â March 14",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "March 1 â€“Â March 14",
		"Display Name": "Ï€ Day",
		"Internal Label": "RegionPiDay",
		"Unlock Date": "2021-03-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "atSCGTvcdHq2EKNfy"
	},
	{
		"Name": "Shamrock Day",
		"Type": "Nook Shopping event",
		"Version Added": "1.8.0",
		"Version Last Updated": "1.8.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "March 10 â€“Â March 17",
		"Dates (Southern Hemisphere)": "March 10 â€“Â March 17",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "March 10 â€“Â March 17",
		"Display Name": "Shamrock Day",
		"Internal Label": "RegionShamrockDay",
		"Unlock Date": "2021-03-10",
		"Unlock Method": "NTP",
		"Unique Entry ID": "zZcYX6kijYEszM3u8"
	},
	{
		"Name": "Shamrock Day (Able Sisters)",
		"Type": "Shopping season",
		"Version Added": "1.8.0",
		"Version Last Updated": "1.8.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "March 10 â€“Â March 17",
		"Dates (Southern Hemisphere)": "March 10 â€“Â March 17",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "March 10 â€“Â March 17",
		"Southern Hemisphere Dates": "March 10 â€“Â March 17",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Shamrock Day",
		"Internal Label": "NA",
		"Unlock Date": "2021-01-28",
		"Unlock Method": "No",
		"Unique Entry ID": "CQeFs5yEfzL3kFdhp"
	},
	{
		"Name": "April Fools' Day",
		"Type": "Nook Shopping event",
		"Version Added": "1.9.0",
		"Version Last Updated": "1.9.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "March 26 â€“Â April 1",
		"Dates (Southern Hemisphere)": "March 26 â€“Â April 1",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "March 26 â€“Â April 1",
		"Display Name": "April Fools' Day",
		"Internal Label": "RegionAprilFool",
		"Unlock Date": "2021-03-26",
		"Unlock Method": "NTP",
		"Unique Entry ID": "PQbKAS4Jt7mWpBBxx"
	},
	{
		"Name": "Singmogil",
		"Type": "Nook Shopping event",
		"Version Added": "1.9.0",
		"Version Last Updated": "1.9.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "April 1 â€“ April 10",
		"Dates (Southern Hemisphere)": "April 1 â€“ April 10",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "April 1 â€“ April 10",
		"Display Name": "Singmogil",
		"Internal Label": "RegionTreeDay",
		"Unlock Date": "2021-04-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "33Y77jAzMCTuwH2Dq"
	},
	{
		"Name": "Prom (1)",
		"Type": "Nook Shopping event",
		"Version Added": "1.9.0",
		"Version Last Updated": "1.9.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "April 1 â€“Â April 30",
		"Dates (Southern Hemisphere)": "April 1 â€“Â April 30",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "April 1 â€“Â April 30",
		"Display Name": "Prom",
		"Internal Label": "RegionProm",
		"Unlock Date": "2021-04-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "GEpYcBtjkvLTEahT4"
	},
	{
		"Name": "Prom (2)",
		"Type": "Nook Shopping event",
		"Version Added": "1.9.0",
		"Version Last Updated": "1.9.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "April 1 â€“Â April 30",
		"Dates (Southern Hemisphere)": "April 1 â€“Â April 30",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "April 1 â€“Â April 30",
		"Display Name": "Prom",
		"Internal Label": "RegionProm2",
		"Unlock Date": "2021-04-01",
		"Unlock Method": "NTP",
		"Unique Entry ID": "LQZH8ucChbLZn79gS"
	},
	{
		"Name": "Prom (Able Sisters)",
		"Type": "Shopping season",
		"Version Added": "1.9.0",
		"Version Last Updated": "1.9.0",
		"Year": "Any",
		"Dates (Northern Hemisphere)": "April 1 â€“Â April 30",
		"Dates (Southern Hemisphere)": "April 1 â€“Â April 30",
		"Availability": "Every year",
		"Northern Hemisphere Dates": "April 1 â€“Â April 30",
		"Southern Hemisphere Dates": "April 1 â€“Â April 30",
		"2020 Dates": "NA",
		"2021 Dates": "NA",
		"Display Name": "Prom",
		"Internal Label": "NA",
		"Unlock Date": "2021-03-18",
		"Unlock Method": "No",
		"Unique Entry ID": "9cNxPyHeSSrSRFfTw"
	},
	{
		"Name": "Nature Day (Nook Shopping)",
		"Type": "Nook Shopping event",
		"Version Added": "1.9.0",
		"Version Last Updated": "1.9.0",
		"Year": "2021",
		"Dates (Northern Hemisphere)": "April 15 â€“Â April 22",
		"Dates (Southern Hemisphere)": "April 15 â€“Â April 22",
		"Availability": "Specific years",
		"Northern Hemisphere Dates": "NA",
		"Southern Hemisphere Dates": "NA",
		"2020 Dates": "NA",
		"2021 Dates": "April 15 â€“Â April 22",
		"Display Name": "Nature Day",
		"Internal Label": "RegionEarthDay",
		"Unlock Date": "2021-04-15",
		"Unlock Method": "NTP",
		"Unique Entry ID": "SwxjFbKbQzaP5t4xC"
	}
]

export default seasonsAndEvents;