const umbrellas = {
  "apple umbrella": {
    "group": [{
      "Name": "apple umbrella",
      "DIY": "Yes",
      "Buy": "NFS",
      "Sell": "1400",
      "HHA Base Points": "103",
      "Color 1": "Yellow",
      "Color 2": "Red",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Crafting",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaApple0",
      "Internal ID": "9948",
      "Unique Entry ID": "FPxdw28z9s2gYgjmr"
    }],
    "type": "Umbrellas"
  },
  "bat umbrella": {
    "group": [{
      "Name": "bat umbrella",
      "DIY": "No",
      "Buy": "840",
      "Sell": "210",
      "HHA Base Points": "3",
      "Color 1": "Black",
      "Color 2": "Black",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaBat0",
      "Internal ID": "6919",
      "Unique Entry ID": "EZnRx49foq3M36yQ4"
    }],
    "type": "Umbrellas"
  },
  "beach umbrella": {
    "group": [{
      "Name": "beach umbrella",
      "DIY": "No",
      "Buy": "770",
      "Sell": "192",
      "HHA Base Points": "3",
      "Color 1": "Blue",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaBeach0",
      "Internal ID": "9957",
      "Unique Entry ID": "3SSFuv6LiH63jych3"
    }],
    "type": "Umbrellas"
  },
  "bear umbrella": {
    "group": [{
      "Name": "bear umbrella",
      "DIY": "No",
      "Buy": "1570",
      "Sell": "392",
      "HHA Base Points": "3",
      "Color 1": "Brown",
      "Color 2": "Beige",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaBear0",
      "Internal ID": "7167",
      "Unique Entry ID": "s7KoPpysn27AeC5zi"
    }],
    "type": "Umbrellas"
  },
  "black chic umbrella": {
    "group": [{
      "Name": "black chic umbrella",
      "DIY": "No",
      "Buy": "1620",
      "Sell": "405",
      "HHA Base Points": "3",
      "Color 1": "Black",
      "Color 2": "Black",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaPacodarace5",
      "Internal ID": "12137",
      "Unique Entry ID": "p8yg9xiFwPscNDJNg"
    }],
    "type": "Umbrellas"
  },
  "black lace umbrella": {
    "group": [{
      "Name": "black lace umbrella",
      "DIY": "No",
      "Buy": "750",
      "Sell": "187",
      "HHA Base Points": "3",
      "Color 1": "Black",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaRace0",
      "Internal ID": "6915",
      "Unique Entry ID": "7vuSb5AutpNQA573q"
    }],
    "type": "Umbrellas"
  },
  "blue dot parasol": {
    "group": [{
      "Name": "blue dot parasol",
      "DIY": "No",
      "Buy": "750",
      "Sell": "187",
      "HHA Base Points": "3",
      "Color 1": "Blue",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaPolkadot2",
      "Internal ID": "9956",
      "Unique Entry ID": "SwKuBi2vT7K365A3p"
    }],
    "type": "Umbrellas"
  },
  "blue shiny-bows parasol": {
    "group": [{
      "Name": "blue shiny-bows parasol",
      "DIY": "No",
      "Buy": "1620",
      "Sell": "405",
      "HHA Base Points": "3",
      "Color 1": "Blue",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaPacodarace2",
      "Internal ID": "12134",
      "Unique Entry ID": "BxZ4XdtfJEyWyBPFe"
    }],
    "type": "Umbrellas"
  },
  "blue umbrella": {
    "group": [{
      "Name": "blue umbrella",
      "DIY": "No",
      "Buy": "770",
      "Sell": "192",
      "HHA Base Points": "3",
      "Color 1": "Blue",
      "Color 2": "Blue",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaStandard2",
      "Internal ID": "9959",
      "Unique Entry ID": "XyJaqSLnBjh5J6vLp"
    }],
    "type": "Umbrellas"
  },
  "busted umbrella": {
    "group": [{
      "Name": "busted umbrella",
      "DIY": "No",
      "Buy": "1570",
      "Sell": "392",
      "HHA Base Points": "3",
      "Color 1": "Black",
      "Color 2": "Black",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaBroken0",
      "Internal ID": "7182",
      "Unique Entry ID": "gkHD9GKJT9eAekxWQ"
    }],
    "type": "Umbrellas"
  },
  "camo umbrella": {
    "group": [{
      "Name": "camo umbrella",
      "DIY": "No",
      "Buy": "650",
      "Sell": "162",
      "HHA Base Points": "3",
      "Color 1": "Green",
      "Color 2": "Beige",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaOutdoor0",
      "Internal ID": "6923",
      "Unique Entry ID": "RJYB5itM7mDdtWHpv"
    }],
    "type": "Umbrellas"
  },
  "candy umbrella": {
    "group": [{
      "Name": "candy umbrella",
      "DIY": "No",
      "Buy": "770",
      "Sell": "192",
      "HHA Base Points": "3",
      "Color 1": "Pink",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaGingham0",
      "Internal ID": "6926",
      "Unique Entry ID": "F6KFg5Yhzgf78pudR"
    }],
    "type": "Umbrellas"
  },
  "cherry umbrella": {
    "group": [{
      "Name": "cherry umbrella",
      "DIY": "Yes",
      "Buy": "NFS",
      "Sell": "1400",
      "HHA Base Points": "103",
      "Color 1": "Red",
      "Color 2": "Red",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Crafting",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaCherry0",
      "Internal ID": "9949",
      "Unique Entry ID": "YwHY3LQXsDeM2iosy"
    }],
    "type": "Umbrellas"
  },
  "cherry-blossom umbrella": {
    "group": [{
      "Name": "cherry-blossom umbrella",
      "DIY": "Yes",
      "Buy": "NFS",
      "Sell": "2800",
      "HHA Base Points": "201",
      "Color 1": "Pink",
      "Color 2": "Green",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Crafting",
      "Season/Event": "cherry-blossom petals",
      "Season/Event Exclusive": "Yes",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaCherryblossom0",
      "Internal ID": "9945",
      "Unique Entry ID": "vTu5kLPipRb69vJA3"
    }],
    "type": "Umbrellas"
  },
  "DAL umbrella": {
    "group": [{
      "Name": "DAL umbrella",
      "DIY": "No",
      "Buy": "NFS",
      "Sell": "1010",
      "HHA Base Points": "251",
      "Color 1": "Blue",
      "Color 2": "Blue",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Dodo Airlines",
      "Source Notes": "Received in mail from DAL after 160 flights",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaDoc0",
      "Internal ID": "9560",
      "Unique Entry ID": "vTdEjywjFjr8AkePD"
    }],
    "type": "Umbrellas"
  },
  "eggy parasol": {
    "group": [{
      "Name": "eggy parasol",
      "DIY": "No",
      "Buy": "750",
      "Sell": "187",
      "HHA Base Points": "3",
      "Color 1": "Yellow",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaPolkadot1",
      "Internal ID": "9955",
      "Unique Entry ID": "qf7Hn5CKMDMBpge9r"
    }],
    "type": "Umbrellas"
  },
  "exquisite parasol": {
    "group": [{
      "Name": "exquisite parasol",
      "DIY": "No",
      "Buy": "1670",
      "Sell": "417",
      "HHA Base Points": "3",
      "Color 1": "Yellow",
      "Color 2": "Pink",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaChina0",
      "Internal ID": "7171",
      "Unique Entry ID": "tFFuizXunsrHcMbEj"
    }],
    "type": "Umbrellas"
  },
  "fairy-tale umbrella": {
    "group": [{
      "Name": "fairy-tale umbrella",
      "DIY": "No",
      "Buy": "820",
      "Sell": "205",
      "HHA Base Points": "3",
      "Color 1": "Green",
      "Color 2": "Yellow",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaFairytale0",
      "Internal ID": "7175",
      "Unique Entry ID": "xKBGNFJd2qpWeDWjo"
    }],
    "type": "Umbrellas"
  },
  "fish umbrella": {
    "group": [{
      "Name": "fish umbrella",
      "DIY": "No",
      "Buy": "NFS",
      "Sell": "80",
      "HHA Base Points": "501",
      "Color 1": "Blue",
      "Color 2": "Aqua",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "C.J.",
      "Season/Event": "Fishing Tourney",
      "Season/Event Exclusive": "Yes",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaFish0",
      "Internal ID": "8768",
      "Unique Entry ID": "bvwaqJav8wmjPj2RC"
    }],
    "type": "Umbrellas"
  },
  "frog umbrella": {
    "group": [{
      "Name": "frog umbrella",
      "DIY": "No",
      "Buy": "1570",
      "Sell": "392",
      "HHA Base Points": "3",
      "Color 1": "Green",
      "Color 2": "Green",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaFrog0",
      "Internal ID": "6925",
      "Unique Entry ID": "nDBiFvLtf5KeStQNv"
    }],
    "type": "Umbrellas"
  },
  "gelato umbrella": {
    "group": [{
      "Name": "gelato umbrella",
      "DIY": "No",
      "Buy": "750",
      "Sell": "187",
      "HHA Base Points": "3",
      "Color 1": "Colorful",
      "Color 2": "Colorful",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaTricolor0",
      "Internal ID": "7180",
      "Unique Entry ID": "tupHZa6zDdFvobTEt"
    }],
    "type": "Umbrellas"
  },
  "ghost umbrella": {
    "group": [{
      "Name": "ghost umbrella",
      "DIY": "No",
      "Buy": "1670",
      "Sell": "417",
      "HHA Base Points": "3",
      "Color 1": "White",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaTeruteru0",
      "Internal ID": "6924",
      "Unique Entry ID": "83zEbSL3S3dty4YjN"
    }],
    "type": "Umbrellas"
  },
  "grape umbrella": {
    "group": [{
      "Name": "grape umbrella",
      "DIY": "No",
      "Buy": "1550",
      "Sell": "387",
      "HHA Base Points": "3",
      "Color 1": "Purple",
      "Color 2": "Green",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaGrape0",
      "Internal ID": "6911",
      "Unique Entry ID": "TJ9cw4XSj64u3uEsx"
    }],
    "type": "Umbrellas"
  },
  "green chic umbrella": {
    "group": [{
      "Name": "green chic umbrella",
      "DIY": "No",
      "Buy": "1620",
      "Sell": "405",
      "HHA Base Points": "3",
      "Color 1": "Green",
      "Color 2": "Black",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaPacodarace4",
      "Internal ID": "12136",
      "Unique Entry ID": "u2YWae8oz23XcT4u9"
    }],
    "type": "Umbrellas"
  },
  "green umbrella": {
    "group": [{
      "Name": "green umbrella",
      "DIY": "No",
      "Buy": "770",
      "Sell": "192",
      "HHA Base Points": "3",
      "Color 1": "Green",
      "Color 2": "Green",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaStandard3",
      "Internal ID": "9960",
      "Unique Entry ID": "8Hf4oRy3cQdundDJK"
    }],
    "type": "Umbrellas"
  },
  "hydrangea umbrella": {
    "group": [{
      "Name": "hydrangea umbrella",
      "DIY": "No",
      "Buy": "750",
      "Sell": "187",
      "HHA Base Points": "3",
      "Color 1": "Aqua",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaHydrangea0",
      "Internal ID": "6906",
      "Unique Entry ID": "dmFbrs5ALCJG4KpzB"
    }],
    "type": "Umbrellas"
  },
  "kabuki umbrella": {
    "group": [{
      "Name": "kabuki umbrella",
      "DIY": "No",
      "Buy": "1670",
      "Sell": "417",
      "HHA Base Points": "3",
      "Color 1": "Purple",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaKabuki0",
      "Internal ID": "7177",
      "Unique Entry ID": "QenZWqPCSZr9ZCrRh"
    }],
    "type": "Umbrellas"
  },
  "kiwi umbrella": {
    "group": [{
      "Name": "kiwi umbrella",
      "DIY": "No",
      "Buy": "1550",
      "Sell": "387",
      "HHA Base Points": "3",
      "Color 1": "Green",
      "Color 2": "Brown",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaKiwi0",
      "Internal ID": "6908",
      "Unique Entry ID": "R9WBMjgoqLwiR3h76"
    }],
    "type": "Umbrellas"
  },
  "lacy parasol": {
    "group": [{
      "Name": "lacy parasol",
      "DIY": "No",
      "Buy": "1550",
      "Sell": "387",
      "HHA Base Points": "3",
      "Color 1": "White",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaLace0",
      "Internal ID": "9946",
      "Unique Entry ID": "8ND7Jkfb2fxLJaR7n"
    }],
    "type": "Umbrellas"
  },
  "ladybug umbrella": {
    "group": [{
      "Name": "ladybug umbrella",
      "DIY": "No",
      "Buy": "NFS",
      "Sell": "80",
      "HHA Base Points": "501",
      "Color 1": "Red",
      "Color 2": "Black",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Flick",
      "Season/Event": "Bug-Off",
      "Season/Event Exclusive": "Yes",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaLadybug0",
      "Internal ID": "8767",
      "Unique Entry ID": "rHNt3mx5hEEDRSRiD"
    }],
    "type": "Umbrellas"
  },
  "leaf umbrella": {
    "group": [{
      "Name": "leaf umbrella",
      "DIY": "Yes",
      "Buy": "NFS",
      "Sell": "300",
      "HHA Base Points": "103",
      "Color 1": "Green",
      "Color 2": "Green",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Crafting",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaLeaf0",
      "Internal ID": "6840",
      "Unique Entry ID": "ZpYcNAofgCtnPfLj5"
    }],
    "type": "Umbrellas"
  },
  "lemon umbrella": {
    "group": [{
      "Name": "lemon umbrella",
      "DIY": "No",
      "Buy": "770",
      "Sell": "192",
      "HHA Base Points": "3",
      "Color 1": "Yellow",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaGingham4",
      "Internal ID": "9954",
      "Unique Entry ID": "yKb3LfnWDwptRPAWK"
    }],
    "type": "Umbrellas"
  },
  "logo umbrella": {
    "group": [{
      "Name": "logo umbrella",
      "DIY": "No",
      "Buy": "650",
      "Sell": "162",
      "HHA Base Points": "3",
      "Color 1": "Blue",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaLogo0",
      "Internal ID": "7172",
      "Unique Entry ID": "sFtYCcv9wy78ujaZr"
    }],
    "type": "Umbrellas"
  },
  "maple-leaf umbrella": {
    "group": [{
      "Name": "maple-leaf umbrella",
      "DIY": "Yes",
      "Buy": "NFS",
      "Sell": "2800",
      "HHA Base Points": "201",
      "Color 1": "Orange",
      "Color 2": "Orange",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Crafting",
      "Season/Event": "maple leaves",
      "Season/Event Exclusive": "Yes",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaAutumn0",
      "Internal ID": "7169",
      "Unique Entry ID": "b5gL4xdKJPZPjhYZM"
    }],
    "type": "Umbrellas"
  },
  "melon umbrella": {
    "group": [{
      "Name": "melon umbrella",
      "DIY": "No",
      "Buy": "770",
      "Sell": "192",
      "HHA Base Points": "3",
      "Color 1": "Green",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaGingham1",
      "Internal ID": "9951",
      "Unique Entry ID": "oFFjNfN2G5BxasAem"
    }],
    "type": "Umbrellas"
  },
  "mini-flower-print umbrella": {
    "group": [{
      "Name": "mini-flower-print umbrella",
      "DIY": "No",
      "Buy": "750",
      "Sell": "187",
      "HHA Base Points": "3",
      "Color 1": "Pink",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaFlorets0",
      "Internal ID": "6914",
      "Unique Entry ID": "G9dRhHQxBzYJB5mmE"
    }],
    "type": "Umbrellas"
  },
  "mint umbrella": {
    "group": [{
      "Name": "mint umbrella",
      "DIY": "No",
      "Buy": "770",
      "Sell": "192",
      "HHA Base Points": "3",
      "Color 1": "Brown",
      "Color 2": "Green",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaGingham2",
      "Internal ID": "9952",
      "Unique Entry ID": "F6fPRcpqGqhQ5oq7F"
    }],
    "type": "Umbrellas"
  },
  "mush umbrella": {
    "group": [{
      "Name": "mush umbrella",
      "DIY": "Yes",
      "Buy": "NFS",
      "Sell": "1200",
      "HHA Base Points": "103",
      "Color 1": "Brown",
      "Color 2": "Beige",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Crafting",
      "Season/Event": "mushrooms",
      "Season/Event Exclusive": "Yes",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaMushroom0",
      "Internal ID": "7174",
      "Unique Entry ID": "LLSQNPiMBWXXdTYFo"
    }],
    "type": "Umbrellas"
  },
  "Nook Inc. umbrella": {
    "group": [{
      "Name": "Nook Inc. umbrella",
      "DIY": "No",
      "Buy": "NFS",
      "Sell": "3500",
      "HHA Base Points": "151",
      "Color 1": "Green",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "700",
      "Exchange Currency": "Nook Miles",
      "Source": "Nook Miles Redemption",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaRco0",
      "Internal ID": "9561",
      "Unique Entry ID": "GX9s8tDymkHYHztY3"
    }],
    "type": "Umbrellas"
  },
  "orange umbrella": {
    "group": [{
      "Name": "orange umbrella",
      "DIY": "Yes",
      "Buy": "NFS",
      "Sell": "1400",
      "HHA Base Points": "103",
      "Color 1": "Orange",
      "Color 2": "Yellow",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Crafting",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaOrange0",
      "Internal ID": "6912",
      "Unique Entry ID": "ovb5ZxHTXJtBWQQxF"
    }],
    "type": "Umbrellas"
  },
  "panda umbrella": {
    "group": [{
      "Name": "panda umbrella",
      "DIY": "No",
      "Buy": "1570",
      "Sell": "392",
      "HHA Base Points": "3",
      "Color 1": "White",
      "Color 2": "Black",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaPanda0",
      "Internal ID": "7170",
      "Unique Entry ID": "AJkrWywbkBfFpke5b"
    }],
    "type": "Umbrellas"
  },
  "paper parasol": {
    "group": [{
      "Name": "paper parasol",
      "DIY": "No",
      "Buy": "870",
      "Sell": "217",
      "HHA Base Points": "3",
      "Color 1": "Brown",
      "Color 2": "Green",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaBangasa0",
      "Internal ID": "7178",
      "Unique Entry ID": "Brvfu2wmEsgfpsfe6"
    }],
    "type": "Umbrellas"
  },
  "patterned vinyl umbrella": {
    "group": [{
      "Name": "patterned vinyl umbrella",
      "DIY": "No",
      "Buy": "750",
      "Sell": "187",
      "HHA Base Points": "3",
      "Color 1": "White",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaBoundary0",
      "Internal ID": "6918",
      "Unique Entry ID": "KzFYhiwG4WmgGuewi"
    }],
    "type": "Umbrellas"
  },
  "peach umbrella": {
    "group": [{
      "Name": "peach umbrella",
      "DIY": "Yes",
      "Buy": "NFS",
      "Sell": "1400",
      "HHA Base Points": "103",
      "Color 1": "Pink",
      "Color 2": "Green",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Crafting",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaPeach0",
      "Internal ID": "9947",
      "Unique Entry ID": "e7KPGj99m2g9dvYfe"
    }],
    "type": "Umbrellas"
  },
  "pear umbrella": {
    "group": [{
      "Name": "pear umbrella",
      "DIY": "Yes",
      "Buy": "NFS",
      "Sell": "1400",
      "HHA Base Points": "103",
      "Color 1": "Yellow",
      "Color 2": "Green",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Crafting",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "Not for sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaPear0",
      "Internal ID": "9950",
      "Unique Entry ID": "2kKFs5wG5ioHGbGda"
    }],
    "type": "Umbrellas"
  },
  "petal parasol": {
    "group": [{
      "Name": "petal parasol",
      "DIY": "No",
      "Buy": "1590",
      "Sell": "397",
      "HHA Base Points": "3",
      "Color 1": "White",
      "Color 2": "Yellow",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaMargaret0",
      "Internal ID": "7181",
      "Unique Entry ID": "5qqATjxvMpMHmcDns"
    }],
    "type": "Umbrellas"
  },
  "picnic umbrella": {
    "group": [{
      "Name": "picnic umbrella",
      "DIY": "No",
      "Buy": "770",
      "Sell": "192",
      "HHA Base Points": "3",
      "Color 1": "Purple",
      "Color 2": "Pink",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaGingham3",
      "Internal ID": "9953",
      "Unique Entry ID": "hvv9Bz2ey3iRvSnAL"
    }],
    "type": "Umbrellas"
  },
  "pineapple umbrella": {
    "group": [{
      "Name": "pineapple umbrella",
      "DIY": "No",
      "Buy": "1550",
      "Sell": "387",
      "HHA Base Points": "3",
      "Color 1": "Yellow",
      "Color 2": "Green",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaPineapple0",
      "Internal ID": "6910",
      "Unique Entry ID": "ohMyh5kSBGg8Zayyh"
    }],
    "type": "Umbrellas"
  },
  "pink shiny-bows parasol": {
    "group": [{
      "Name": "pink shiny-bows parasol",
      "DIY": "No",
      "Buy": "1620",
      "Sell": "405",
      "HHA Base Points": "3",
      "Color 1": "Pink",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaPacodarace0",
      "Internal ID": "7176",
      "Unique Entry ID": "PTvmPPNiXMZ4jhBKX"
    }],
    "type": "Umbrellas"
  },
  "pink umbrella": {
    "group": [{
      "Name": "pink umbrella",
      "DIY": "No",
      "Buy": "770",
      "Sell": "192",
      "HHA Base Points": "3",
      "Color 1": "Pink",
      "Color 2": "Pink",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaSchool0",
      "Internal ID": "7164",
      "Unique Entry ID": "Cg8DXnxz3AtYJvdPE"
    }],
    "type": "Umbrellas"
  },
  "purple chic umbrella": {
    "group": [{
      "Name": "purple chic umbrella",
      "DIY": "No",
      "Buy": "1620",
      "Sell": "405",
      "HHA Base Points": "3",
      "Color 1": "Purple",
      "Color 2": "Black",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaPacoda0",
      "Internal ID": "7183",
      "Unique Entry ID": "2dXt6F6XwMf346Zbv"
    }],
    "type": "Umbrellas"
  },
  "purple shiny-bows parasol": {
    "group": [{
      "Name": "purple shiny-bows parasol",
      "DIY": "No",
      "Buy": "1620",
      "Sell": "405",
      "HHA Base Points": "3",
      "Color 1": "Purple",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaPacodarace1",
      "Internal ID": "12133",
      "Unique Entry ID": "J6FrqXxBPqGNBs4sC"
    }],
    "type": "Umbrellas"
  },
  "rainbow umbrella": {
    "group": [{
      "Name": "rainbow umbrella",
      "DIY": "No",
      "Buy": "840",
      "Sell": "210",
      "HHA Base Points": "3",
      "Color 1": "Colorful",
      "Color 2": "Colorful",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaRainbow0",
      "Internal ID": "7179",
      "Unique Entry ID": "P9bMZJY3n2dtooq5X"
    }],
    "type": "Umbrellas"
  },
  "raindrop umbrella": {
    "group": [{
      "Name": "raindrop umbrella",
      "DIY": "No",
      "Buy": "750",
      "Sell": "187",
      "HHA Base Points": "3",
      "Color 1": "Yellow",
      "Color 2": "Aqua",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaRain0",
      "Internal ID": "6913",
      "Unique Entry ID": "Djdj6KiSLh82BHzqB"
    }],
    "type": "Umbrellas"
  },
  "red chic umbrella": {
    "group": [{
      "Name": "red chic umbrella",
      "DIY": "No",
      "Buy": "1620",
      "Sell": "405",
      "HHA Base Points": "3",
      "Color 1": "Red",
      "Color 2": "Black",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaPacodarace6",
      "Internal ID": "12138",
      "Unique Entry ID": "kKoJtAcxMDNKq7tNu"
    }],
    "type": "Umbrellas"
  },
  "red umbrella": {
    "group": [{
      "Name": "red umbrella",
      "DIY": "No",
      "Buy": "770",
      "Sell": "192",
      "HHA Base Points": "3",
      "Color 1": "Red",
      "Color 2": "Red",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaStandard1",
      "Internal ID": "9958",
      "Unique Entry ID": "Z9yCA3wawXdQsbLSs"
    }],
    "type": "Umbrellas"
  },
  "snowflake umbrella": {
    "group": [{
      "Name": "snowflake umbrella",
      "DIY": "No",
      "Buy": "1550",
      "Sell": "387",
      "HHA Base Points": "3",
      "Color 1": "Aqua",
      "Color 2": "Aqua",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaCrystal0",
      "Internal ID": "6905",
      "Unique Entry ID": "r5RwHucDKWJPg7dkv"
    }],
    "type": "Umbrellas"
  },
  "spider umbrella": {
    "group": [{
      "Name": "spider umbrella",
      "DIY": "No",
      "Buy": "840",
      "Sell": "210",
      "HHA Base Points": "3",
      "Color 1": "Black",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaSpider0",
      "Internal ID": "7173",
      "Unique Entry ID": "aaQhimbednGniK4NF"
    }],
    "type": "Umbrellas"
  },
  "strawberry umbrella": {
    "group": [{
      "Name": "strawberry umbrella",
      "DIY": "No",
      "Buy": "1550",
      "Sell": "387",
      "HHA Base Points": "3",
      "Color 1": "Pink",
      "Color 2": "Green",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaStrawberry0",
      "Internal ID": "6907",
      "Unique Entry ID": "kKQHooYToACDqoqBm"
    }],
    "type": "Umbrellas"
  },
  "striped umbrella": {
    "group": [{
      "Name": "striped umbrella",
      "DIY": "No",
      "Buy": "750",
      "Sell": "187",
      "HHA Base Points": "3",
      "Color 1": "Gray",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaStripe0",
      "Internal ID": "6916",
      "Unique Entry ID": "hF2THDnHbEJWTDT8L"
    }],
    "type": "Umbrellas"
  },
  "sunny parasol": {
    "group": [{
      "Name": "sunny parasol",
      "DIY": "No",
      "Buy": "750",
      "Sell": "187",
      "HHA Base Points": "3",
      "Color 1": "Yellow",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaSunflower0",
      "Internal ID": "6904",
      "Unique Entry ID": "thr45xserbQqAm6o4"
    }],
    "type": "Umbrellas"
  },
  "tartan-check umbrella": {
    "group": [{
      "Name": "tartan-check umbrella",
      "DIY": "No",
      "Buy": "750",
      "Sell": "187",
      "HHA Base Points": "3",
      "Color 1": "Red",
      "Color 2": "Green",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaPlaid0",
      "Internal ID": "6917",
      "Unique Entry ID": "HjZzRQKbMdXBKYawe"
    }],
    "type": "Umbrellas"
  },
  "Toad parasol": {
    "group": [{
      "Name": "Toad parasol",
      "DIY": "No",
      "Buy": "750",
      "Sell": "187",
      "HHA Base Points": "3",
      "Color 1": "Red",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaPolkadotRed",
      "Internal ID": "5861",
      "Unique Entry ID": "HnmPeaovKNwg7ZuBL"
    }],
    "type": "Umbrellas"
  },
  "two-tone umbrella": {
    "group": [{
      "Name": "two-tone umbrella",
      "DIY": "No",
      "Buy": "770",
      "Sell": "192",
      "HHA Base Points": "3",
      "Color 1": "Red",
      "Color 2": "Yellow",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaTwocolor0",
      "Internal ID": "7166",
      "Unique Entry ID": "Da4xWXq9D2RFLnyYj"
    }],
    "type": "Umbrellas"
  },
  "vinyl umbrella": {
    "group": [{
      "Name": "vinyl umbrella",
      "DIY": "No",
      "Buy": "770",
      "Sell": "192",
      "HHA Base Points": "3",
      "Color 1": "White",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaVinyl0",
      "Internal ID": "7165",
      "Unique Entry ID": "q4Eo8vxPLFCL4ppac"
    }],
    "type": "Umbrellas"
  },
  "watermelon umbrella": {
    "group": [{
      "Name": "watermelon umbrella",
      "DIY": "No",
      "Buy": "1550",
      "Sell": "387",
      "HHA Base Points": "3",
      "Color 1": "Red",
      "Color 2": "Green",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaWater0",
      "Internal ID": "6909",
      "Unique Entry ID": "JTchAPvto4vHBJANw"
    }],
    "type": "Umbrellas"
  },
  "white shiny-bows parasol": {
    "group": [{
      "Name": "white shiny-bows parasol",
      "DIY": "No",
      "Buy": "1620",
      "Sell": "405",
      "HHA Base Points": "3",
      "Color 1": "White",
      "Color 2": "White",
      "Size": "1x1",
      "Exchange Price": "NA",
      "Exchange Currency": "NA",
      "Source": "Nook's Cranny",
      "Source Notes": "Available in Nook's Cranny (upgraded only)",
      "Season/Event": "NA",
      "Season/Event Exclusive": "NA",
      "Gender": "Free",
      "Villager Gender": "Free",
      "Villager Equippable": "Yes",
      "Catalog": "For sale",
      "Version Added": "1.0.0",
      "Unlocked?": "Yes",
      "Filename": "UmbrellaPacodarace3",
      "Internal ID": "12135",
      "Unique Entry ID": "4btSNLBHRoocAXfgE"
    }],
    "type": "Umbrellas"
  }
}
export default umbrellas;