const InputActionTypes = {
  PICK_CATEGORY: 'PICK_CATEGORY',
  SET_CAT_ARRAY: 'SET_CAT_ARRAY',
  SET_FILTER_ARRAY: 'SET_FILTER_ARRAY',
  TOGGLE_FILTER: 'TOGGLE_FILTER',
  SEARCHFIELD_CHANGE: 'SEARCHFIELD_CHANGE',
  LOAD_ITEMS: 'LOAD_ITEMS',
  SET_SORT_BY: 'SET_SORT_BY'
}

export default InputActionTypes;