const InputActionTypes = {
  SET_CATEGORY: 'SET_CATEGORY',
  SET_FILTER: 'SET_FILTER',
  SET_CAT_ARRAY: 'SET_CAT_ARRAY',
  SET_FILTER_ARRAY: 'SET_FILTER_ARRAY',
  SEARCHFIELD_CHANGE: 'SEARCHFIELD_CHANGE',
  FILTER_ITEMS: 'FILTER_ITEMS',
  SORT_ITEMS: 'SORT_ITEMS'
}

export default InputActionTypes;